-- =============================================
-- IOP: Life Skills - LUNES (COMPLETO Y ÚNICO)
-- =============================================
-- Este script:
-- 1. ELIMINA todas las actividades existentes
-- 2. Inserta SOLO la actividad "Life Skills" con todas sus subactividades y párrafos
-- =============================================

-- PASO 1: Limpiar todas las actividades existentes
DO $$
BEGIN
    -- Primero eliminar referencias en group_schedules
    DELETE FROM group_schedules;
    RAISE NOTICE '🗑️  Todas las referencias en group_schedules eliminadas';
    
    -- Eliminar párrafos de actividades
    DELETE FROM activity_paragraphs;
    RAISE NOTICE '🗑️  Todos los párrafos de actividades eliminados';
    
    -- Eliminar subactividades
    DELETE FROM subactivities;
    RAISE NOTICE '🗑️  Todas las subactividades eliminadas';
    
    -- Eliminar actividades
    DELETE FROM activities;
    RAISE NOTICE '🗑️  Todas las actividades eliminadas';
    
    RAISE NOTICE '✅ Base de datos limpiada completamente';
END $$;

-- PASO 2: Insertar SOLO Life Skills con todas sus subactividades y párrafos
DO $$
DECLARE
    v_activity_id UUID;
    v_decision_making_id UUID;
    v_emotions_id UUID;
    v_daily_routines_id UUID;
    v_housework_id UUID;
    v_family_role_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Crear actividad "Life Skills"
    INSERT INTO activities (activity_name, description, is_active)
    VALUES ('Life Skills', 'Life Skills activities for IOP groups - Monday', TRUE)
    RETURNING activity_id INTO v_activity_id;
    RAISE NOTICE '✅ Actividad "Life Skills" creada con ID: %', v_activity_id;

    -- =============================================
    -- SUBACTIVIDAD 1: DECISION MAKING (40 párrafos)
    -- =============================================
    INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
    VALUES (v_activity_id, 'Decision making', 'Decision making skills and processes', TRUE)
    RETURNING subactivity_id INTO v_decision_making_id;
    RAISE NOTICE '✅ Subactividad "Decision making" creada';

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a session focused on understanding the psychological processes underlying decision-making. Clients explored how emotional regulation, impulsivity, and cognitive distortions influence the quality of their choices. Through guided discussion, participants identified past decisions made under stress and examined the role of automatic thinking. The therapist emphasized mindfulness as a grounding tool to improve problem-solving and promote deliberate, value-based decisions.', 1, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a cognitive-behavioral group aimed at enhancing clients'' ability to make adaptive choices in daily life. The discussion centered on identifying internal and external barriers such as fear of failure, avoidance, and perfectionistic thinking. Clients were encouraged to use structured frameworks—such as pros and cons analysis—to improve insight and confidence. The therapist reinforced self-efficacy and accountability as key components of autonomous decision-making.', 2, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a psychoeducational session on the stages of effective decision-making, emphasizing awareness, evaluation, and implementation. Clients practiced identifying the emotional triggers that cloud judgment and engaged in a scenario-based exercise to practice choosing alternatives aligned with long-term goals. The therapist provided feedback on each participant''s reasoning process and reinforced the importance of reflective thinking before action.', 3, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist guided clients through a problem-solving activity focused on distinguishing reactive from intentional decisions. The group discussed how anxiety, peer influence, and uncertainty contribute to indecisive behavior. Clients were taught strategies to tolerate ambiguity and delay impulsive responses. The therapist encouraged the use of self-monitoring techniques to track decision outcomes and strengthen adaptive behavioral patterns.', 4, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a group discussion on the relationship between emotional awareness and decision quality. Clients explored how avoidance and emotional suppression can result in poor or inconsistent choices. Through collaborative exercises, participants practiced labeling emotions prior to acting and linking decisions to personal values. The therapist highlighted the role of emotional intelligence in fostering self-directed growth and healthier interpersonal dynamics.', 5, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist introduced the concept of cognitive flexibility as a determinant of effective decision-making. Clients analyzed how rigid thought patterns and black-and-white thinking hinder the ability to evaluate multiple perspectives. The therapist provided interventions to promote adaptability, including reframing and perspective-taking. Group members reflected on recent choices and identified alternative paths that could have produced more balanced outcomes.', 6, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated an interactive session addressing impulsive versus deliberate decision-making. Clients examined personal situations where acting without reflection led to negative outcomes. Through cognitive restructuring exercises, participants practiced pausing before reacting to impulses. The therapist reinforced self-regulation techniques to improve behavioral control and promote mindful decision processes.', 7, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a group on decision-making under emotional distress. Clients discussed how intense affective states—such as anger or sadness—impair judgment. The therapist guided participants through grounding and breathing techniques to reduce emotional reactivity prior to making important choices. Group members verbalized strategies for maintaining clarity and consistency in future decision-making situations.', 8, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist provided psychoeducation on how core beliefs and schemas influence decision-making patterns. Clients explored how self-doubt, guilt, or the need for approval distort rational thinking. Through guided journaling, participants identified cognitive biases that repeatedly affect their ability to choose effectively. The therapist emphasized cognitive restructuring and confidence-building as mechanisms for healthier autonomy.', 9, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a values-based decision-making exercise, encouraging clients to identify actions aligned with personal ethics and long-term goals. The discussion focused on differentiating between short-term gratification and sustainable growth. The therapist highlighted how congruence between decisions and values contributes to emotional stability and reduced regret.', 10, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a goal-oriented group exploring how problem-solving and decision-making intersect. Clients were invited to analyze a current dilemma using step-by-step reasoning. The therapist modeled techniques such as identifying options, anticipating consequences, and evaluating realistic outcomes. Participants practiced applying these methods to everyday scenarios to strengthen executive functioning.', 11, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a group exploring the role of social pressure in personal decision-making. Clients processed experiences of conforming to others'' expectations at the expense of self-direction. The therapist facilitated assertiveness exercises and boundary-setting discussions to reinforce independent thinking. Participants reflected on the empowerment that comes from making self-driven choices.', 12, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist guided clients in examining how avoidance behaviors delay or prevent important decisions. Clients identified specific fears that lead to procrastination and indecision. The therapist introduced behavioral activation strategies to counter avoidance and build momentum through small, achievable actions. Group members reported increased awareness of how fear impacts follow-through.', 13, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist introduced the concept of "decision fatigue" and its psychological impact on consistency and motivation. Clients discussed how excessive options or overthinking contribute to burnout and disengagement. The therapist encouraged participants to simplify routines and create structured systems to reduce cognitive overload. Emphasis was placed on setting priorities and maintaining mental clarity.', 14, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a collaborative activity where clients role-played real-life decision-making situations, practicing communication, negotiation, and compromise. The therapist observed and provided constructive feedback, focusing on how assertiveness and emotional regulation improve outcomes. Participants reflected on the importance of maintaining self-respect while being receptive to others'' perspectives.', 15, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a reflection-based session examining how past trauma or negative experiences shape current decision-making tendencies. Clients identified patterns of overcontrol, avoidance, or dependency rooted in past events. The therapist provided grounding interventions and cognitive reframing to promote empowered and adaptive decision-making in the present.', 16, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a discussion on the connection between self-awareness and decision outcomes. Clients were encouraged to identify automatic thoughts that often precede poor choices. The therapist introduced cognitive delay techniques, teaching participants to pause and question the accuracy of their assumptions before acting. The group emphasized self-reflection as a foundation for consistent and rational decision-making.', 17, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a solution-focused session exploring how unrealistic expectations and perfectionism can interfere with decision-making. Clients processed experiences of overanalyzing minor details and delaying choices out of fear of error. The therapist modeled acceptance-based strategies to help clients tolerate imperfection and take committed action toward progress rather than paralysis.', 18, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a group exercise designed to highlight the impact of external influences—such as family, culture, or peers—on personal decision-making. Clients reflected on the difference between internal motivation and external validation. The therapist guided participants toward building autonomy and reinforcing self-determination as indicators of psychological maturity.', 19, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated an experiential learning session where clients mapped out recent decision pathways, tracing the emotions, triggers, and outcomes associated with each. The activity promoted metacognitive awareness and insight into habitual response patterns. The therapist reinforced the concept of behavioral accountability and the importance of learning from prior decisions without self-criticism.', 20, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a structured activity on the role of intuition and logic in the decision-making process. Clients explored the balance between emotional instinct and rational analysis. The therapist encouraged integrating both systems to achieve more holistic and confident choices. Group discussion emphasized that neither impulsivity nor overthinking leads to adaptive functioning.', 21, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist guided a group focused on risk assessment and realistic goal-setting as integral parts of decision-making. Clients practiced evaluating the potential benefits and consequences of hypothetical situations. The therapist emphasized tolerance for uncertainty as a sign of emotional growth and promoted gradual exposure to decision-making challenges to build confidence.', 22, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist provided psychoeducation on how stress physiology impacts cognitive clarity and executive functioning. Clients learned how chronic anxiety can narrow perspective and impair decision quality. The therapist introduced grounding and relaxation exercises to reduce arousal levels before making important choices, highlighting the mind-body connection in effective decision-making.', 23, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a motivational interviewing group aimed at strengthening commitment to responsible decision-making. Clients identified ambivalence about certain life changes and explored internal conflicts between comfort and growth. The therapist used reflective questioning to elicit self-motivated reasons for change, enhancing intrinsic motivation and self-trust.', 24, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a session centered on the consequences of avoidance and inaction. Clients discussed how postponing decisions can maintain feelings of helplessness and anxiety. The therapist introduced behavioral activation principles, encouraging participants to take small, manageable steps toward unresolved goals. The discussion emphasized the emotional relief that follows proactive engagement.', 25, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a mindfulness-based decision-making exercise focusing on the present moment. Clients practiced grounding before evaluating a current dilemma, learning to differentiate between impulsive urges and thoughtful intentions. The therapist highlighted the role of self-compassion in reducing fear-based decision errors and promoting clarity through emotional balance.', 26, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a cognitive-behavioral group exploring the influence of negative self-talk on daily decision-making. Clients identified how internalized criticism contributes to hesitation or impulsivity. The therapist introduced cognitive reframing techniques to replace self-defeating thoughts with constructive alternatives, fostering confidence and psychological flexibility in choice-making.', 27, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist guided clients through an exercise on emotional forecasting and its role in anticipating future consequences. Participants practiced evaluating how current emotions distort perception of long-term results. The therapist emphasized metacognitive strategies for identifying emotional bias, encouraging clients to delay decisions until a more neutral mindset is achieved.', 28, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a reflective group discussion addressing decision-making in relationships. Clients explored how attachment styles and fear of rejection shape interpersonal choices. The therapist encouraged insight into patterns of people-pleasing or emotional withdrawal and introduced assertiveness techniques to promote healthier relational decisions.', 29, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a practical skills-building session on time management as a component of effective decision-making. Clients examined how disorganization and avoidance contribute to rushed or poorly considered decisions. The therapist modeled prioritization methods, encouraging structure, routine, and consistency to enhance executive functioning and goal attainment.', 30, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a group on identifying impulsive thought patterns and their connection to reward-seeking behavior. Clients processed instances where the need for instant gratification led to regret or guilt. The therapist emphasized mindfulness-based impulse control strategies and encouraged reflection on delayed gratification as a marker of emotional maturity.', 31, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a psychoeducational session on self-determination theory, highlighting autonomy, competence, and relatedness as factors that enhance healthy decision-making. Clients were encouraged to assess whether their choices align with intrinsic motivation or external validation. The therapist promoted the idea that authentic decision-making strengthens identity coherence and self-worth.', 32, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a discussion exploring moral reasoning and ethical dilemmas in personal decision-making. Clients engaged in scenario-based exercises analyzing how values, empathy, and situational context influence behavior. The therapist highlighted the cognitive and emotional integration required for moral maturity and adaptive functioning.', 33, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist guided clients in examining how uncertainty tolerance impacts decision outcomes. Participants identified discomfort with ambiguity as a trigger for avoidance or control-seeking behaviors. The therapist provided grounding and acceptance-based interventions to build resilience in the face of unknown outcomes, fostering more adaptive responses.', 34, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a group focusing on the concept of "learned helplessness" and its effect on decision-making confidence. Clients recognized patterns of passivity formed through repeated negative experiences. The therapist implemented empowerment-based interventions, encouraging small, success-oriented decisions to rebuild self-efficacy and a sense of personal agency.', 35, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a strengths-based session encouraging clients to draw upon personal values, resilience, and coping resources when faced with challenging choices. Participants reflected on times when perseverance led to positive results. The therapist reinforced the use of self-awareness and gratitude as grounding mechanisms for stable and mindful decision-making.', 36, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a group discussion centered on the connection between cognitive distortions and everyday decision-making. Clients examined how all-or-nothing thinking, catastrophizing, and emotional reasoning can distort judgment and contribute to impulsive actions. The therapist provided psychoeducation on identifying and challenging these patterns through self-monitoring and cognitive reframing to enhance rational decision processes.', 37, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist led a skills-based session designed to strengthen critical thinking during high-stress situations. Clients discussed how external pressure and perceived urgency often lead to reactive decision-making. The therapist guided participants through structured problem-solving techniques, emphasizing the value of pausing, gathering information, and evaluating multiple perspectives before taking action.', 38, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist conducted a reflective session exploring how self-esteem and identity influence decision-making. Clients processed how internalized beliefs about competence or worthiness affect confidence when facing choices. The therapist introduced affirmations and behavioral experiments aimed at increasing trust in one''s judgment and promoting assertive, value-aligned decisions.', 39, TRUE),
        (v_activity_id, v_decision_making_id, 'IOP Therapist facilitated a cognitive-behavioral group emphasizing accountability and follow-through as integral components of effective decision-making. Clients reviewed past choices and evaluated outcomes based on consistency between intentions and actions. The therapist encouraged the development of realistic action plans, reinforcing the concept of personal responsibility as a foundation for long-term behavioral change.', 40, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Decision making"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 2: MANAGEMENT OF EMOTIONS (8 párrafos)
    -- =============================================
    INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
    VALUES (v_activity_id, 'Management of emotions', 'Emotional regulation and management strategies', TRUE)
    RETURNING subactivity_id INTO v_emotions_id;
    RAISE NOTICE '✅ Subactividad "Management of emotions" creada';

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_emotions_id, 'IOP Therapist facilitated a psychoeducational session on recognizing emotional triggers and their physiological manifestations. Clients learned to identify early warning signs of distress such as muscle tension, racing thoughts, and irritability. The therapist introduced grounding and mindfulness techniques to increase emotional regulation and prevent reactive behaviors.', 1, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist conducted a cognitive-behavioral group focused on understanding the connection between thoughts, feelings, and actions. Clients explored how distorted thinking patterns escalate emotional intensity. The therapist guided participants in restructuring maladaptive thoughts to promote balanced emotional responses and healthier coping mechanisms.', 2, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist led a process-oriented group exploring the difference between suppression, repression, and emotional regulation. Clients discussed personal tendencies to avoid or minimize difficult emotions. The therapist emphasized emotional labeling and acceptance as foundational tools for psychological resilience and self-awareness.', 3, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist facilitated an experiential session emphasizing the importance of emotional literacy. Clients practiced identifying and naming a wide range of emotions beyond the basic categories of anger, sadness, and fear. The therapist reinforced that expanding emotional vocabulary enhances communication, empathy, and interpersonal effectiveness.', 4, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist guided a group discussion on managing anger and frustration constructively. Clients analyzed situations that trigger reactive behavior and explored the role of unmet needs and perceived injustice. The therapist introduced techniques such as deep breathing, time-outs, and assertive expression to reduce escalation and promote self-control.', 5, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist conducted a session addressing emotional avoidance and its impact on long-term well-being. Clients reflected on patterns of distraction, overworking, or withdrawal used to escape uncomfortable emotions. The therapist provided psychoeducation on the paradox of avoidance and encouraged gradual exposure to distressing feelings to foster adaptive processing.', 6, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist led a mindfulness-based session aimed at improving clients'' tolerance for distressing emotions. Participants engaged in guided meditation and body-awareness exercises designed to observe emotions without immediate reaction. The therapist discussed the difference between reacting and responding, promoting emotional stability and cognitive clarity.', 7, TRUE),
        (v_activity_id, v_emotions_id, 'IOP Therapist facilitated a dialectical-behavioral group focused on emotion regulation and distress tolerance. Clients identified recent emotional episodes and analyzed the factors that intensified them. The therapist introduced DBT skills such as "Check the Facts" and "Opposite Action" to promote balanced emotional functioning and reduce impulsivity.', 8, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Management of emotions"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 3: DAILY ROUTINES (40 párrafos)
    -- =============================================
    INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
    VALUES (v_activity_id, 'Daily Routines', 'Establishing and maintaining daily routines for stability', TRUE)
    RETURNING subactivity_id INTO v_daily_routines_id;
    RAISE NOTICE '✅ Subactividad "Daily Routines" creada';

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a session focused on the development of consistent daily routines to support emotional and behavioral stability. Clients discussed the relationship between structure and psychological well-being. The therapist emphasized the role of predictability in reducing anxiety and promoting self-efficacy.', 1, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a cognitive-behavioral group exploring how disorganization and inconsistent schedules contribute to emotional dysregulation. Clients identified barriers to maintaining structure, such as procrastination and poor time perception. The therapist provided strategies for habit formation and behavioral reinforcement.', 2, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a psychoeducational session on the connection between circadian rhythm and mental health. Clients learned how sleep hygiene, nutrition, and exercise routines influence mood regulation and energy levels. The therapist reinforced the importance of maintaining consistent daily patterns to enhance overall functioning.', 3, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group discussion centered on creating balance between productivity and rest. Clients examined how overcommitment and avoidance behaviors disrupt daily stability. The therapist guided participants in developing structured schedules that include both goal-oriented and restorative activities.', 4, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a session emphasizing the psychological impact of routine predictability on cognitive organization. Clients reflected on how consistent routines reduce decision fatigue and support attention, motivation, and self-regulation. The therapist encouraged the use of planners and visual reminders as external aids.', 5, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a skills-based session teaching clients how to structure morning and evening routines that promote consistency and emotional readiness. Clients practiced identifying small, realistic habits that create a sense of mastery. The therapist emphasized incremental progress and behavioral reinforcement.', 6, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist guided a group focused on identifying how emotional states interfere with maintaining daily routines. Clients recognized how depressive symptoms, anxiety, or impulsivity disrupt consistency. The therapist introduced behavioral activation techniques to promote adherence and engagement in structured activities.', 7, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a mindfulness-based group highlighting the importance of intentionality in daily habits. Clients practiced setting intentions at the start of the day to increase focus and presence. The therapist reinforced mindful transitions between activities as a means of cultivating routine stability.', 8, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a problem-solving session in which clients identified environmental and psychological barriers that prevent routine maintenance. The therapist encouraged clients to modify environmental cues, reduce distractions, and establish accountability systems to sustain behavioral consistency.', 9, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a group exploring how self-discipline and intrinsic motivation contribute to successful daily routines. Clients discussed how self-reward systems and task prioritization can strengthen follow-through. The therapist provided psychoeducation on habit stacking and reinforcement schedules to build lasting behavioral patterns.', 10, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group session on the role of structure in emotional regulation and recovery. Clients examined how the absence of consistent routines can lead to disorganization, anxiety, and decreased motivation. The therapist provided tools for implementing daily schedules that support stability and predictability.', 11, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a psychoeducational session emphasizing the relationship between self-care routines and mental health maintenance. Clients explored how consistent engagement in hygiene, nutrition, and rest improves mood and self-esteem. The therapist encouraged developing personalized checklists to strengthen accountability.', 12, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a cognitive-behavioral group focused on identifying cognitive barriers to maintaining daily routines. Clients discussed internal obstacles such as perfectionism, procrastination, and negative self-talk. The therapist guided participants in cognitive restructuring to support adaptive behavior change.', 13, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a goal-oriented session in which clients designed a realistic daily plan incorporating essential tasks and coping activities. The therapist modeled task segmentation and time-blocking as strategies for improving consistency and reducing overwhelm.', 14, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist guided a group discussion on the psychological benefits of morning routines for setting the tone of the day. Clients explored how early structure influences motivation, focus, and affect regulation. The therapist encouraged implementation of gradual morning rituals that promote readiness and calm.', 15, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a process group examining the emotional resistance that arises when attempting to establish structure. Clients identified discomfort with routine as linked to control issues, avoidance, or low self-efficacy. The therapist provided supportive feedback to promote insight and behavioral flexibility.', 16, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a skills-training session emphasizing behavioral consistency in self-management. Clients practiced developing cue-based habits—linking daily behaviors to environmental triggers. The therapist highlighted the importance of reinforcement and repetition in building sustainable daily routines.', 17, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a group exploring how technology use impacts daily structure. Clients discussed how excessive screen time interferes with sleep hygiene, focus, and productivity. The therapist provided behavioral modification strategies, including digital boundaries and scheduled screen-free periods.', 18, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a motivational session addressing ambivalence toward routine formation. Clients reflected on both the perceived loss of spontaneity and the benefits of predictability. The therapist used motivational interviewing techniques to increase readiness for change and commitment to structured living.', 19, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a mindfulness-integrated session promoting awareness during transitions between daily activities. Clients practiced mindful pauses before shifting tasks to enhance focus and prevent emotional exhaustion. The therapist reinforced presence and intentional engagement as key elements of functional daily structure.', 20, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group session on developing structure as a foundation for emotional stability. Clients explored how predictable routines reduce uncertainty and increase a sense of control. The therapist emphasized the use of daily planners and consistent time management to enhance overall functioning.', 21, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a psychoeducational group examining the link between consistent routines and executive functioning. Clients discussed how establishing order improves organization, attention, and follow-through. The therapist provided strategies to strengthen cognitive control through repetition and environmental cues.', 22, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a skills-based session on balancing self-care, productivity, and leisure within a daily structure. Clients identified tendencies to overextend or neglect certain areas of functioning. The therapist modeled how balanced routines foster psychological well-being and prevent burnout.', 23, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group discussion on the importance of maintaining structure during periods of emotional instability. Clients shared experiences of how chaotic routines amplify symptoms of depression and anxiety. The therapist reinforced gradual behavioral activation to restore consistency and confidence.', 24, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a group focused on identifying and modifying unhelpful habits that interfere with daily productivity. Clients analyzed triggers leading to avoidance or distraction. The therapist introduced habit reversal and substitution techniques to promote more adaptive behavioral patterns.', 25, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist guided a session centered on planning daily activities aligned with personal values and treatment goals. Clients reflected on how purposeful structure enhances motivation and self-direction. The therapist provided tools for prioritization and reinforcement of goal-consistent behavior.', 26, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a cognitive-behavioral session examining how negative emotions disrupt adherence to daily structure. Clients identified thought patterns such as defeatism or self-doubt that reduce task completion. The therapist guided participants in reframing thoughts to support follow-through and accountability.', 27, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group focused on using external supports to maintain routine consistency. Clients discussed the benefits of reminders, visual schedules, and peer accountability. The therapist encouraged integration of support systems to improve reliability and reduce forgetfulness.', 28, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a mindfulness-based session emphasizing the role of awareness in routine maintenance. Clients practiced staying present during repetitive tasks to reduce boredom and disengagement. The therapist reinforced mindful attention as a method of cultivating satisfaction and emotional regulation.', 29, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a reflective group exploring how unexpected changes affect routine adherence. Clients processed frustration and loss of control when plans are disrupted. The therapist introduced flexibility training, encouraging adaptability while maintaining core structure to preserve emotional balance.', 30, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a group session focused on how consistent daily structure supports behavioral regulation and emotional predictability. Clients examined the connection between unstructured time and increased impulsivity. The therapist emphasized time-blocking and realistic scheduling as effective tools for self-management.', 31, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a psychoeducational group highlighting how daily routines contribute to long-term recovery and relapse prevention. Clients discussed the role of structure in maintaining focus, stability, and accountability. The therapist encouraged identifying key anchor activities that promote continuity and self-discipline.', 32, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a session examining the impact of lifestyle balance within daily routines. Clients assessed how neglecting certain areas—such as nutrition, rest, or exercise—affects cognitive clarity and emotional resilience. The therapist reinforced gradual integration of healthy habits to achieve equilibrium.', 33, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a process-oriented discussion on the psychological resistance to routine building. Clients explored feelings of monotony, control, and fear of failure associated with structure. The therapist normalized resistance and provided cognitive-behavioral strategies for increasing motivation and engagement.', 34, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a skills-development group on using behavioral cues to establish sustainable daily habits. Clients practiced linking new behaviors to existing routines, reinforcing consistency through environmental association. The therapist emphasized behavioral momentum and the power of small, repeated actions.', 35, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a goal-setting session where clients outlined a personalized daily plan addressing physical, emotional, and cognitive domains. The therapist guided participants in setting measurable, attainable goals and highlighted the connection between structure and self-efficacy.', 36, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a mindfulness-integrated session exploring intentionality in routine actions. Clients practiced grounding during routine tasks, such as morning preparation or meal organization, to increase awareness and presence. The therapist reinforced mindful structure as a means to reduce anxiety and impulsivity.', 37, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist conducted a group focused on identifying unproductive behaviors that disrupt daily organization. Clients analyzed avoidance patterns such as oversleeping, excessive screen time, or procrastination. The therapist provided behavioral substitution strategies and encouraged positive reinforcement for adaptive change.', 38, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist led a discussion on the emotional benefits of maintaining a consistent evening routine. Clients explored how nightly structure contributes to better sleep hygiene and improved morning functioning. The therapist encouraged journaling and relaxation rituals as transitional tools for emotional decompression.', 39, TRUE),
        (v_activity_id, v_daily_routines_id, 'IOP Therapist facilitated a psychoeducational group emphasizing adaptability within structured living. Clients discussed the need for flexibility when unexpected events occur without abandoning their overall framework. The therapist guided participants in balancing consistency with self-compassion to sustain emotional stability and personal progress.', 40, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Daily Routines"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 4: HOUSEWORK MANAGEMENT (44 párrafos)
    -- =============================================
    INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
    VALUES (v_activity_id, 'Housework Management', 'Managing household tasks and responsibilities', TRUE)
    RETURNING subactivity_id INTO v_housework_id;
    RAISE NOTICE '✅ Subactividad "Housework Management" creada';

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a skills-based session focused on developing organization and structure in completing household responsibilities. Clients explored how disorganization can increase stress and emotional overload. The therapist emphasized time management and task segmentation as techniques to enhance consistency and self-efficacy in home maintenance.', 1, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a group discussion on the relationship between environmental order and mental health. Clients identified how cluttered spaces contribute to cognitive fatigue and irritability. The therapist encouraged the use of cleaning routines as behavioral activation strategies to promote emotional regulation and productivity.', 2, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a psychoeducational session highlighting the role of executive functioning in managing housework effectively. Clients learned to prioritize tasks, plan ahead, and distribute effort throughout the week. The therapist provided cognitive-behavioral tools to reduce procrastination and enhance goal-directed behavior.', 3, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a process-oriented group focused on overcoming avoidance behaviors related to domestic chores. Clients examined how feelings of overwhelm and low motivation interfere with daily functioning. The therapist introduced behavioral activation and reinforcement scheduling to support gradual progress.', 4, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist guided a group exploring the emotional satisfaction associated with maintaining a clean and organized environment. Clients reflected on how visual order contributes to psychological calm and self-esteem. The therapist emphasized mindfulness while completing household tasks to strengthen grounding and focus.', 5, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a problem-solving session in which clients identified barriers to managing home responsibilities, such as poor time estimation or low energy. The therapist guided participants through practical strategies including task breakdown, visual planning, and accountability pairing.', 6, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a cognitive-behavioral group addressing negative thought patterns that interfere with home management. Clients recognized self-critical beliefs such as "I''ll never catch up" or "It''s too much to handle." The therapist introduced reframing techniques to replace these cognitions with realistic and encouraging statements.', 7, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a session emphasizing the therapeutic use of routine in household maintenance. Clients discussed how predictable cleaning schedules contribute to stability and a sense of mastery. The therapist encouraged pairing neutral tasks with positive stimuli, such as music, to enhance motivation and mood.', 8, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist guided a group discussion on the importance of delegation and shared responsibility within the home environment. Clients explored the psychological impact of imbalance and overburdening. The therapist promoted assertive communication and boundary setting as tools for cooperative household management.', 9, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a mindfulness-based group integrating present-moment awareness into daily housework. Clients practiced focusing on sensory experience while completing simple tasks. The therapist highlighted how mindful attention can transform routine chores into grounding and self-soothing practices that reduce anxiety and emotional reactivity.', 10, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a session emphasizing the connection between environmental structure and emotional regulation. Clients discussed how maintaining a tidy living space can reduce cognitive overload and promote calm. The therapist introduced behavioral reinforcement techniques to increase consistency in completing household chores.', 11, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a skills-training group focused on task initiation and follow-through in home maintenance. Clients identified patterns of avoidance and perfectionism that lead to incomplete chores. The therapist provided stepwise planning methods and encouraged self-reward systems to strengthen motivation.', 12, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a cognitive-behavioral session examining how distorted thinking contributes to neglecting domestic responsibilities. Clients explored beliefs related to helplessness and low self-efficacy. The therapist modeled cognitive restructuring to transform negative self-talk into actionable goals.', 13, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a group on the psychological benefits of cleanliness and organization. Clients reflected on how environmental control improves mood stability and focus. The therapist encouraged developing short, achievable cleaning routines as a strategy for increasing autonomy and emotional grounding.', 14, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist guided a group activity in which clients created visual home-care schedules. The therapist emphasized the use of color-coded lists and time-blocking to improve adherence. Clients discussed how external structure helps compensate for executive functioning challenges and prevents task avoidance.', 15, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a process-oriented discussion exploring emotional barriers to household management. Clients identified shame, fatigue, or frustration as deterrents to productivity. The therapist validated these emotions and encouraged self-compassion while implementing small, realistic behavioral changes.', 16, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a group focusing on adaptive coping strategies through home organization. Clients learned to use domestic tasks as grounding tools during moments of emotional dysregulation. The therapist reinforced how engaging in physical activity, such as cleaning or organizing, can redirect energy constructively.', 17, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a psychoeducational session highlighting the importance of environmental cues in habit formation. Clients explored how visual clutter or disorganization can trigger avoidance. The therapist introduced cue-based habit stacking to associate cleaning behaviors with existing daily routines.', 18, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a session on the relationship between self-care and environmental maintenance. Clients processed how neglecting household responsibilities often mirrors emotional withdrawal. The therapist provided education on the reciprocal influence between personal hygiene, living space organization, and psychological wellness.', 19, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a mindfulness-integrated session where clients practiced present-moment awareness during household tasks. Participants engaged in grounding visualization while folding laundry and organizing items. The therapist emphasized that mindful housework promotes focus, sensory regulation, and internal calm.', 20, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a group session focused on establishing structured cleaning routines to promote consistency and reduce overwhelm. Clients discussed how unpredictability and clutter contribute to irritability and loss of motivation. The therapist emphasized the use of daily checklists and graded task completion to reinforce a sense of accomplishment.', 21, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a psychoeducational group examining how executive dysfunction affects home organization. Clients learned how deficits in planning, sequencing, and time estimation interfere with routine completion. The therapist introduced compensatory strategies such as task chunking and visual cues to enhance functioning.', 22, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a group discussion on the emotional symbolism of personal spaces. Clients reflected on how maintaining their environment mirrors self-worth and psychological stability. The therapist encouraged reframing cleaning as an act of self-respect rather than obligation, fostering intrinsic motivation.', 23, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a skills-based session targeting procrastination in domestic responsibilities. Clients explored triggers such as fear of failure or low energy that lead to task avoidance. The therapist introduced activation cues, positive reinforcement, and behavioral accountability methods to promote follow-through.', 24, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a mindfulness-oriented group on bringing intentionality to housework. Clients practiced focusing on sensory experiences—sounds, textures, and movements—while completing simple chores. The therapist highlighted mindfulness as a method for emotional grounding and cognitive clarity.', 25, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a discussion on how environmental chaos can perpetuate symptoms of anxiety and depression. Clients analyzed how clutter increases cognitive load and decreases focus. The therapist provided structured cleaning strategies that align with behavioral activation principles.', 26, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a session exploring task delegation and shared responsibility within the household. Clients identified difficulties with communication or control that prevent cooperation. The therapist modeled assertive requests and boundary-setting to promote equitable home management.', 27, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a problem-solving group centered on adapting home management strategies to fluctuating energy levels. Clients discussed pacing techniques and prioritizing essential chores on low-energy days. The therapist reinforced self-compassion while maintaining functional structure.', 28, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a psychoeducational session on using environmental design to support behavioral consistency. Clients learned how physical arrangement—such as placing frequently used items within view—can cue action and minimize decision fatigue. The therapist emphasized aligning environment with intentional living.', 29, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a reflective group on the emotional rewards of environmental mastery. Clients shared how completing household tasks contributes to a sense of order and control. The therapist validated these experiences and encouraged participants to recognize progress as a form of emotional regulation.', 30, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a session focused on developing adaptive coping through structured home maintenance. Clients explored how completing small domestic tasks enhances agency and reduces feelings of helplessness. The therapist emphasized behavioral activation as a tool to improve motivation and daily functioning.', 31, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a cognitive-behavioral group examining how self-critical thought patterns interfere with consistent household upkeep. Clients identified beliefs such as "It''s pointless" or "I can''t keep up," which perpetuate avoidance. The therapist guided reframing exercises to replace these distortions with realistic, encouraging self-statements.', 32, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a group discussion emphasizing the link between environmental stability and emotional containment. Clients reflected on how external order promotes internal calm. The therapist encouraged gradual organization of one area at a time to reduce overwhelm and promote psychological balance.', 33, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a skills-development session addressing time perception and task planning. Clients practiced breaking down chores into specific, timed segments to prevent fatigue and procrastination. The therapist reinforced the use of visual timers and progress tracking to increase consistency.', 34, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist guided a mindfulness-based session incorporating present-moment focus during household tasks. Clients practiced sensory awareness—attention to breath, movement, and sound—while discussing how mindfulness transforms mundane activities into grounding experiences. The therapist emphasized this as a method to reduce anxiety and enhance self-regulation.', 35, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a group exploring the emotional connection between self-image and home environment. Clients discussed how clutter may symbolize internal chaos or emotional neglect. The therapist encouraged participants to view home care as a practice of self-compassion and restoration.', 36, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a psychoeducational session on behavioral reinforcement and its role in habit formation. Clients identified personal rewards and intrinsic motivators for completing home-related tasks. The therapist highlighted how consistent reinforcement strengthens behavioral patterns and increases self-efficacy.', 37, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a problem-solving group focusing on managing distractions during housework. Clients discussed difficulties with maintaining attention and task completion. The therapist introduced environmental control techniques—such as setting alarms, minimizing sensory overload, and structuring short work intervals—to promote focus.', 38, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a process-oriented session on emotion regulation through physical organization. Clients explored how repetitive tasks like folding, sorting, or cleaning can be used as grounding mechanisms during heightened stress. The therapist validated these behaviors as healthy coping alternatives to avoidance or rumination.', 39, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a group addressing the psychological impact of cleanliness standards and perfectionism. Clients identified how rigid expectations lead to frustration and exhaustion. The therapist guided cognitive restructuring to foster flexibility, balance, and satisfaction with "good enough" levels of accomplishment.', 40, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a session on the connection between environmental order and mental health maintenance. Clients explored how maintaining organized spaces supports emotional stability and cognitive clarity. The therapist introduced structured cleaning schedules as a form of self-care and stress management.', 41, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist conducted a group focused on identifying and addressing emotional barriers to home maintenance. Clients processed feelings of shame, overwhelm, or inadequacy that prevent consistent household care. The therapist provided validation and cognitive-behavioral strategies to overcome these obstacles.', 42, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist led a skills-based session on developing sustainable household management routines. Clients practiced creating realistic schedules that accommodate energy fluctuations and life demands. The therapist emphasized flexibility and self-compassion as essential components of long-term maintenance.', 43, TRUE),
        (v_activity_id, v_housework_id, 'IOP Therapist facilitated a mindfulness-integrated group exploring the therapeutic benefits of mindful housework. Clients practiced bringing awareness to each task, noticing physical sensations and emotional responses. The therapist reinforced how present-moment engagement transforms routine chores into opportunities for emotional regulation and self-care.', 44, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Housework Management"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 5: ROLE OF THE FAMILY IN LIFE SKILLS (36 párrafos)
    -- =============================================
    INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
    VALUES (v_activity_id, 'Role of the family in life skills', 'Understanding family dynamics and their impact on life skills development', TRUE)
    RETURNING subactivity_id INTO v_family_role_id;
    RAISE NOTICE '✅ Subactividad "Role of the family in life skills" creada';

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a psychoeducational group exploring the family''s influence on the development of adaptive life skills. Clients discussed how early modeling of behaviors such as communication, organization, and problem-solving shapes current coping strategies. The therapist emphasized awareness of intergenerational learning patterns to promote intentional change.', 1, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a group session examining the role of family systems in emotional regulation and daily functioning. Clients identified how family dynamics—such as enmeshment, rigidity, or support—affect their ability to maintain independence. The therapist introduced strategies to differentiate personal needs from familial expectations.', 2, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a process-oriented discussion on how family interactions reinforce or hinder skill acquisition. Clients reflected on family messages regarding responsibility, autonomy, and emotional expression. The therapist encouraged reframing unhelpful patterns and establishing healthy boundaries.', 3, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a cognitive-behavioral group addressing the impact of learned family roles on behavior and self-perception. Clients explored how roles such as "caretaker," "peacemaker," or "scapegoat" influence decision-making and interpersonal effectiveness. The therapist guided insight-building exercises to promote adaptive role restructuring.', 4, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist guided a session centered on identifying supportive and unsupportive family influences in personal growth. Clients analyzed how validation, criticism, or neglect from family members shaped their self-efficacy. The therapist reinforced the development of self-validation as a means of emotional autonomy.', 5, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a discussion on communication patterns within families and their effect on the acquisition of social and problem-solving skills. Clients practiced assertive and empathetic responses through role-play. The therapist emphasized the importance of clear, respectful communication in fostering emotional maturity.', 6, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a group on the relationship between family expectations and stress management. Clients discussed how pressure to meet unrealistic standards contributes to perfectionism and anxiety. The therapist introduced cognitive reframing techniques to promote self-acceptance and reduce emotional reactivity.', 7, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a session focused on family as a source of both support and conflict in daily functioning. Clients identified situations in which family involvement enhances or impedes progress toward independence. The therapist guided participants in developing strategies for healthy interdependence and boundary-setting.', 8, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a group exploring the role of cultural and generational differences within families and how they shape values, priorities, and coping mechanisms. Clients discussed the challenges of balancing family traditions with personal identity. The therapist reinforced assertive communication as a bridge between cultural respect and self-expression.', 9, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a reflective group examining the emotional impact of family support systems in recovery and self-management. Clients shared experiences of encouragement, misunderstanding, or absence of support. The therapist emphasized the development of external support networks to complement family connections and strengthen resilience.', 10, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a group session exploring how family modeling influences the acquisition of daily life skills. Clients identified early messages learned from caregivers about responsibility and problem-solving. The therapist emphasized the significance of healthy modeling and corrective experiences in adulthood.', 11, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a psychoeducational group on attachment patterns and their impact on autonomy. Clients examined how early family relationships shaped confidence, trust, and emotional self-regulation. The therapist guided reflection on ways to build secure attachment behaviors in current family interactions.', 12, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a discussion analyzing how family expectations can support or hinder personal growth. Clients shared experiences of feeling overprotected or pressured within their families. The therapist introduced boundary-setting strategies to enhance independence and emotional balance.', 13, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a session on family communication as a foundation for effective coping and interpersonal functioning. Clients practiced identifying unhealthy communication cycles such as criticism or withdrawal. The therapist modeled assertive and validating language to foster understanding and cooperation.', 14, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a group focused on intergenerational transmission of beliefs and behaviors. Clients discussed how family traditions influence decision-making, motivation, and resilience. The therapist emphasized increasing awareness to consciously choose adaptive behaviors that align with personal values.', 15, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a reflective group addressing the emotional role of the family as a support system during stress. Clients identified which family members contribute to feelings of safety or distress. The therapist guided the group in distinguishing between helpful and enabling behaviors.', 16, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a session exploring how inconsistent family boundaries affect emotional and behavioral regulation. Clients processed experiences of blurred roles and dependency. The therapist provided psychoeducation on structure, consistency, and mutual respect as components of healthy family systems.', 17, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a cognitive-behavioral session addressing family conflict and its influence on adaptive functioning. Clients identified cognitive distortions that arise during family disputes and practiced reframing them. The therapist encouraged perspective-taking and empathy to reduce reactivity.', 18, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a group examining family dynamics during times of transition or crisis. Clients reflected on how illness, loss, or relocation shifted their family roles and coping mechanisms. The therapist reinforced emotional flexibility and collaborative problem-solving to navigate change effectively.', 19, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a process-oriented discussion on the role of forgiveness and reconciliation in family relationships. Clients explored unresolved resentment and its impact on current emotional stability. The therapist promoted self-awareness and guided exercises in compassionate communication to support relational healing.', 20, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a session examining the influence of family dynamics on the formation of self-care and independence skills. Clients discussed how early overprotection or neglect affected their confidence in daily functioning. The therapist reinforced the use of gradual autonomy-building practices to enhance self-reliance.', 21, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a group discussion exploring how parental attitudes toward discipline and responsibility shape adult coping patterns. Clients analyzed how consistency or inconsistency in family rules impacted their emotional regulation. The therapist emphasized the value of structure and flexibility within family systems.', 22, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a cognitive-behavioral group focused on identifying unhelpful family beliefs that hinder problem-solving. Clients reflected on inherited mindsets such as "asking for help is weakness" or "conflict should be avoided." The therapist guided cognitive reframing to promote adaptive, reality-based thinking.', 23, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a psychoeducational group addressing how emotional validation within the family supports psychological resilience. Clients discussed experiences of being ignored, dismissed, or supported in childhood. The therapist encouraged awareness of emotional needs and modeling validation in current relationships.', 24, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist guided a process-oriented group centered on the family''s role in reinforcing motivation and goal setting. Clients shared memories of how encouragement or criticism from relatives affected their perseverance. The therapist highlighted positive reinforcement as an essential element in fostering achievement.', 25, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a session on intergenerational coping patterns and their effect on life skill development. Clients explored how family members managed stress and emotions, often repeating similar patterns unconsciously. The therapist introduced mindfulness techniques to increase awareness and interrupt maladaptive cycles.', 26, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a reflective discussion on how cultural values within families shape perceptions of responsibility, gender roles, and independence. Clients examined how cultural expectations align or conflict with their personal goals. The therapist encouraged bicultural integration and self-definition within family contexts.', 27, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a group on the relationship between family cohesion and adaptive functioning. Clients identified how emotional closeness or detachment influenced their social and communication abilities. The therapist emphasized maintaining balance between connection and individuality.', 28, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a skills-based session where clients practiced assertive communication to navigate family expectations. The therapist modeled techniques for expressing needs respectfully without guilt or defensiveness, promoting confidence and emotional regulation in family interactions.', 29, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a group exploring forgiveness as a developmental skill within the family context. Clients processed resentment, misunderstandings, and unresolved emotions toward relatives. The therapist introduced compassion-based interventions to facilitate emotional release and relational healing.', 30, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a psychoeducational session on family roles and their impact on emotional and behavioral development. Clients analyzed how rigid or flexible family structures influence self-expression and coping. The therapist encouraged insight into how early patterns continue to affect adult functioning.', 31, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist conducted a group focused on family support as a protective factor in mental health recovery. Clients identified relatives who contribute to stability versus those who create emotional strain. The therapist guided participants in strengthening supportive alliances while maintaining healthy distance from negative influences.', 32, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a reflective group on how communication styles within families affect self-esteem and confidence. Clients discussed experiences of invalidation or constructive feedback. The therapist introduced assertive dialogue strategies to foster empathy, respect, and psychological safety in communication.', 33, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist facilitated a process-oriented session exploring the effects of family conflict on emotional regulation. Clients examined patterns of avoidance, aggression, or triangulation observed in their households. The therapist emphasized emotional awareness and boundary-setting as mechanisms for conflict resolution.', 34, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist guided a discussion about how family expectations around success, independence, or caretaking influence adult functioning. Clients reflected on the internal pressure to meet unrealistic standards. The therapist introduced self-compassion techniques to reduce guilt and promote authentic goal-setting.', 35, TRUE),
        (v_activity_id, v_family_role_id, 'IOP Therapist led a session on the role of family rituals and routines in promoting cohesion and stability. Clients identified meaningful practices from their upbringing and how they can integrate them into adult life. The therapist emphasized that consistent, shared experiences strengthen emotional bonds and support resilience.', 36, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Role of the family in life skills"', v_paragraph_count;

    RAISE NOTICE '✅✅✅ COMPLETADO: Life Skills con todas sus subactividades y párrafos insertados ✅✅✅';

END $$;

-- Verificar que solo existe Life Skills
SELECT 
    a.activity_name,
    s.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs
FROM activities a
LEFT JOIN subactivities s ON s.activity_id = a.activity_id
LEFT JOIN activity_paragraphs ap ON ap.subactivity_id = s.subactivity_id
GROUP BY a.activity_name, s.subactivity_name
ORDER BY a.activity_name, s.subactivity_name;
