-- =============================================
-- IOP: Problem Solving - JUEVES - Generating Alternatives
-- =============================================
-- Este script inserta los 80 párrafos para "Generating Alternatives"
-- de la actividad "Problem Solving" para IOP del día JUEVES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Problem Solving"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'problem solving'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Problem Solving" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Problem Solving" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Generating Alternatives"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'generating alternatives'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Generating Alternatives', 'Developing skills to generate multiple alternatives in problem-solving', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Generating Alternatives" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Generating Alternatives" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 80 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured group session on generating alternatives within the problem-solving process. The therapist highlighted how cognitive rigidity and emotional overwhelm often limit clients'' ability to perceive multiple solutions. Through guided brainstorming and scenario-based exercises, clients practiced cognitive flexibility and were encouraged to identify at least three possible responses to a current personal challenge.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a skills-building session focused on expanding clients'' capacity to generate multiple alternatives when addressing everyday stressors. Emphasis was placed on the role of divergent thinking in adaptive functioning. Clients explored how automatic negative thoughts inhibit solution-focused reasoning and engaged in collaborative dialogue to develop more flexible approaches.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced the importance of generating alternatives as a critical component of effective problem-solving. Clients were guided to move beyond black-and-white thinking and examine more nuanced solutions to interpersonal and emotional conflicts. The therapist facilitated a values-based exercise that helped participants evaluate the emotional and practical implications of each alternative.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational group exploring how impulsivity and emotional reactivity interfere with generating adaptive solutions. The therapist utilized role-play activities to help clients pause before responding, identify possible courses of action, and reflect on potential consequences. Clients practiced developing this skill as a means of enhancing autonomy and preventing escalation.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive-behavioral exercise emphasizing the value of brainstorming diverse alternatives when confronted with stressors. Clients explored how limiting beliefs and rigid thought patterns restrict creative problem-solving. The therapist reinforced the importance of curiosity and open-ended questioning to increase perspective-taking and emotional regulation.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group focused on enhancing problem-solving repertoires through the generation of alternative coping strategies. Clients discussed how emotional distress often narrows cognitive processing, leading to impulsive or avoidant behaviors. The therapist guided participants through cognitive restructuring tasks to develop new behavioral and emotional responses to previously unresolved issues.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group intervention centered on cultivating flexible thinking through the generation of multiple alternatives to complex situations. Clients completed structured worksheets identifying triggers, perceived barriers, and possible actions. The therapist emphasized how cognitive flexibility and solution diversity improve resilience and emotion regulation.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an experiential session encouraging clients to use lateral thinking strategies to expand their problem-solving options. The session addressed common cognitive distortions such as catastrophizing and dichotomous thinking. Group feedback supported participants in evaluating the feasibility and potential outcomes of each proposed alternative.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist provided psychoeducation on the role of problem-solving flexibility in emotional well-being and relapse prevention. Clients examined how automatic reactions restrict their ability to evaluate diverse responses. Through collaborative brainstorming and peer feedback, each participant identified multiple alternative coping mechanisms for a personal stressor.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced the concept of solution generation as a foundational element of adaptive coping. The therapist modeled how shifting from reactive to proactive thinking can reveal several possible responses to one challenge. Clients practiced identifying both internal and external resources to develop creative, sustainable problem-solving strategies.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session focused on generating alternatives as a critical step in problem-solving. Clients were encouraged to practice divergent thinking, allowing multiple potential strategies to emerge without immediate evaluation. The therapist emphasized that broadening the range of options enhances cognitive flexibility and reduces reliance on rigid or maladaptive coping patterns.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through brainstorming exercises to strengthen their capacity for generating adaptive alternatives. Participants were encouraged to suspend judgment while considering creative and unconventional strategies. The therapist validated their contributions and highlighted how cultivating a wider repertoire of responses promotes resilience and adaptive functioning in daily life.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an intervention exploring barriers to generating alternatives, including cognitive rigidity and negative self-talk. Through guided prompts, participants practiced reframing challenges and identifying multiple possible courses of action. The therapist reinforced the therapeutic value of maintaining openness, curiosity, and problem-solving flexibility when confronting obstacles.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged the group in scenario-based practice where clients collaboratively generated alternative solutions to common emotional and interpersonal stressors. The session emphasized the role of collaboration, creativity, and critical thinking in strengthening adaptive coping skills. The therapist modeled flexibility and encouraged the group to evaluate both practical and innovative responses.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion linking the process of generating alternatives with emotional regulation. Clients reflected on how fixating on a single rigid solution can heighten anxiety and hopelessness. The therapist introduced cognitive mapping and role-play exercises to encourage exploration of diverse, realistic alternatives that support balanced emotional responses.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a structured group on generating alternatives to broaden clients'' problem-solving repertoires beyond habitual responses. The discussion emphasized divergent thinking as a means of exploring multiple strategies before narrowing to the most feasible one. The therapist highlighted that cultivating mental flexibility strengthens resilience and decreases cognitive rigidity.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through structured exercises aimed at promoting the generation of alternatives for managing personal and interpersonal challenges. Participants practiced withholding judgment while brainstorming potential strategies. The therapist underscored how broadening perspective supports adaptive coping, reduces avoidance, and enhances self-efficacy in stressful situations.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a skills-based session targeting barriers that limit the ability to generate alternatives, such as automatic negative thoughts and overgeneralization. Clients used guided prompts to reframe challenges and identify at least three actionable responses. The therapist validated their participation and reinforced the connection between creative thinking and effective problem-solving.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided the group through scenario-based problem-solving exercises to strengthen solution generation skills. Clients collaborated to develop both conventional and innovative strategies for managing stressors and reflected on the outcomes of each. The therapist emphasized how practicing open-mindedness fosters emotional regulation, decision-making confidence, and behavioral flexibility.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on the importance of generating alternatives to reduce impulsive or maladaptive decision-making. Clients explored past situations where limited options led to ineffective results. The therapist modeled brainstorming techniques and encouraged participants to apply cognitive flexibility and reflective reasoning to enhance daily coping strategies.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured session focused on generating alternatives as an essential step in effective problem-solving. Clients explored how cognitive rigidity and emotional reactivity often limit their ability to perceive multiple solutions. Through guided exercises and reflective discussion, participants practiced expanding their range of responses, promoting cognitive flexibility and adaptive coping in stressful situations.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group aimed at enhancing clients'' capacity for divergent thinking in problem-solving. Participants engaged in brainstorming activities designed to challenge automatic negative thoughts and rigid mental patterns. The therapist emphasized that developing multiple solutions increases emotional regulation and reduces reliance on avoidance or impulsivity.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a skills-building intervention focused on broadening clients'' perspectives when approaching problems. The group discussed how habitual thinking and fear of failure often restrict the generation of alternatives. The therapist introduced cognitive reframing techniques and guided participants through identifying at least three distinct approaches to current challenges.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution-oriented session where clients practiced generating creative and realistic alternatives to everyday stressors. The therapist encouraged a nonjudgmental mindset during brainstorming to promote curiosity and flexibility. Clients reflected on how broadening their options supports greater self-efficacy and emotional resilience.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided the group in identifying cognitive and emotional barriers that hinder alternative generation in problem-solving. Clients examined how overgeneralization and catastrophic thinking limit adaptive responses. The therapist modeled lateral thinking and encouraged participants to approach difficulties from new perspectives to foster problem-solving confidence.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group exercise designed to strengthen flexible thinking by generating multiple potential strategies for managing life stressors. Clients collaborated to identify creative and practical alternatives to interpersonal or personal conflicts. The therapist emphasized that maintaining openness to diverse solutions promotes emotional regulation and behavioral adaptability.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a cognitive-behavioral session on the role of generating alternatives in preventing impulsive decisions and emotional dysregulation. Clients discussed past experiences where limited options led to maladaptive outcomes. The therapist reinforced the importance of critical thinking and reflective reasoning to enhance long-term problem-solving efficacy.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on the connection between solution generation and executive functioning. Clients practiced developing alternative strategies for real-life dilemmas while analyzing potential outcomes of each. The therapist highlighted how practicing structured decision-making and cognitive flexibility strengthens self-control and goal-directed behavior.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through scenario-based exercises to practice generating multiple alternative responses to complex emotional or interpersonal issues. Participants discussed the advantages and drawbacks of each option. The therapist validated client participation and emphasized how adaptive problem-solving builds resilience and promotes functional independence.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational activity where clients learned to apply divergent thinking and creativity to everyday problems. The therapist explained that generating alternatives reduces learned helplessness and increases emotional empowerment. Clients worked collaboratively to develop practical and innovative strategies that aligned with their personal goals.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group intervention designed to promote cognitive flexibility by practicing the generation of multiple alternative solutions. Clients reflected on how rigid thinking patterns have previously limited problem-solving effectiveness. The therapist encouraged participants to explore diverse approaches and recognize that adaptability is key to psychological resilience.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a goal-directed group session emphasizing open-mindedness in problem-solving. Clients were guided to suspend premature judgment and brainstorm several possible approaches to a self-identified challenge. The therapist reinforced that developing alternatives fosters autonomy and strengthens self-efficacy in emotional regulation.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a collaborative workshop on the process of generating alternatives in decision-making. Clients examined how their mood states can affect creativity and flexibility. The therapist used guided questioning to promote awareness of how balanced emotional processing enhances problem-solving and reduces distress.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a skills-focused exercise that integrated cognitive restructuring with the generation of alternatives. Clients identified personal problems and developed three or more possible courses of action for each. The therapist underscored how this process supports executive functioning, goal-setting, and behavioral activation.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in a reflective problem-solving activity emphasizing how generating alternatives promotes psychological adaptability. Participants explored how emotional distress narrows thinking and practiced broadening perspective through guided prompts. The therapist highlighted the value of flexibility in sustaining motivation and preventing cognitive stagnation.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an interactive group session in which clients collaborated to generate alternatives for shared real-life stressors. The therapist modeled the use of cognitive mapping to visualize different pathways to resolution. Participants discussed how diversity of perspective enhances emotional tolerance and supports effective coping strategies.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session highlighting the link between solution generation and emotional regulation. Clients identified patterns of rigid or dichotomous thinking and replaced them with more flexible, balanced alternatives. The therapist emphasized that practicing this process regularly builds mental agility and promotes adaptive problem resolution.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group intervention encouraging clients to explore alternative strategies to overcome recurring challenges. The therapist introduced mindfulness-based techniques to help participants remain open and nonreactive while brainstorming. Clients reflected on how emotional awareness supports creativity and problem-solving persistence.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a guided exercise where clients identified current life problems and used divergent reasoning to develop at least three potential solutions. The therapist promoted group collaboration and reflective feedback to help participants assess the effectiveness and feasibility of their alternatives.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution-focused group session emphasizing adaptive flexibility and critical evaluation of generated alternatives. Clients explored how broadening their perspective during problem-solving enhances confidence and decreases avoidance. The therapist validated their insights and reinforced proactive engagement in decision-making processes.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive-behavioral group focused on the process of generating alternatives to enhance adaptive problem-solving. Clients explored how automatic thinking and rigid cognitive patterns often lead to ineffective decision-making. Through guided brainstorming and peer collaboration, participants practiced developing multiple strategies to address current challenges, promoting flexibility and self-efficacy.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led an experiential session emphasizing the importance of divergent thinking in effective problem resolution. Clients identified a recent personal or interpersonal stressor and worked to generate at least three alternative approaches. The therapist reinforced that cultivating multiple perspectives strengthens emotional regulation and prevents impulsive or avoidant responses.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session centered on expanding clients'' problem-solving repertoire through alternative generation. Participants discussed barriers such as overgeneralization and fear of failure that limit cognitive flexibility. The therapist provided strategies to enhance creative reasoning and validated efforts toward developing adaptive coping mechanisms.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured group exercise aimed at helping clients recognize how cognitive rigidity restricts their ability to generate effective solutions. Clients practiced open-ended questioning and brainstorming without judgment. The therapist highlighted how adopting a growth mindset supports resilience and long-term problem-solving success.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through scenario-based exercises that required them to generate alternative responses to emotionally charged situations. The session focused on distinguishing between reactive behaviors and reflective choices. The therapist emphasized that developing diverse options reduces distress and fosters autonomous decision-making.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a discussion on how emotional dysregulation can impair the capacity to identify viable solutions. Clients learned to use cognitive reframing to transform negative self-talk into productive thought patterns that support creative problem-solving. The therapist reinforced adaptive flexibility as a key factor in emotional stability and goal achievement.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group activity that integrated behavioral activation and solution generation. Clients collaboratively explored multiple strategies for resolving a common life challenge, focusing on evaluating the consequences of each. The therapist modeled rational decision-making and highlighted how balanced analysis supports functional outcomes.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a goal-oriented session emphasizing problem-solving flexibility and emotional awareness. Clients practiced generating alternative approaches to common daily stressors, identifying both practical and emotional benefits. The therapist encouraged participants to focus on process-oriented thinking rather than perfectionistic outcomes.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an interactive exercise promoting collaborative brainstorming to develop multiple coping alternatives. Clients were encouraged to reflect on the emotional, behavioral, and social implications of their choices. The therapist underscored the therapeutic value of shared insight in broadening perspective and enhancing interpersonal learning.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a solution-focused intervention highlighting the importance of adaptive flexibility in response to obstacles. Participants examined past problem-solving experiences to identify effective patterns and areas needing improvement. The therapist validated clients'' progress and linked alternative generation to increased emotional resilience.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive restructuring session to address the impact of dichotomous thinking on problem-solving efficacy. Clients were encouraged to move beyond "all-or-nothing" perspectives and identify incremental alternatives. The therapist emphasized that flexible thinking promotes balanced decision-making and stress reduction.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a skills-based session where clients practiced using mindfulness techniques to create mental space for generating alternatives. The discussion focused on how present-moment awareness enhances creativity and decreases reactivity. The therapist modeled grounded decision-making and reinforced cognitive openness.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational discussion on how past experiences and core beliefs influence the ability to generate diverse solutions. Clients identified recurring problem-solving patterns that hindered adaptability. The therapist provided feedback on strategies to challenge maladaptive schemas and foster cognitive flexibility.', 53),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in a guided reflective exercise designed to improve executive functioning during problem-solving. Clients analyzed how emotional intensity narrows thought processes and practiced generating alternatives under hypothetical stress scenarios. The therapist emphasized the importance of emotional regulation in supporting effective decision-making.', 54),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group dialogue linking solution generation to self-efficacy and psychological empowerment. Clients identified how expanding their problem-solving strategies reduced feelings of helplessness. The therapist encouraged participants to apply this process to real-life stressors to build confidence and functional autonomy.', 55),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a collaborative learning activity that encouraged clients to generate alternative coping responses in pairs. Participants reflected on how emotional triggers can bias their problem-solving process. The therapist emphasized the therapeutic role of peer feedback and perspective-taking in fostering adaptive solutions.', 56),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a problem-solving workshop integrating cognitive-behavioral and mindfulness techniques. Clients practiced slowing down their responses to increase clarity and explore multiple courses of action. The therapist reinforced how combining awareness and analytical reasoning enhances adaptive decision-making.', 57),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through role-play scenarios aimed at developing creative problem-solving and reducing automatic reactivity. Participants brainstormed alternative approaches to interpersonal challenges and evaluated emotional outcomes. The therapist validated efforts and linked flexibility in thinking to improved relational functioning.', 58),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention where clients explored how stress, perfectionism, and fear of criticism inhibit alternative generation. Through guided discussion, participants identified cognitive distortions that limit their problem-solving scope. The therapist provided corrective feedback and introduced strategies for balanced thinking.', 59),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-oriented session in which clients worked collaboratively to generate and refine multiple strategies for personal and social stressors. The therapist emphasized that effective problem-solving involves trial, evaluation, and revision. Participants learned that maintaining flexibility is essential for long-term emotional stability and goal-directed behavior.', 60),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive-behavioral group focused on the importance of generating alternatives as a key stage in effective problem-solving. Clients explored how emotional reactivity and rigid thinking can limit the range of possible solutions. Through guided exercises, they practiced expanding their perspectives, identifying multiple strategies to manage current stressors, and reinforcing cognitive flexibility to enhance emotional regulation.', 61),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational session emphasizing the role of divergent thinking in improving problem-solving outcomes. Clients discussed how habitual negative thought patterns restrict creativity and adaptability. The therapist guided participants in brainstorming alternative responses to personal challenges, highlighting how broadening solution options fosters self-efficacy and psychological resilience.', 62),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention that integrated reflective reasoning and solution generation techniques. Clients identified a recurring problem and collaboratively developed several potential alternatives. The therapist modeled cognitive reframing to help participants evaluate the effectiveness and emotional impact of each option, promoting adaptive problem-solving behaviors.', 63),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a skills-development activity where clients were encouraged to use open-ended thinking to generate alternatives to stressful life events. The therapist emphasized the importance of delaying judgment during brainstorming to allow creativity and flexibility to emerge. This exercise aimed to enhance executive functioning and strengthen decision-making capacity.', 64),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a scenario-based exercise designed to increase awareness of automatic cognitive patterns that restrict problem-solving. Clients practiced identifying alternative courses of action to replace ineffective coping mechanisms. The therapist reinforced how diversifying options enhances emotional regulation and reduces impulsive responses to distress.', 65),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of how cognitive rigidity interferes with generating alternatives during high-stress situations. Clients participated in guided reflection to challenge all-or-nothing thinking and practiced replacing it with flexible, solution-focused reasoning. The therapist highlighted how these strategies promote psychological adaptability and reduce avoidant behaviors.', 66),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured problem-solving session where clients examined real-life stressors and collaboratively generated alternative coping strategies. The therapist encouraged nonjudgmental brainstorming to promote creativity and self-confidence in decision-making. Participants reflected on how cognitive flexibility leads to more effective and sustainable outcomes.', 67),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational discussion connecting solution generation to emotional balance and mental clarity. Clients explored how anxiety and frustration can narrow focus, making it difficult to envision multiple responses. The therapist introduced techniques for cognitive expansion, supporting participants in identifying varied and realistic solutions to current challenges.', 68),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exercise integrating behavioral activation and cognitive flexibility to strengthen problem-solving skills. Clients worked in pairs to identify stressors and develop at least three alternative solutions for each. The therapist emphasized the value of creativity and emotional regulation in maintaining functional problem-solving capacity.', 69),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a goal-directed intervention aimed at improving clients'' ability to generate adaptive alternatives under pressure. Participants analyzed the cognitive and emotional barriers that limit their problem-solving effectiveness. The therapist encouraged reflective self-awareness and strategic thinking to enhance long-term coping efficacy.', 70),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on the psychological benefits of generating multiple alternatives when faced with adversity. Clients reflected on how having several options reduces anxiety and increases perceived control. The therapist reinforced that flexibility in problem-solving contributes to resilience and more balanced emotional responses.', 71),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a cognitive restructuring activity aimed at identifying unhelpful thought patterns that restrict alternative generation. Clients practiced transforming rigid or defeatist perspectives into creative, actionable solutions. The therapist emphasized how consistent use of this technique promotes adaptive coping and empowered decision-making.', 72),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an experiential learning session where clients role-played challenging interpersonal scenarios to practice generating alternatives. The therapist facilitated reflection on how emotional triggers influence cognitive responses and encouraged balanced, flexible reasoning. Clients reported greater confidence in handling similar situations effectively.', 73),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-focused group emphasizing the relationship between problem-solving flexibility and emotional stability. Clients practiced brainstorming exercises that encouraged both creative and practical responses to complex problems. The therapist validated client insights and reinforced the therapeutic goal of fostering autonomy and cognitive adaptability.', 74),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a skills-enhancement session centered on using mindfulness to support the process of generating alternatives. Clients learned how staying grounded in the present moment reduces cognitive overload and supports clearer reasoning. The therapist linked mindful awareness to improved executive functioning and rational decision-making.', 75),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a reflective exercise encouraging clients to explore the connection between emotional regulation and the ability to generate multiple solutions. Participants identified past instances of limited problem-solving and discussed how emotional awareness could have expanded their choices. The therapist modeled insight-oriented questioning to deepen understanding.', 76),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a collaborative group session designed to improve problem-solving flexibility. Clients were encouraged to suspend negative judgments and engage in creative exploration of alternative solutions. The therapist emphasized how psychological flexibility strengthens resilience and prevents maladaptive coping responses.', 77),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in a cognitive-behavioral intervention aimed at increasing tolerance for uncertainty through alternative generation. Clients discussed how fear of failure or perfectionism restricts adaptability. The therapist modeled balanced thinking patterns and reinforced the role of cognitive expansion in emotional growth.', 78),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group reflection activity where clients analyzed personal barriers to generating alternatives, such as overgeneralization and self-doubt. The therapist introduced cognitive reframing strategies and encouraged participants to view challenges as opportunities for experimentation and learning, supporting growth-oriented behavior.', 79),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a process-oriented session on developing flexibility in thought and behavior through the generation of alternatives. Clients practiced identifying multiple possible actions for a single problem while discussing the emotional consequences of each choice. The therapist emphasized the importance of open-minded exploration as a pathway to emotional resilience and problem-solving competence.', 80);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Generating Alternatives" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'problem solving'
AND LOWER(sa.subactivity_name) = 'generating alternatives'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

