-- =============================================
-- IOP: Problem Solving - JUEVES - Possible Solution
-- =============================================
-- Este script crea la actividad "Problem Solving" para IOP del día JUEVES
-- e inserta los 80 párrafos para el objetivo "Possible Solution"
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener o crear la actividad "Problem Solving"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'problem solving'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        INSERT INTO activities (activity_name, description, activity_type, is_active)
        VALUES ('Problem Solving', 'Problem Solving activities for IOP groups - Thursday', 'IOP', TRUE)
        RETURNING activity_id INTO v_activity_id;
        RAISE NOTICE '✅ Actividad "Problem Solving" creada con ID: %', v_activity_id;
    ELSE
        RAISE NOTICE '✅ Actividad "Problem Solving" ya existe con ID: %', v_activity_id;
    END IF;

    -- Obtener o crear la subactividad "Possible Solution"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'possible solution'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Possible Solution', 'Exploring possible solutions as a critical phase of the structured problem-solving model', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Possible Solution" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Possible Solution" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 80 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session centered on the exploration of possible solutions as a critical phase of the structured problem-solving model. Clients were encouraged to generate a variety of alternatives without immediate judgment, fostering cognitive flexibility and creative thinking. The therapist emphasized the importance of brainstorming as a strategy to overcome cognitive rigidity often associated with depressive and anxious symptomatology.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced a problem-solving framework with a focus on expanding the client''s repertoire of adaptive responses. Clients worked in small groups to develop multiple solutions to hypothetical interpersonal dilemmas. The therapist highlighted how the ability to generate diverse options increases a sense of agency and reduces the likelihood of impulsive or avoidant behaviors when under emotional distress.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session in which clients identified a current problem and then engaged in a guided activity to explore at least three potential solutions. Emphasis was placed on evaluating the feasibility, risks, and emotional implications of each option. The therapist reinforced the value of solution-focused thinking in disrupting maladaptive behavioral cycles and promoting goal-directed action.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an experiential exercise aimed at helping clients shift from problem-saturated narratives toward proactive planning. Clients were supported in reframing challenges into solvable scenarios and were guided through the process of identifying potential steps toward resolution. The therapist provided psychoeducation on how emotional reasoning can obstruct effective problem-solving and encouraged evidence-based decision-making.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a cognitive-behavioral process of examining possible solutions to personal stressors. Clients practiced distinguishing between short-term relief strategies and sustainable long-term resolutions. The therapist modeled balanced problem analysis and promoted collaborative dialogue to help clients practice assertive communication when implementing chosen solutions.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured group discussion focused on the identification and evaluation of possible solutions to self-identified problems. Clients were encouraged to approach issues from multiple perspectives, enhancing problem-solving efficacy and emotional regulation. The therapist emphasized the importance of considering both internal and external resources when formulating action plans.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged the group in a cognitive-behavioral task designed to generate and assess alternative solutions to emotionally charged situations. Clients learned to distinguish between reactive and reflective decision-making processes and discussed how exploring various options can reduce perceived helplessness and promote adaptive functioning.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist presented a scenario-based exercise where clients collaboratively identified possible responses to common interpersonal stressors. The group processed how personal values, prior experiences, and emotional states can influence solution selection. The therapist reinforced the importance of selecting responses aligned with long-term well-being rather than immediate emotional relief.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a problem-solving workshop that involved role-play and peer feedback to explore alternative strategies to current challenges. Clients were supported in identifying at least two viable solutions to a real-life concern and discussed barriers to implementation. The therapist highlighted the therapeutic value of practicing mental flexibility in distress tolerance.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-focused intervention aimed at enhancing clients'' confidence in navigating daily challenges. Clients explored the difference between passive avoidance and active coping and were encouraged to commit to testing at least one adaptive strategy. The therapist provided validation and modeled realistic thinking throughout the session to support cognitive restructuring.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group intervention on generating possible solutions to identified problems. Clients were encouraged to brainstorm adaptive responses without immediate judgment or self-criticism. The therapist highlighted the importance of divergent thinking and cognitive flexibility, emphasizing that a wider range of options increases the likelihood of effective problem resolution.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in exploring alternative strategies for managing current stressors. The discussion focused on the role of creativity and cognitive reframing in solution generation. Clients practiced identifying both short-term and long-term approaches, while the therapist reinforced the value of evaluating feasibility before implementation.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a structured session in which clients engaged in collaborative problem-solving exercises. Participants examined the benefits and limitations of potential solutions, learning to weigh risks and rewards. The therapist modeled decision-making processes grounded in rational-emotive principles, supporting clients in enhancing their coping repertoire.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced techniques for expanding possible solutions beyond habitual or automatic responses. Clients reflected on past tendencies toward rigid thinking and practiced generating alternatives using guided prompts. The therapist validated individual contributions and emphasized the role of adaptability in promoting resilience and self-efficacy.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group activity focused on solution-focused thinking. Clients were encouraged to shift attention from barriers to possibilities, formulating realistic action steps aligned with personal values and goals. The therapist underscored the therapeutic value of practicing proactive strategies, linking the exercise to improved emotional regulation and functional outcomes.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exercise centered on the development of possible solutions once a problem was clearly defined. Clients were guided to generate multiple alternatives through brainstorming, with an emphasis on suspending premature judgment. The therapist reinforced the cognitive-behavioral principle that expanding options enhances autonomy and reduces reliance on maladaptive coping.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session designed to increase clients'' ability to formulate potential solutions for everyday stressors. Participants practiced weighing the pros and cons of each alternative, focusing on both short-term relief and long-term outcomes. The therapist highlighted the relevance of evaluating feasibility and aligning responses with personal values to strengthen decision-making capacity.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through structured problem-solving steps that involved exploring various possible solutions without attachment to a single outcome. Clients reflected on barriers to creativity, such as rigid thinking or avoidance. The therapist modeled cognitive flexibility and encouraged adaptive experimentation, linking this process to improved problem management and resilience.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged the group in generating solution pathways by using scenario-based practice. Clients were encouraged to propose both conventional and innovative responses, then assess their potential impact. The therapist emphasized the therapeutic benefit of shifting focus from obstacles to opportunities, cultivating a proactive stance toward stress regulation.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on possible solutions to interpersonal and intrapersonal conflicts. Clients identified realistic strategies, including assertive communication, time management, and use of social supports. The therapist validated these contributions and reinforced the importance of translating abstract ideas into concrete action steps that can be monitored for effectiveness.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive-behavioral group session focused on the generation of possible solutions as part of the structured problem-solving process. Clients were guided to engage in divergent thinking by identifying multiple strategies to address current personal or interpersonal challenges. The therapist emphasized the importance of brainstorming without self-criticism to foster cognitive flexibility, creativity, and empowerment in decision-making.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational session exploring adaptive problem-solving and solution generation. Clients were encouraged to view challenges as opportunities for growth rather than sources of defeat. Through guided discussion, participants identified at least three potential responses to ongoing stressors, evaluating each for feasibility, emotional impact, and alignment with long-term goals.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a structured exercise designed to enhance clients'' ability to identify viable and goal-oriented solutions to real-life problems. Participants discussed how emotional reasoning often limits creativity and practiced cognitive reframing to expand possible options. The therapist reinforced that solution generation promotes a sense of agency and reduces avoidance-based coping.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in a collaborative session where they practiced developing multiple potential strategies for managing difficult situations. The group examined how rigid or dichotomous thinking patterns impede effective problem-solving. The therapist introduced techniques such as brainstorming and pros-and-cons evaluation to encourage flexibility and balanced reasoning.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a problem-solving workshop emphasizing the process of generating, evaluating, and selecting adaptive solutions. Clients were encouraged to consider both immediate and long-term consequences of their decisions. The therapist highlighted the relationship between effective solution generation and emotional regulation, particularly in reducing impulsive or avoidant reactions.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group activity where clients were prompted to identify three potential ways to resolve a current challenge while considering personal values and resources. The therapist modeled reflective questioning to help participants move beyond self-defeating thought patterns and toward practical, solution-oriented thinking.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an interactive exercise aimed at improving cognitive flexibility in the face of stressors. Clients were encouraged to replace negative self-talk with constructive problem-focused strategies. The therapist reinforced the idea that generating diverse solutions increases resilience and enhances self-efficacy in daily functioning.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion centered on identifying alternative strategies to habitual coping responses. Clients analyzed previous attempts at problem resolution and collaboratively proposed new, more adaptive approaches. The therapist emphasized the therapeutic benefit of creativity and open-mindedness in sustaining emotional stability.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a solution-focused exercise emphasizing goal-directed thinking and proactive behavior. Participants generated a list of potential strategies to manage ongoing life stressors. The therapist validated their ideas and underscored how broadening possible solutions can mitigate feelings of helplessness and enhance problem-solving confidence.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session encouraging clients to explore creative and realistic solutions for managing recurring difficulties. The group reflected on how overthinking or emotional avoidance can limit progress. The therapist introduced structured brainstorming as a method to transform perceived barriers into opportunities for personal growth and improved functioning.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on solution generation within problem-solving therapy. Clients were encouraged to evaluate each proposed solution through a lens of practicality, emotional sustainability, and long-term benefit. The therapist highlighted how this process fosters balanced reasoning and enhances adaptive coping mechanisms.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided participants in identifying adaptive alternatives to maladaptive coping behaviors. Clients explored the emotional and behavioral consequences of various potential solutions to current stressors. The therapist reinforced that taking time to generate options improves decision quality and prevents reactionary behavior.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session emphasizing collaborative problem-solving and the psychological value of generating multiple possible responses to adversity. Clients practiced open discussion and peer feedback to refine their proposed solutions. The therapist emphasized how shared insight fosters accountability and builds social support networks.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group reflection exercise where clients examined previous problem-solving attempts and explored new potential responses to similar situations. The therapist encouraged replacing rigid "all-or-nothing" thinking with flexible, goal-oriented alternatives that align with clients'' emotional and behavioral health goals.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a cognitive-behavioral activity promoting solution-focused adaptability as a means to counter stress-induced paralysis. Clients were guided through structured questioning to uncover overlooked resources and practical next steps. The therapist emphasized the psychological benefits of viewing challenges as manageable through systematic exploration of options.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on the relationship between emotional regulation and effective solution generation. Clients identified barriers such as anxiety or perfectionism that interfere with brainstorming. The therapist modeled mindfulness-based strategies to enhance clarity and foster productive problem-solving habits.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in generating problem-solving alternatives through role-play exercises that mirrored real-world challenges. Participants practiced evaluating emotional consequences and potential outcomes of each solution. The therapist emphasized the link between flexibility in thinking and reduction in anxiety symptoms.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group session on creative problem-solving through cognitive reframing. Clients were encouraged to shift focus from limitations to possibilities and to practice seeing challenges from multiple perspectives. The therapist reinforced that generating diverse solutions enhances resilience and self-confidence.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an interactive group focused on the skill of divergent thinking as a foundation for problem-solving. Clients were encouraged to avoid premature judgment of ideas and instead engage in brainstorming to uncover innovative solutions. The therapist discussed how this skill strengthens adaptability and coping efficiency.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-focused session encouraging clients to develop structured action plans based on the most feasible solutions identified. Clients were prompted to connect each solution with measurable steps and coping supports. The therapist reinforced that consistent problem-solving practice enhances emotional regulation and long-term self-efficacy.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured problem-solving session centered on developing possible solutions to current psychosocial stressors. Clients were encouraged to identify at least three adaptive alternatives to their ongoing challenges while examining potential barriers to implementation. The therapist emphasized the use of cognitive flexibility and solution-focused thinking as tools to enhance emotional regulation and promote a sense of control.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a cognitive-behavioral framework emphasizing solution generation as a key component of adaptive coping. Participants explored multiple approaches to common interpersonal and emotional difficulties, focusing on feasibility and alignment with their long-term goals. The therapist modeled balanced reasoning and validated efforts toward self-efficacy and proactive decision-making.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational group promoting divergent thinking in problem-solving. Clients practiced brainstorming without self-censorship, allowing for creativity and openness to alternative strategies. The therapist discussed how generating various solutions reduces rigidity in thinking and strengthens emotional resilience during stressful circumstances.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a problem-solving intervention focused on identifying constructive and goal-directed responses to daily stressors. Clients were guided to weigh the potential benefits and consequences of each idea generated. The therapist highlighted how flexible problem-solving decreases avoidance behaviors and supports long-term psychological stability.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group activity designed to enhance clients'' adaptive decision-making through collaborative exploration of solutions. Participants shared personal challenges and collectively brainstormed practical strategies for improvement. The therapist emphasized the therapeutic role of social learning and interpersonal feedback in refining effective coping methods.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in developing solution-oriented frameworks to address recurring emotional or behavioral difficulties. The group discussed the impact of automatic negative thoughts on the ability to find solutions. The therapist introduced cognitive reframing techniques to help participants view obstacles from a perspective of growth and adaptability.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a problem-solving exercise emphasizing the importance of creativity and open-mindedness in developing possible solutions. Clients were prompted to challenge limiting beliefs and generate ideas beyond habitual coping strategies. The therapist reinforced that expanding problem-solving options promotes psychological empowerment and confidence.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group discussion encouraging clients to explore alternative responses to unresolved personal problems. Participants practiced evaluating each option for practicality, emotional cost, and potential outcome. The therapist underscored the role of thoughtful analysis in building self-regulation and informed decision-making.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session centered on transforming maladaptive problem-solving patterns into structured, realistic strategies. Clients engaged in identifying possible solutions through guided questioning and peer dialogue. The therapist emphasized that viewing problems as solvable enhances motivation and emotional balance.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an experiential activity aimed at promoting goal-focused planning through the generation of multiple solutions. Clients explored how anxiety and self-doubt can limit creativity and learned to use mindfulness techniques to access clarity in problem resolution. The therapist highlighted the connection between self-awareness and effective problem-solving.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a structured reflection process to identify potential solutions for personal and relational conflicts. Participants were encouraged to view challenges through a lens of curiosity rather than fear. The therapist reinforced that adopting a flexible, exploratory mindset strengthens emotional regulation and adaptive coping.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a cognitive-behavioral group focused on cultivating proactive approaches to problem-solving. Clients practiced separating emotion-driven responses from logical evaluation to expand possible solutions. The therapist emphasized that balanced decision-making improves overall psychological well-being and autonomy.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a role-playing exercise in which clients practiced applying solution-focused strategies to real-life situations. Participants generated multiple responses and analyzed their potential outcomes. The therapist highlighted how this experiential learning supports behavioral activation and improved conflict resolution skills.', 53),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a solution-mapping exercise designed to visually organize potential actions for managing stressors. Clients discussed how visualization helps reduce cognitive overload and clarify priorities. The therapist emphasized that structured planning fosters self-discipline and promotes consistent follow-through.', 54),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group dialogue focusing on collaborative problem-solving and mutual feedback. Clients were encouraged to exchange constructive insights and offer alternative perspectives to one another''s challenges. The therapist modeled empathetic communication and reinforced collective resilience as a therapeutic resource.', 55),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a discussion-based session exploring how perfectionistic thinking can inhibit the generation of possible solutions. Clients practiced identifying flexible, realistic alternatives instead of rigid "all-or-nothing" responses. The therapist reinforced self-compassion as a foundation for productive problem-solving and emotional recovery.', 56),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution-oriented group emphasizing incremental change rather than immediate resolution. Clients identified small, actionable steps toward addressing identified problems, increasing their sense of mastery. The therapist underscored that gradual problem-solving helps sustain motivation and build confidence.', 57),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in analyzing barriers to effective problem-solving, such as avoidance, fear of failure, or cognitive distortion. Participants worked collaboratively to reframe these barriers into opportunities for learning. The therapist emphasized that facing discomfort with openness enhances adaptive functioning and emotional growth.', 58),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a cognitive restructuring activity to promote realistic and sustainable problem-solving. Clients practiced distinguishing between reactive and reflective decision-making. The therapist modeled curiosity-driven questioning to foster metacognitive awareness and better long-term planning.', 59),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational session on the value of solution generation as emotional regulation. Clients explored how identifying practical alternatives reduces anxiety and fosters a sense of empowerment. The therapist reinforced that viewing obstacles as challenges to be solved rather than threats promotes resilience and psychological flexibility.', 60),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured problem-solving session focused on generating possible solutions to individual challenges. Clients were encouraged to use brainstorming techniques to expand their range of adaptive responses without prematurely evaluating their ideas. The therapist emphasized cognitive flexibility and the importance of considering both short-term and long-term consequences to strengthen problem-solving efficacy and emotional regulation.', 61),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through the process of exploring multiple possible solutions to real-life problems, highlighting how open-mindedness and creative thinking enhance adaptability. Participants practiced evaluating their proposed solutions for feasibility and emotional sustainability. The therapist reinforced that developing varied options increases a sense of control and decreases avoidance behaviors.', 62),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a solution-oriented group activity designed to improve critical thinking and problem-solving confidence. Clients collaboratively generated and analyzed alternative approaches to current stressors. The therapist underscored the importance of rational evaluation and self-reflective awareness in selecting the most constructive course of action.', 63),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive-behavioral discussion on identifying adaptive solutions as part of an effective coping plan. Clients reflected on past problem-solving experiences and learned to distinguish between impulsive reactions and deliberate, goal-directed actions. The therapist emphasized that structured solution generation reduces distress and promotes emotional resilience.', 64),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided participants in developing solution-based strategies for managing emotional and interpersonal difficulties. Clients were encouraged to approach each problem from different perspectives and to evaluate their ideas based on practicality and alignment with their values. The therapist modeled balanced reasoning and encouraged clients to use problem-solving as a self-empowerment tool.', 65),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational session centered on divergent thinking and the generation of multiple solutions to a single problem. Clients discussed how rigid cognitive patterns can restrict adaptive functioning. The therapist highlighted that expanding options increases psychological flexibility and strengthens overall coping capacity.', 66),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exercise where clients practiced solution exploration by identifying three potential actions to address a recurring challenge. Through guided reflection, participants examined the benefits, risks, and emotional outcomes of each choice. The therapist reinforced the therapeutic value of structured problem-solving in reducing cognitive rumination.', 67),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in an interactive discussion about alternative responses to stress-inducing situations. Participants were encouraged to differentiate between emotion-driven and rationally derived solutions. The therapist emphasized that effective problem-solving promotes a sense of autonomy and mitigates learned helplessness.', 68),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group dialogue promoting solution-focused thinking as a strategy for behavioral activation. Clients worked collaboratively to identify feasible options for managing their daily stressors. The therapist highlighted that generating constructive solutions fosters self-efficacy and enhances emotional regulation.', 69),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a step-by-step solution development model that emphasized creativity, practicality, and reflection. Participants explored how avoidance and fear of failure hinder their ability to problem-solve effectively. The therapist encouraged the use of goal-oriented problem-solving to build resilience and improve coping mechanisms.', 70),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session aimed at helping clients identify adaptive pathways to address interpersonal and emotional challenges. Clients brainstormed multiple responses and reflected on their potential impact on relationships and self-esteem. The therapist reinforced that flexible problem-solving supports healthy communication and self-regulation.', 71),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution generation workshop where clients explored how self-awareness and realistic appraisal contribute to effective decision-making. Participants practiced identifying potential actions and analyzing the pros and cons of each. The therapist emphasized that structured reflection builds confidence and strengthens executive functioning.', 72),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exercise designed to strengthen analytical and reflective skills in problem-solving. Clients generated possible alternatives for managing current difficulties while identifying internal and external supports. The therapist highlighted that consistent solution-focused practice enhances psychological stability and adaptive behavior.', 73),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-mapping activity that helped clients visually organize their thoughts about potential responses to a stressor. Participants discussed how visualization aids in prioritizing goals and reducing emotional overwhelm. The therapist emphasized that clear organization enhances decision-making clarity and motivation.', 74),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group problem-solving intervention focused on the identification and evaluation of realistic solutions. Clients worked collaboratively to consider the feasibility, timing, and emotional consequences of their choices. The therapist reinforced that balanced reasoning promotes cognitive restructuring and a greater sense of mastery.', 75),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in a cognitive flexibility exercise designed to challenge rigid or pessimistic thinking. Participants brainstormed adaptive solutions to hypothetical and personal scenarios, exploring how reframing enhances problem-solving. The therapist underscored that cognitive adaptability is essential for sustained recovery and emotional balance.', 76),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a problem-solving session emphasizing creativity, resource utilization, and behavioral experimentation. Clients practiced generating solutions that integrated self-care and social support. The therapist validated participants'' insights and highlighted how intentional problem-solving reduces impulsivity and promotes stability.', 77),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a collaborative activity where clients used group feedback to refine and expand possible solutions to shared challenges. The exercise focused on recognizing the diversity of thought and valuing multiple perspectives. The therapist emphasized that collective problem-solving strengthens social learning and emotional insight.', 78),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group focused on building tolerance for uncertainty while exploring solutions. Clients discussed how fear of failure can prevent creative problem-solving and learned to reframe mistakes as opportunities for growth. The therapist reinforced that resilient thinking supports both emotional and behavioral progress.', 79),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a solution-focused cognitive exercise that encouraged clients to identify obstacles to progress and brainstorm realistic alternatives. Participants were guided to evaluate each solution using a pros-and-cons matrix. The therapist highlighted that structured decision-making enhances self-efficacy and long-term goal attainment.', 80);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Possible Solution" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'problem solving'
AND LOWER(sa.subactivity_name) = 'possible solution'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

