-- =============================================
-- IOP: Problem Solving - JUEVES - Decision Making
-- =============================================
-- Este script inserta los 80 párrafos para "Decision Making"
-- de la actividad "Problem Solving" para IOP del día JUEVES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Problem Solving"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'problem solving'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Problem Solving" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Problem Solving" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Decision Making"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'decision making'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Decision Making', 'Developing decision-making skills as part of effective problem-solving', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Decision Making" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Decision Making" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 80 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured cognitive-behavioral session focused on the role of decision-making in effective problem resolution. Clients were introduced to a stepwise framework that included identifying the issue, listing possible options, anticipating outcomes, and selecting the most adaptive response. The therapist encouraged clients to reflect on recent impulsive decisions and guided them through reconstructing those scenarios using the model.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session aimed at enhancing executive functioning through improved decision-making skills. Emphasis was placed on the intersection between emotional dysregulation and poor decision outcomes. Clients participated in a guided activity that highlighted the importance of pausing, evaluating alternatives, and utilizing logical reasoning before acting on emotionally charged situations.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session emphasizing the cognitive distortions that interfere with rational decision-making, such as catastrophizing and all-or-nothing thinking. Clients were encouraged to identify how these distortions have impacted past choices and to apply reframing techniques to more accurately assess risk and consequence. The therapist reinforced the value of delayed responses in emotionally complex scenarios.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced an evidence-based decision-making model grounded in solution-focused therapy. Clients examined personal dilemmas and were supported in generating multiple potential actions, assessing pros and cons, and forecasting emotional and functional outcomes. The therapist modeled reflective questioning to facilitate insight and intentionality in the decision-making process.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group process wherein clients explored the influence of interpersonal dynamics on decision-making. The session focused on identifying patterns of acquiescence, avoidance, or excessive control within relationships. Through discussion and role-play, clients practiced asserting preferences and making decisions that align with their personal values and treatment goals.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session exploring the connection between indecision and underlying anxiety symptoms. Clients were encouraged to identify recent situations where avoidance of decision-making increased distress. The therapist introduced grounding strategies and a rational choice model to help clients feel more empowered when facing everyday decisions.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a cognitive-behavioral group focused on enhancing problem-solving abilities through structured decision-making. Clients engaged in an exercise where they identified a recent conflict, analyzed it objectively, and generated at least two viable solutions. The therapist emphasized the importance of self-reflection, outcome forecasting, and behavioral activation in the decision-making process.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led an interactive discussion on barriers to effective decision-making, such as fear of failure, perfectionism, and impulsivity. Clients were guided to recognize how these factors impact their problem-solving skills and were encouraged to use a pros-and-cons matrix to support more adaptive choices. The session promoted emotional insight and cognitive flexibility.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist introduced the concept of values-based decision-making as a tool for increasing congruence between actions and long-term goals. Clients were invited to clarify core personal values and assess how their recent decisions align with these principles. The therapist provided individualized feedback to reinforce autonomy and self-efficacy in problem-solving.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution-focused group session emphasizing the use of past successes to inform future decisions. Clients reflected on previous effective problem-solving experiences and extracted strategies that could be generalized to current stressors. The therapist reinforced the idea that structured decision-making is a skill that improves with practice and self-awareness.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on decision-making as the final step in structured problem-solving. Clients were guided to analyze previously generated solutions and select the most adaptive choice based on feasibility, long-term benefit, and alignment with personal goals. The therapist highlighted how intentional decision-making strengthens self-efficacy and decreases impulsive behavior.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an intervention emphasizing the cognitive processes underlying effective decision-making. Clients practiced comparing alternatives through cost-benefit analysis and discussed how emotional regulation plays a role in evaluating outcomes. The therapist reinforced the use of rational evaluation strategies to reduce avoidance and enhance accountability.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in applying executive functioning skills to decision-making tasks. The session emphasized prioritization, risk assessment, and the impact of values on final choices. The therapist modeled the use of reflective questioning, encouraging clients to slow down their cognitive process to prevent reactive or maladaptive responses.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged the group in scenario-based decision-making exercises to strengthen problem-solving abilities. Clients practiced selecting a course of action from multiple possible solutions while considering both short-term relief and long-term consequences. The therapist validated their reasoning and emphasized the importance of adaptive decision-making for resilience and behavioral activation.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion focused on barriers to effective decision-making, such as cognitive distortions, fear of failure, or overgeneralization. Clients explored strategies for overcoming these obstacles by applying structured frameworks. The therapist underscored the therapeutic value of cultivating decisional confidence, linking this process to improved problem-solving competence and affect regulation.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured group session on decision-making, guiding clients to recognize the cognitive steps involved in moving from identifying a problem to selecting an adaptive solution. The discussion emphasized the importance of weighing potential risks and benefits, promoting the use of reflective reasoning to support healthier behavioral outcomes.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in exercises designed to strengthen decisional capacity by practicing prioritization of options. Participants examined how impulsivity or emotional bias can interfere with judgment. The therapist reinforced the application of rational analysis and problem-solving frameworks to enhance executive functioning and self-regulation.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session in which clients practiced evaluating multiple possible solutions through comparative analysis. Emphasis was placed on distinguishing between short-term gratification and long-term effectiveness. The therapist modeled the use of critical thinking strategies and validated client progress toward more deliberate decision-making.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in scenario-based activities where they were asked to make decisions under simulated stress. Clients explored how anxiety or avoidance can hinder the decision-making process. The therapist highlighted strategies such as cognitive reframing and mindfulness to improve tolerance for uncertainty and strengthen adaptive choices.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on the psychological barriers that affect decision-making, including fear of error, overgeneralization, and indecisiveness. Clients were encouraged to verbalize strategies for overcoming these barriers. The therapist emphasized the therapeutic value of decisional confidence and its role in reinforcing problem-solving competence and emotional stability.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured session focused on decision-making as a critical step in effective problem-solving. Clients explored how emotional reactivity and cognitive distortions can influence the quality of their decisions. Through guided discussion and applied exercises, participants practiced using rational evaluation and delayed response techniques to enhance self-control and improve judgment in stressful situations.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group emphasizing the importance of reflective decision-making. Clients learned to identify how impulsivity, avoidance, and fear of failure often interfere with adaptive choices. The therapist guided participants through a structured process of comparing alternatives, reinforcing cognitive flexibility and executive functioning in the face of emotional distress.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a cognitive-behavioral intervention aimed at strengthening decision-making capacity. Clients engaged in role-play scenarios that required evaluating options, predicting potential consequences, and aligning choices with long-term goals. The therapist underscored how intentional decision-making promotes self-efficacy and reduces maladaptive coping responses.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group problem-solving exercise centered on developing structured decision-making skills. Clients discussed how indecision often stems from anxiety and perfectionism, then practiced using a stepwise model to assess feasibility and risk. The therapist reinforced that balanced reasoning and emotional regulation are essential for sustainable behavioral change.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in identifying internal and external factors that affect their decision-making process. Participants analyzed how personal values, emotional states, and cognitive biases shape the choices they make. The therapist modeled reflective questioning and encouraged the use of evidence-based strategies to promote rational and adaptive decisions.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a solution-focused group on enhancing decision-making through realistic appraisal and self-awareness. Clients explored the link between impulsive actions and negative outcomes, learning to integrate mindfulness techniques to slow their cognitive processing. The therapist validated participants'' insights and emphasized intentional choice-making as a tool for emotional stability.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged the group in a decision-analysis exercise where clients identified a current challenge and generated multiple potential solutions. Each participant evaluated their options using a pros-and-cons framework to assess short- and long-term impact. The therapist highlighted that structured decision-making fosters behavioral activation and decreases learned helplessness.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session focused on the relationship between emotional dysregulation and poor decision outcomes. Clients practiced strategies to pause and reflect before acting, identifying triggers that lead to impulsivity. The therapist reinforced the concept of cognitive restructuring to support more deliberate and values-consistent choices.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an experiential group activity emphasizing the importance of values-based decision-making. Clients examined how aligning their choices with personal goals and principles improves emotional well-being and self-consistency. The therapist encouraged self-reflection and collaborative feedback to strengthen autonomous decision-making.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in recognizing maladaptive patterns in their decision-making processes, such as avoidance, rumination, or overgeneralization. Through discussion, participants identified realistic strategies to increase confidence and accountability. The therapist emphasized that adaptive decision-making enhances both problem-solving efficacy and emotional resilience.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention integrating mindfulness with structured decision-making frameworks. Clients practiced grounding techniques before engaging in analytical tasks to ensure emotional regulation during the decision process. The therapist reinforced the link between present-focused awareness and improved cognitive clarity.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a decision-making workshop designed to build executive functioning and self-reflection. Clients were encouraged to recall recent decision points and analyze the reasoning behind their choices. The therapist emphasized that metacognitive awareness—thinking about one''s thought process—supports more rational and confident decision-making.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on the psychological barriers that hinder effective decision-making, including fear of rejection, overthinking, and low self-trust. Clients practiced challenging irrational beliefs through cognitive reframing. The therapist underscored that confronting these barriers promotes assertiveness and self-directed growth.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through case-based decision-making scenarios that simulated real-world stressors. Participants worked collaboratively to evaluate alternatives, anticipate consequences, and justify their final choice. The therapist emphasized that rational problem-solving strengthens emotional control and encourages consistent behavioral follow-through.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a decision-mapping activity where clients visually organized possible outcomes to enhance clarity and reduce cognitive overload. The therapist guided participants in assessing which actions aligned with long-term well-being. The session reinforced the value of structured reasoning as a tool for emotional and behavioral regulation.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in a cognitive-behavioral exercise focusing on deliberate choice-making under pressure. Participants discussed how emotional bias can distort reasoning and were guided in developing alternative thought pathways. The therapist reinforced that consistent practice of evaluative thinking fosters long-term decision confidence.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group session exploring the connection between self-esteem and decision-making. Clients examined how negative self-concepts contribute to indecision or impulsive behavior. The therapist encouraged the use of self-compassion and assertive communication to strengthen autonomy and promote more adaptive judgments.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a reflective decision-making session focused on identifying lessons from past experiences. Clients shared prior outcomes and analyzed what cognitive or emotional factors influenced their results. The therapist validated participants'' reflections and emphasized learning-based adaptation as a key aspect of behavioral growth.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided the group in developing decision-making strategies for managing interpersonal conflicts. Clients practiced evaluating options that balance assertiveness with empathy, aiming for mutually beneficial outcomes. The therapist highlighted how emotional intelligence and social awareness are integral components of effective decision-making.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a solution-oriented discussion designed to strengthen decisional confidence and autonomy. Clients identified one decision they had recently avoided and, with group support, developed an actionable plan. The therapist emphasized the importance of taking responsibility for choices as part of personal empowerment and psychological resilience.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured group session focused on decision-making as a vital component of effective problem-solving. Clients explored how impulsivity, fear of failure, and cognitive distortions often interfere with making sound choices. Through guided exercises, participants practiced analytical reasoning and emotional regulation to promote more intentional and adaptive decision-making in daily life.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention designed to strengthen clients'' ability to make rational, goal-oriented decisions. The group discussed the importance of weighing consequences and aligning actions with personal values. The therapist emphasized executive functioning skills and self-awareness as core mechanisms for achieving improved behavioral outcomes.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a cognitive-behavioral group centered on identifying internal and external factors that influence the decision-making process. Clients examined how automatic thoughts, stress, and social pressures can lead to maladaptive patterns. The therapist modeled reflective questioning and encouraged participants to apply problem-solving frameworks to enhance judgment and self-efficacy.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an experiential session in which clients engaged in decision-making exercises using real-life stressors. Participants practiced identifying potential outcomes and evaluating risks versus benefits. The therapist provided feedback to help clients develop insight, accountability, and cognitive flexibility in their problem-solving approach.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a solution-focused session that emphasized intentional decision-making as a key to emotional and behavioral stability. Clients were encouraged to reflect on recent choices and analyze how emotional states impacted their outcomes. The therapist guided them in applying mindfulness and rational evaluation strategies to foster improved self-regulation.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through a decision-analysis exercise exploring the relationship between stress, cognition, and impulsivity. Participants worked collaboratively to identify how overthinking or avoidance hinders progress. The therapist reinforced goal-oriented thinking and evidence-based reasoning as strategies for making adaptive, confident choices.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion emphasizing how values-based decision-making contributes to emotional congruence and personal growth. Clients identified their core values and evaluated whether their recent decisions aligned with those principles. The therapist encouraged self-reflection and assertive communication as tools to enhance integrity and psychological balance.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a rational decision-making workshop where clients learned to differentiate between reactive and deliberate choices. Participants practiced evaluating options through cost-benefit analysis and forecasting potential emotional impacts. The therapist highlighted the importance of delayed gratification and thoughtful appraisal in achieving long-term well-being.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exercise designed to enhance decisional confidence by examining past experiences. Clients identified patterns of avoidance, impulsivity, or regret associated with poor decision outcomes. The therapist provided psychoeducation on cognitive restructuring and modeled ways to transform uncertainty into proactive engagement.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through scenario-based decision-making tasks where they practiced responding to interpersonal or occupational dilemmas. Emphasis was placed on using logical reasoning and emotional awareness simultaneously. The therapist reinforced that effective decision-making involves balancing cognitive analysis with empathic understanding.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a cognitive restructuring session where clients examined how distorted beliefs affect their ability to make effective decisions. Participants learned to identify "all-or-nothing" and "catastrophic" thinking patterns. The therapist introduced rational self-talk and problem-solving heuristics to promote balanced, realistic evaluations of possible outcomes.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group on decisional problem-solving, helping clients explore how uncertainty and perfectionism impede progress. Through guided discussion, participants identified internalized fears related to making "wrong" choices. The therapist emphasized that experiential learning and risk tolerance are essential components of emotional resilience.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an interactive group exercise integrating executive functioning and behavioral activation to strengthen decision-making. Clients were tasked with choosing between competing priorities while considering long-term impact. The therapist underscored how consistent practice of structured reasoning can improve clarity, confidence, and emotional regulation.', 53),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in exploring the emotional underpinnings of their decision-making habits. Participants reflected on how guilt, shame, or anxiety often lead to avoidance or passivity. The therapist introduced grounding techniques to help clients remain centered and make thoughtful choices despite emotional discomfort.', 54),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a goal-directed decision-making session where clients practiced identifying desired outcomes before selecting actions. Participants worked on distinguishing between immediate emotional relief and sustainable progress. The therapist highlighted the importance of strategic planning and intentional behavior modification for long-term success.', 55),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a reflective processing group in which clients analyzed how interpersonal influences affect their choices. The session focused on recognizing when decisions are made to please others versus to meet personal goals. The therapist reinforced autonomy and self-advocacy as pillars of healthy psychological functioning.', 56),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a behavioral decision-making exercise emphasizing the role of self-monitoring in building awareness of thought-behavior patterns. Clients tracked recent choices and evaluated the cognitive and emotional triggers that guided them. The therapist supported participants in developing self-correction strategies to increase decisional accuracy.', 57),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group dialogue on ethical and moral decision-making, exploring how integrity and empathy contribute to positive outcomes. Clients examined dilemmas that required balancing personal needs with broader responsibilities. The therapist encouraged perspective-taking and empathic reasoning to strengthen moral awareness in problem-solving.', 58),
    (v_activity_id, v_subactivity_id, 'IOP Therapist engaged clients in role-play scenarios simulating high-stress situations that required quick decision-making. Participants learned to recognize physiological stress responses and apply coping mechanisms before acting. The therapist emphasized the connection between emotional regulation and effective executive decision-making.', 59),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a solution-oriented group integrating cognitive-behavioral and mindfulness strategies to improve decision-making. Clients practiced pausing before reacting, acknowledging emotions, and evaluating available options rationally. The therapist validated their progress and reinforced that self-regulated decisions promote both autonomy and psychological well-being.', 60),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a structured problem-solving session focused on decision-making as a key executive function skill. Clients discussed how stress and emotional overload can interfere with rational evaluation and judgment. Through guided exercises, participants practiced identifying possible solutions, weighing potential outcomes, and selecting the most adaptive option. The therapist emphasized cognitive flexibility and self-reflective awareness as tools to enhance effective decision-making.', 61),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group aimed at strengthening clients'' decisional competence through structured reasoning and self-regulation. Clients analyzed personal examples of impulsive or avoidant choices and restructured them using evidence-based frameworks. The therapist highlighted how integrating emotional insight with logical analysis fosters adaptive problem-solving and promotes long-term behavioral stability.', 62),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group session centered on decision-making within emotionally charged contexts. Clients explored how automatic thoughts and maladaptive schemas often drive reactive behaviors. The therapist modeled reflective questioning and cognitive reframing to help participants develop more deliberate and goal-oriented decision-making processes.', 63),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion emphasizing values-based decision-making as a foundation for self-efficacy and autonomy. Clients identified core personal values and compared them with their recent behavioral choices. The therapist guided the group in aligning decisions with these values to strengthen motivation, integrity, and behavioral consistency.', 64),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through scenario-based exercises designed to simulate real-life decision-making challenges. Participants practiced identifying feasible solutions, analyzing risks, and predicting short- and long-term consequences. The therapist reinforced the importance of executive control and emotional regulation to promote mindful and intentional actions.', 65),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a cognitive-behavioral session that examined how distorted thinking patterns—such as catastrophizing or overgeneralization—can hinder decision-making. Clients practiced replacing irrational beliefs with balanced perspectives. The therapist emphasized the role of self-monitoring and delayed response techniques in fostering sound and adaptive judgments.', 66),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a solution-focused group encouraging clients to develop problem-solving confidence through structured decision-making. Participants discussed barriers such as fear of failure and indecision. The therapist modeled how to implement cost-benefit analysis and realistic appraisal to reduce anxiety and enhance cognitive control during complex decisions.', 67),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group intervention focused on enhancing critical thinking and emotional awareness during decision-making. Clients explored the cognitive steps necessary for analyzing alternatives and forecasting potential outcomes. The therapist reinforced how intentional reasoning and goal-oriented behavior lead to improved functional outcomes and emotional stability.', 68),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a reflective session where clients examined the psychological barriers that influence decision-making, including perfectionism, impulsivity, and avoidance. Through open dialogue, participants identified coping mechanisms that promote flexibility and resilience. The therapist encouraged the development of adaptive reasoning strategies to enhance self-confidence in decision-making.', 69),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted an interactive problem-solving activity designed to strengthen executive functioning in the context of decision-making. Clients practiced analyzing multiple solutions to a hypothetical problem while monitoring emotional reactions. The therapist emphasized the integration of rational analysis and affect regulation to support balanced decision outcomes.', 70),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group focused on rational decision-making under emotional stress. Clients were encouraged to identify triggers that lead to impulsivity and apply cognitive tools such as grounding and self-dialogue before acting. The therapist reinforced mindfulness-based techniques to promote calm and deliberate thinking patterns.', 71),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session centered on the link between self-esteem and decisional confidence. Clients explored how low self-worth and dependency on external validation can lead to indecision or maladaptive compromises. The therapist emphasized building autonomy through assertive, values-aligned decision-making and self-empowerment practices.', 72),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a problem-solving workshop aimed at strengthening analytical and reflective decision-making skills. Clients engaged in exercises that required evaluating alternatives through structured frameworks. The therapist modeled how applying objective reasoning enhances accountability, emotional regulation, and behavioral follow-through.', 73),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a behavioral activation session where clients practiced implementing small, goal-directed decisions to build momentum toward larger life changes. The therapist highlighted how consistent, intentional decision-making reinforces motivation, reduces avoidance, and promotes a sense of personal agency and control.', 74),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in identifying patterns of indecision linked to anxiety and cognitive overload. Participants worked collaboratively to design practical strategies for managing uncertainty, such as prioritizing, simplifying choices, and reframing "mistakes" as learning opportunities. The therapist reinforced the therapeutic role of self-trust and resilience in adaptive decision-making.', 75),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of the emotional and cognitive stages involved in making difficult decisions. Clients reflected on personal dilemmas and were guided in separating factual reasoning from emotional reactivity. The therapist emphasized the development of metacognitive awareness to enhance problem-solving insight and consistency.', 76),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an applied decision-making activity integrating cognitive-behavioral and mindfulness principles. Clients practiced pausing before responding, identifying emotional states, and selecting options aligned with long-term goals. The therapist underscored the connection between present-moment awareness and rational decision execution.', 77),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session designed to improve interpersonal decision-making within relationships. Clients explored how empathy, boundaries, and assertiveness affect choices made during conflict or negotiation. The therapist encouraged reflection on how balanced communication contributes to healthier outcomes and relational stability.', 78),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients in recognizing decision fatigue and its impact on executive functioning. Participants discussed strategies such as routine planning, delegation, and prioritization to reduce cognitive strain. The therapist emphasized that structured problem-solving supports mental clarity and emotional endurance.', 79),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a goal-oriented discussion where clients identified a personal decision requiring immediate attention. Using a collaborative framework, they practiced evaluating potential outcomes, anticipating obstacles, and committing to a realistic action plan. The therapist validated efforts and reinforced the therapeutic value of decisional accountability and behavioral consistency.', 80);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Decision Making" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'problem solving'
AND LOWER(sa.subactivity_name) = 'decision making'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

