-- =============================================
-- IOP: Self-Esteem - LUNES (COMPLETO)
-- =============================================
-- Este script inserta la actividad "Self-Esteem" para IOP del día LUNES
-- Incluye: Actividad + 5 subactividades con TODOS sus párrafos
-- NOTA: NO elimina actividades existentes, solo añade Self-Esteem
-- =============================================

-- Insertar actividad "Self-Esteem" para IOP
DO $$
DECLARE
    v_activity_id UUID;
    v_self_esteem_id UUID;
    v_triggers_id UUID;
    v_building_confidence_id UUID;
    v_practice_selfcare_id UUID;
    v_daily_accomplishments_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Buscar si ya existe la actividad "Self-Esteem"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'self-esteem'
    LIMIT 1;

    -- Si no existe, crearla
    IF v_activity_id IS NULL THEN
        INSERT INTO activities (activity_name, description, is_active)
        VALUES ('Self-Esteem', 'Self-Esteem activities for IOP groups - Monday', TRUE)
        RETURNING activity_id INTO v_activity_id;
        
        RAISE NOTICE '✅ Actividad "Self-Esteem" creada con ID: %', v_activity_id;
    ELSE
        RAISE NOTICE '✅ Actividad "Self-Esteem" ya existe con ID: %', v_activity_id;
    END IF;

    -- =============================================
    -- SUBACTIVIDAD 1: SELF-ESTEEM (50 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_self_esteem_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'self-esteem'
    LIMIT 1;

    IF v_self_esteem_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Self-Esteem', 'Understanding and developing self-esteem', TRUE)
        RETURNING subactivity_id INTO v_self_esteem_id;
        RAISE NOTICE '✅ Subactividad "Self-Esteem" creada';
    END IF;

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a psychoeducational session focused on understanding the cognitive and emotional foundations of self-esteem. Clients explored how self-talk, early experiences, and internalized beliefs influence self-worth. The therapist introduced cognitive restructuring to replace negative self-evaluations with balanced affirmations.', 1, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a group discussion examining the link between self-esteem and personal boundaries. Clients reflected on how low self-worth often leads to people-pleasing or difficulty asserting needs. The therapist emphasized boundary-setting as a protective factor for emotional stability and self-respect.', 2, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a reflective session exploring how early family dynamics shaped each client''s self-image. Participants identified messages of approval, criticism, or neglect that contributed to current self-perceptions. The therapist guided the group in developing self-compassion and self-validation techniques.', 3, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a cognitive-behavioral group on challenging perfectionistic tendencies that undermine self-esteem. Clients examined unrealistic internal standards and how fear of failure reinforces self-criticism. The therapist provided interventions promoting acceptance of imperfection and growth-oriented thinking.', 4, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist guided a group session centered on self-affirmation and positive identity formation. Clients practiced articulating personal strengths and achievements without minimizing them. The therapist reinforced the importance of internal validation rather than reliance on external approval.', 5, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a mindfulness-based group on cultivating self-acceptance through present-moment awareness. Clients practiced observing self-judgmental thoughts without attachment. The therapist emphasized mindfulness as a method to foster nonjudgmental self-recognition and emotional balance.', 6, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a session exploring the relationship between self-esteem and resilience. Clients discussed how past setbacks shaped their confidence and motivation. The therapist guided reflection on reframing failure as a source of learning and personal empowerment.', 7, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a discussion about social comparison and its impact on self-esteem. Clients processed the influence of media, peer pressure, and societal standards. The therapist encouraged gratitude and self-focus exercises to redirect attention toward individual growth and authenticity.', 8, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a process-oriented session addressing self-esteem fluctuations in response to external feedback. Clients explored how validation or criticism from others affects self-worth. The therapist modeled balanced self-assessment and introduced strategies for maintaining internal consistency.', 9, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a strengths-based session designed to reinforce positive self-identity. Clients identified personal qualities that contribute to their resilience, creativity, or empathy. The therapist promoted self-recognition as a form of empowerment and reinforced ongoing practice of affirming behaviors.', 10, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group session addressing the internalized negative beliefs that erode self-esteem. Clients explored the origins of self-deprecating thoughts and their connection to past experiences of rejection or criticism. The therapist guided cognitive restructuring exercises to foster balanced self-perception.', 11, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a psychoeducational group highlighting the role of self-compassion in rebuilding self-esteem. Clients learned to distinguish between self-criticism and accountability. The therapist introduced compassionate self-talk techniques to reduce shame and enhance emotional resilience.', 12, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a session focusing on body image and its relationship to self-esteem. Clients examined the influence of societal standards and internalized ideals on self-worth. The therapist promoted acceptance-based interventions to encourage respect and appreciation for personal individuality.', 13, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a discussion on the relationship between achievement and self-esteem. Clients explored how tying self-worth solely to productivity leads to instability and burnout. The therapist encouraged intrinsic motivation and the practice of valuing effort over outcome.', 14, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist guided a reflective group centered on self-forgiveness as a key component of healthy self-esteem. Clients processed feelings of guilt and regret that undermine self-worth. The therapist provided emotional reframing and mindfulness exercises to promote acceptance and growth.', 15, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a strengths-based session where clients practiced identifying and verbalizing positive personal qualities. The therapist emphasized recognizing internal strengths as an antidote to negative self-schema and reinforced the practice of daily affirmations.', 16, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a cognitive-behavioral session exploring the impact of rumination and self-doubt on confidence. Clients learned how repetitive negative thinking distorts perception of competence. The therapist introduced thought-stopping and redirection strategies to build self-assurance.', 17, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group discussion about assertiveness as an expression of self-esteem. Clients practiced communicating needs and opinions with confidence and respect. The therapist reinforced the connection between self-expression, self-worth, and personal empowerment.', 18, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a process-oriented session addressing the link between emotional validation and self-esteem development. Clients reflected on past experiences of invalidation and how they shaped current self-concept. The therapist encouraged internal validation practices and supportive peer feedback.', 19, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a mindfulness-based exercise encouraging clients to observe their self-talk patterns with curiosity. Clients practiced identifying moments of self-criticism and responding with acceptance. The therapist emphasized that awareness is the first step toward cultivating genuine self-esteem and compassion.', 20, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group focused on differentiating self-esteem from external validation. Clients explored how dependency on others'' approval undermines autonomy and confidence. The therapist encouraged internal sources of affirmation to strengthen self-worth.', 21, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a session exploring how early attachment experiences influence adult self-esteem. Clients discussed patterns of conditional love and their long-term effects on self-image. The therapist guided reflective dialogue to promote healing and secure self-acceptance.', 22, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a cognitive-behavioral group addressing overgeneralization as a cognitive distortion that damages self-esteem. Clients identified all-or-nothing thinking patterns and practiced reframing failures as temporary and specific rather than global self-judgments.', 23, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a session emphasizing the connection between gratitude and self-esteem. Clients practiced recognizing personal accomplishments and internal strengths. The therapist reinforced the practice of self-affirmation as a daily self-care strategy.', 24, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a mindfulness-based group on observing the inner critic without attachment. Clients practiced naming and externalizing self-critical thoughts. The therapist modeled compassionate awareness to foster emotional distance from negative self-evaluation.', 25, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a discussion on resilience and self-esteem as interconnected processes. Clients identified moments when persistence led to personal growth despite adversity. The therapist emphasized self-trust as a foundation for enduring confidence.', 26, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a psychoeducational session addressing social comparison as a barrier to self-esteem. Clients discussed the impact of media and peer competition on self-worth. The therapist encouraged cognitive reframing and self-focus to restore perspective.', 27, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist guided a group exercise centered on personal affirmations and values identification. Clients created affirmations aligned with core beliefs rather than superficial achievements. The therapist reinforced congruence between self-image and authentic values.', 28, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a session examining the relationship between emotional regulation and self-esteem. Clients explored how impulsive reactions and guilt can erode confidence. The therapist introduced grounding and reflection skills to strengthen self-control and self-respect.', 29, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a discussion on the connection between self-esteem and boundary maintenance. Clients processed experiences of overextending themselves to gain approval. The therapist modeled assertive responses and promoted self-protection as an act of self-worth.', 30, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group exploring how self-esteem influences interpersonal relationships. Clients identified patterns of codependence, withdrawal, or defensiveness related to self-perception. The therapist emphasized balanced reciprocity and emotional self-sufficiency.', 31, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a reflective session on shame resilience. Clients examined how internalized shame inhibits self-expression and growth. The therapist introduced vulnerability-based exercises to cultivate self-acceptance and authenticity.', 32, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a psychoeducational session about self-talk modification as a therapeutic tool. Clients practiced identifying automatic negative thoughts and replacing them with evidence-based affirmations. The therapist reinforced the importance of language in shaping self-concept.', 33, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a session focusing on failure tolerance as a component of healthy self-esteem. Clients discussed personal experiences of perceived failure and their emotional impact. The therapist guided normalization and reframing to encourage adaptive risk-taking.', 34, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a group emphasizing the importance of recognizing progress rather than perfection. Clients shared incremental successes and challenges in maintaining confidence. The therapist encouraged reflection on growth as a measure of self-value.', 35, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a mindfulness-based group teaching present-focused awareness to reduce self-criticism. Clients learned to recognize moments of judgment and shift toward curiosity and acceptance. The therapist reinforced mindful awareness as a form of self-kindness.', 36, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a session exploring the impact of trauma on self-esteem formation. Clients reflected on how adverse experiences distorted their self-image. The therapist provided psychoeducation on trauma recovery and rebuilding self-worth through emotional safety.', 37, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a group discussion highlighting self-advocacy as a reflection of self-esteem. Clients practiced articulating needs and preferences confidently. The therapist modeled assertive communication and reinforced empowerment through self-expression.', 38, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a process-oriented session examining identity development and self-esteem. Clients reflected on how social roles, gender, or cultural identity influence self-perception. The therapist guided participants in defining self-worth based on authenticity rather than conformity.', 39, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a strengths-based closing session reinforcing the concept of unconditional self-acceptance. Clients revisited personal progress in reshaping negative self-beliefs. The therapist encouraged ongoing practice of self-validation, reflection, and compassionate awareness to sustain emotional growth.', 40, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group discussion on rebuilding self-esteem after periods of low motivation or emotional distress. Clients identified internal barriers to self-worth and practiced reframing moments of stagnation as opportunities for recovery and learning.', 41, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a session on authenticity as a foundation of self-esteem. Clients explored the consequences of masking true emotions to gain approval. The therapist encouraged congruence between values, behavior, and self-perception.', 42, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a cognitive-behavioral group examining the "impostor syndrome" phenomenon. Clients reflected on self-doubt despite evidence of competence. The therapist provided interventions focused on self-affirmation, realistic evaluation, and acknowledgment of personal achievements.', 43, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a mindfulness-based group teaching radical self-acceptance. Clients practiced grounding techniques to observe judgmental thoughts without resistance. The therapist emphasized that unconditional self-acceptance fosters stability and emotional regulation.', 44, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a psychoeducational session exploring the relationship between self-esteem and emotional boundaries. Clients analyzed how internalized guilt or fear of rejection affect their ability to set limits. The therapist guided assertiveness training to strengthen self-respect.', 45, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a process-oriented group addressing social anxiety rooted in low self-esteem. Clients discussed avoidance of social settings due to fear of judgment. The therapist introduced exposure planning and cognitive reframing to promote confidence and social competence.', 46, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a strengths-identification exercise to enhance awareness of personal abilities and growth areas. Clients created "strength statements" to challenge long-held self-critical beliefs. The therapist reinforced self-acknowledgment as a daily confidence-building habit.', 47, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist conducted a reflective group exploring the role of gratitude in self-esteem restoration. Clients shared personal qualities or life aspects they appreciate. The therapist highlighted gratitude as a corrective emotional experience against chronic self-doubt.', 48, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist led a session focused on the impact of chronic stress on self-esteem. Clients recognized how prolonged emotional strain diminishes self-efficacy and self-trust. The therapist introduced relaxation strategies and realistic self-expectations to restore balance.', 49, TRUE),
        (v_activity_id, v_self_esteem_id, 'IOP Therapist facilitated a group discussion addressing self-sabotaging behaviors. Clients identified patterns of undermining success or relationships due to fear of inadequacy. The therapist introduced behavioral awareness and self-monitoring to promote accountability and growth.', 50, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Self-Esteem"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 2: IDENTIFY TRIGGERS TO LOW (40 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_triggers_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'identify triggers to low'
    LIMIT 1;

    IF v_triggers_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Identify Triggers to Low', 'Identifying triggers that lower self-esteem', TRUE)
        RETURNING subactivity_id INTO v_triggers_id;
        RAISE NOTICE '✅ Subactividad "Identify Triggers to Low" creada';
    END IF;

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a cognitive-behavioral group exploring emotional and environmental triggers that contribute to decreased self-esteem. Clients identified specific situations, such as rejection or criticism, that intensify self-doubt. The therapist guided participants in recognizing early warning signs and developing adaptive coping strategies.', 1, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a session focused on understanding how automatic negative thoughts act as internal triggers for low self-esteem. Clients practiced identifying and challenging distorted cognitions rooted in perfectionism or fear of failure. The therapist reinforced self-awareness as the first step toward self-correction.', 2, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a psychoeducational discussion examining interpersonal dynamics that lower self-esteem. Clients reflected on patterns of comparison, invalidation, or dependency. The therapist introduced boundary-setting techniques to reduce vulnerability to external judgment.', 3, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a process-oriented group exploring how past trauma and unresolved emotional wounds trigger feelings of inadequacy. Clients processed memories that shaped their inner critic. The therapist emphasized self-compassion and grounding as tools for emotional stabilization.', 4, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist guided a mindfulness-based session on recognizing physiological and emotional cues of low self-esteem. Clients practiced body scanning and emotional labeling to identify moments of internal tension or withdrawal. The therapist highlighted the connection between somatic awareness and emotional regulation.', 5, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a group analyzing the influence of social comparison on self-esteem fluctuations. Clients discussed triggers such as social media exposure or perceived failure relative to peers. The therapist encouraged gratitude journaling and cognitive redirection to counter external validation seeking.', 6, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a session addressing family-of-origin messages that perpetuate low self-worth. Clients identified recurring themes of criticism, neglect, or unrealistic expectations. The therapist helped participants reframe inherited beliefs and establish self-supportive internal dialogue.', 7, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a group discussion on situational triggers related to rejection and abandonment fears. Clients examined how sensitivity to perceived exclusion impacts confidence. The therapist provided psychoeducation on attachment-based coping and emotional resilience.', 8, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a cognitive restructuring session addressing self-blame and over-responsibility as triggers for low self-esteem. Clients learned to differentiate accountability from self-devaluation. The therapist modeled balanced self-evaluation and promoted compassionate self-reflection.', 9, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a strengths-based group emphasizing how awareness of triggers allows for proactive emotional management. Clients created individualized trigger maps and paired each with a healthy coping response. The therapist reinforced that consistent recognition builds mastery and long-term confidence.', 10, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a session examining the relationship between emotional triggers and core beliefs of inadequacy. Clients identified recurring thought patterns such as "I''m not good enough" that arise during moments of perceived failure. The therapist introduced thought-tracking tools to increase awareness and promote cognitive flexibility.', 11, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a process group exploring how social rejection and criticism activate feelings of inferiority. Clients reflected on recent interactions that diminished confidence. The therapist encouraged emotional labeling and guided participants in reframing experiences through self-validation.', 12, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a cognitive-behavioral session identifying how perfectionism and fear of judgment serve as triggers for low self-esteem. Clients discussed the emotional cost of unrealistic expectations. The therapist provided interventions focused on acceptance, realistic goal-setting, and balanced self-assessment.', 13, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a mindfulness-based discussion helping clients detect subtle triggers of self-devaluation. Clients practiced noticing emotional shifts during conflict or perceived disapproval. The therapist reinforced grounding and self-compassion practices to counter immediate negative reactions.', 14, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist guided a psychoeducational group on understanding relational patterns that reinforce feelings of worthlessness. Clients examined codependent behaviors and the need for external validation. The therapist modeled assertive responses to strengthen self-agency and emotional independence.', 15, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a group focusing on identifying cognitive distortions—such as personalization and magnification—that intensify low self-esteem triggers. Clients practiced challenging these distortions with evidence-based reasoning. The therapist emphasized the use of daily self-monitoring to reduce recurrence.', 16, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a reflective session analyzing how internalized family criticism continues to affect self-worth. Clients discussed learned self-judgment and guilt responses. The therapist introduced reparenting techniques and positive self-talk to promote emotional repair.', 17, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a group exercise mapping personal triggers associated with shame and rejection. Clients recognized how specific tones, phrases, or environments evoke insecurity. The therapist guided desensitization strategies through gradual exposure and self-affirmation.', 18, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a session exploring the impact of chronic stress and exhaustion on self-esteem triggers. Clients noted how fatigue amplifies negative thinking and self-doubt. The therapist introduced self-care planning and relaxation training to maintain emotional stability.', 19, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a problem-solving group addressing workplace and social stressors that lower confidence. Clients identified how performance pressure and comparison intensify self-criticism. The therapist reinforced balanced evaluation, effective communication, and resilience-based coping strategies.', 20, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a group discussion exploring situational factors that trigger low self-esteem. Clients identified patterns such as comparison, rejection, or lack of recognition that activate self-critical thoughts. The therapist reinforced self-awareness as a foundation for emotional regulation.', 21, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a session addressing how perfectionism and unrealistic expectations contribute to episodes of diminished self-worth. Clients discussed how fear of failure intensifies self-judgment. The therapist guided cognitive reframing to promote realistic self-evaluation.', 22, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a psychoeducational group focused on recognizing internal versus external triggers to low self-esteem. Clients differentiated between external criticism and internalized beliefs. The therapist emphasized using mindfulness to track emotional shifts in real time.', 23, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a reflective session examining how early experiences of invalidation shaped current self-esteem triggers. Clients shared examples of how past criticism influences their present emotional responses. The therapist provided psychoeducation on reconditioning core beliefs.', 24, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a cognitive-behavioral session on identifying automatic negative thoughts that lower self-worth. Clients practiced journaling to document thought-emotion patterns. The therapist emphasized how increased awareness enables cognitive restructuring.', 25, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a discussion exploring the role of interpersonal rejection in self-esteem decline. Clients identified sensitivity to disapproval as a recurring theme. The therapist introduced assertive communication as a means to preserve self-respect.', 26, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a process group examining environmental stressors—such as work pressure or family conflict—that diminish confidence. Clients reflected on how chronic stress impacts self-perception. The therapist reinforced boundary-setting and self-care routines.', 27, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist guided a mindfulness-based session helping clients notice emotional triggers through body sensations and mental cues. The therapist encouraged present-moment awareness to intervene before negative self-talk escalates.', 28, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a group on social comparison and its effect on self-esteem. Clients explored how exposure to idealized images or achievements triggers inadequacy. The therapist promoted self-acceptance and gratitude-focused redirection.', 29, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a session analyzing the link between conflict avoidance and diminished self-esteem. Clients reflected on how silencing themselves to maintain peace reinforces feelings of inferiority. The therapist guided role-play exercises to strengthen assertiveness.', 30, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a psychoeducational discussion addressing how chronic self-criticism becomes a trigger for low self-esteem. Clients identified internal dialogues rooted in guilt and fear of disapproval. The therapist introduced compassionate self-talk techniques.', 31, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a process-oriented group exploring how relationship dynamics influence self-worth. Clients recognized patterns of emotional dependence or excessive caregiving. The therapist reinforced balanced reciprocity as a strategy for maintaining confidence.', 32, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a session examining workplace stress as a trigger for insecurity. Clients processed feelings of inadequacy tied to performance. The therapist introduced strengths recognition and realistic goal-setting as corrective approaches.', 33, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a group exploring the connection between fatigue and self-esteem vulnerability. Clients noticed how exhaustion amplifies negative self-perception. The therapist highlighted self-care and rest as essential emotional regulators.', 34, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist guided a session addressing cultural and familial expectations as triggers for low self-esteem. Clients discussed the pressure to meet idealized roles or standards. The therapist emphasized individuation and authenticity as pathways to self-worth.', 35, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a group on emotional triggers tied to comparison within family or peer groups. Clients reflected on envy, inadequacy, and competition dynamics. The therapist promoted self-validation and collaborative rather than competitive mindsets.', 36, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a cognitive-behavioral session addressing guilt and over-responsibility as recurring self-esteem triggers. Clients practiced distinguishing healthy accountability from self-blame. The therapist reinforced balanced responsibility and forgiveness.', 37, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist led a discussion identifying sensory or contextual cues—such as tone of voice or social environments—that activate low self-esteem responses. The therapist encouraged awareness and grounding when confronted with these cues.', 38, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist conducted a strengths-based session teaching clients to identify patterns that precede emotional withdrawal. Clients recognized isolation as both a symptom and trigger of low self-worth. The therapist reinforced engagement in supportive interactions.', 39, TRUE),
        (v_activity_id, v_triggers_id, 'IOP Therapist facilitated a closing session integrating all previously identified triggers into a self-awareness plan. Clients created personalized lists of warning signs and adaptive responses. The therapist reinforced proactive emotional monitoring as a long-term self-esteem maintenance skill.', 40, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Identify Triggers to Low"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 3: BUILDING SELF-CONFIDENCE (60 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_building_confidence_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'building self-confidence'
    LIMIT 1;

    IF v_building_confidence_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Building Self-Confidence', 'Developing self-confidence skills', TRUE)
        RETURNING subactivity_id INTO v_building_confidence_id;
        RAISE NOTICE '✅ Subactividad "Building Self-Confidence" creada';
    END IF;

    -- Insertar los 60 párrafos de Building Self-Confidence
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a group session focused on developing self-confidence through awareness of personal strengths and self-efficacy. Clients explored internal barriers such as fear of failure and self-doubt. The therapist encouraged participants to identify one strength they often minimize and to reframe it as evidence of capability, promoting a mindset of growth rather than inadequacy.', 1, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral group addressing self-defeating thoughts that interfere with confidence. Clients recognized how automatic negative thinking patterns distort self-perception. The therapist introduced thought-challenging techniques to replace unrealistic self-criticism with balanced, supportive internal dialogue.', 2, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a strengths-based session emphasizing the connection between consistent action and increased self-trust. Clients identified small daily tasks that could reinforce their sense of competence. The therapist highlighted that confidence builds through follow-through, persistence, and realistic self-acknowledgment.', 3, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a psychoeducational group on overcoming fear of rejection as a barrier to self-confidence. Clients processed experiences where avoidance behaviors reinforced insecurity. The therapist introduced exposure and assertiveness techniques to strengthen resilience and adaptive risk-taking.', 4, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a mindfulness-based group exploring the role of self-awareness in cultivating confidence. Clients practiced observing their internal dialogue and emotional reactions to perceived failure. The therapist emphasized mindful acceptance and curiosity as tools to reduce self-criticism and increase emotional regulation.', 5, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a reflective session encouraging clients to examine past achievements that contributed to personal growth. Participants discussed how acknowledging effort and progress strengthens intrinsic motivation. The therapist guided a group exercise on verbal affirmations to internalize self-recognition.', 6, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a process-oriented discussion examining how external validation impacts self-confidence. Clients shared insights about the pressure to meet others'' expectations. The therapist modeled self-affirming statements and encouraged shifting focus toward internal satisfaction rather than approval-seeking.', 7, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a group centered on identifying confidence-draining habits such as procrastination, overthinking, and excessive self-comparison. Clients reflected on underlying emotional triggers linked to these behaviors. The therapist encouraged implementation of small behavioral changes to promote mastery and autonomy.', 8, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a session integrating cognitive and behavioral interventions to promote self-confidence through behavioral activation. Clients were guided to select one task they had been avoiding due to insecurity. The therapist reinforced that progress, rather than perfection, is the key to self-assurance and personal growth.', 9, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a motivational group discussion emphasizing resilience as the foundation of self-confidence. Clients analyzed how past adversities have shaped their inner strength. The therapist encouraged participants to view resilience as evidence of competence and capability, promoting a stable, enduring sense of self-worth.', 10, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a cognitive-behavioral group focused on strengthening self-confidence through realistic self-assessment. Clients examined patterns of minimizing accomplishments and magnifying errors. The therapist guided participants in recognizing evidence of competence and reinforcing self-efficacy through balanced thinking.', 11, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a process-oriented session exploring how internalized criticism weakens confidence. Clients discussed experiences where negative feedback shaped self-doubt. The therapist introduced self-compassion statements and modeled reframing techniques to promote internal validation.', 12, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a psychoeducational group highlighting the link between assertiveness and confidence. Clients practiced communicating opinions respectfully while maintaining emotional control. The therapist emphasized that self-assured communication fosters empowerment and healthy interpersonal boundaries.', 13, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a session focused on identifying small, achievable goals to enhance confidence through mastery experiences. Clients developed personalized plans emphasizing consistent effort. The therapist reinforced that self-trust grows when individuals follow through on their commitments.', 14, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a mindfulness-based discussion on how self-awareness supports confidence. Clients practiced grounding techniques to remain present during moments of self-doubt. The therapist encouraged mindful recognition of strengths as a countermeasure to negative self-perception.', 15, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a reflective group exploring how past accomplishments can serve as anchors for current confidence. Clients shared personal success stories to reinforce positive identity development. The therapist highlighted how recalling resilience promotes stability and motivation.', 16, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a strengths-identification exercise encouraging clients to acknowledge and verbalize positive qualities. The therapist guided the group in transforming modest or dismissive language into assertive self-affirmations, reinforcing adaptive confidence-building.', 17, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral group examining avoidance behaviors rooted in insecurity. Clients identified situations where fear of inadequacy prevented engagement. The therapist encouraged gradual exposure to challenges as a means of reinforcing confidence through experience.', 18, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a psychoeducational session addressing the difference between confidence and arrogance. Clients explored how authentic self-assurance includes humility and self-respect. The therapist modeled balanced confidence and reinforced that genuine self-esteem is grounded in self-awareness.', 19, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a motivational group encouraging clients to identify role models who embody healthy confidence. Participants discussed observable traits such as persistence and calm under pressure. The therapist guided reflection on how these qualities can be integrated into personal development goals.', 20, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a psychoeducational session exploring the foundations of self-confidence and its relationship with self-concept. Clients discussed how early experiences and feedback shaped their belief in personal ability. The therapist introduced exercises for recognizing strengths and reframing self-limiting thoughts.', 21, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral group addressing the fear of failure as a major obstacle to confidence. Clients explored patterns of avoidance and perfectionism that reinforce insecurity. The therapist encouraged embracing mistakes as opportunities for learning and resilience.', 22, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a mindfulness-based session teaching clients how to use present-focused awareness to reduce performance anxiety. Clients practiced breathing exercises and grounding techniques. The therapist emphasized that calm self-awareness improves confidence and decision-making under pressure.', 23, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a reflective group focused on how internal dialogue influences self-confidence. Clients identified critical self-talk patterns and replaced them with evidence-based affirmations. The therapist reinforced consistent cognitive monitoring as a tool for emotional balance.', 24, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a process-oriented group exploring the connection between confidence and authenticity. Clients discussed moments when hiding true emotions led to insecurity. The therapist emphasized congruence between thoughts, emotions, and behaviors as the basis for genuine confidence.', 25, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a motivational group helping clients set realistic short-term goals to strengthen confidence. Participants identified achievable steps toward personal or professional growth. The therapist provided feedback on progress tracking to enhance self-efficacy.', 26, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a discussion about social comparison and its detrimental effects on confidence. Clients shared experiences of self-judgment in competitive environments. The therapist guided cognitive reframing techniques and promoted gratitude as a corrective mindset.', 27, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a strengths-based session where clients reflected on qualities that have helped them navigate adversity. The therapist encouraged acknowledgment of perseverance and adaptability as key contributors to long-term confidence.', 28, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a psychoeducational group on body language and its impact on self-perception. Clients practiced maintaining eye contact, upright posture, and steady tone when communicating. The therapist emphasized the reciprocal relationship between physical expression and internal confidence.', 29, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a cognitive-processing discussion exploring how emotional regulation supports self-confidence. Clients identified situations where frustration or fear undermined assertiveness. The therapist modeled coping strategies to maintain composure and reinforce self-trust.', 30, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a group centered on redefining success in personal terms. Clients explored how societal expectations create unrealistic standards. The therapist encouraged self-defined goals that align with intrinsic motivation and authentic satisfaction.', 31, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a reflection-based session examining the role of self-discipline in confidence building. Clients discussed the connection between consistency, reliability, and self-respect. The therapist guided participants in creating daily habits that reinforce self-mastery.', 32, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a group discussion on the importance of resilience after setbacks. Clients analyzed how recovery from adversity enhances self-belief. The therapist encouraged them to view challenges as tests of strength rather than evidence of weakness.', 33, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a process group examining how external validation affects internal stability. Clients reflected on how praise and criticism influence their confidence levels. The therapist introduced strategies for developing internal sources of validation and independence.', 34, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a mindfulness-integrated session encouraging clients to approach tasks with curiosity rather than fear. The therapist explained how curiosity decreases anxiety and increases willingness to take healthy risks—key factors in confidence development.', 35, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a session exploring how overgeneralization of negative feedback damages self-confidence. Clients practiced separating isolated criticism from global self-judgment. The therapist reinforced accurate self-assessment as an essential confidence skill.', 36, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral group on identifying success-inhibiting beliefs. Clients examined thoughts such as "I''m not ready" or "I don''t deserve success." The therapist guided participants in developing evidence-based counterstatements to challenge those beliefs.', 37, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a reflective discussion focused on the role of gratitude in confidence-building. Clients identified personal accomplishments or supportive relationships that reinforce positive self-concept. The therapist encouraged incorporating gratitude journaling into daily routines.', 38, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a psychoeducational group on assertive communication as a marker of confidence. Clients practiced expressing needs clearly without defensiveness. The therapist highlighted that assertiveness promotes both respect for others and self-empowerment.', 39, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a closing group helping clients integrate all learned techniques to sustain confidence. Participants reviewed personal progress, identifying areas of continued growth. The therapist reinforced maintenance strategies such as self-affirmation, mindfulness, and behavioral consistency.', 40, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a group discussion on identifying and dismantling self-sabotaging behaviors that undermine confidence. Clients explored avoidance, overthinking, and excessive reassurance-seeking as patterns rooted in fear of inadequacy. The therapist introduced awareness techniques to interrupt these cycles and promote accountability.', 41, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral session addressing self-limiting beliefs formed through repeated failure experiences. Clients practiced reframing "I can''t" statements into flexible, growth-oriented perspectives. The therapist reinforced that persistence, not perfection, drives self-assurance.', 42, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a mindfulness-based group focused on recognizing inner dialogue as a determinant of confidence. Clients practiced observing negative thoughts without identifying with them. The therapist emphasized cognitive diffusion as a method to reduce the emotional impact of self-criticism.', 43, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a psychoeducational session on the importance of self-advocacy. Clients discussed challenges in expressing personal needs assertively. The therapist guided exercises on using direct language, highlighting that advocating for oneself strengthens confidence and autonomy.', 44, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a reflective group exploring how comparison with others erodes confidence. Clients analyzed emotional reactions to perceived competition. The therapist promoted individualized self-evaluation and encouraged focusing on progress over perfection.', 45, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a process group emphasizing emotional validation as a foundation for confidence. Clients discussed how self-acceptance during distressing moments can stabilize self-esteem. The therapist modeled compassionate self-talk and encouraged daily self-soothing practices.', 46, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a group on building self-confidence through behavioral activation. Clients identified a small but challenging task to complete within the week. The therapist reinforced the idea that confidence strengthens through direct action and consistent follow-through.', 47, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a psychoeducational discussion highlighting the connection between posture, body language, and perceived confidence. Clients practiced nonverbal cues such as maintaining open posture and steady tone. The therapist reinforced the mind-body feedback loop between stance and self-belief.', 48, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a group exploring the role of failure tolerance in self-confidence development. Clients reflected on past mistakes and what they revealed about resilience. The therapist emphasized that self-trust is built by facing discomfort rather than avoiding it.', 49, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a session encouraging clients to identify and challenge internalized messages of inadequacy from family or social environments. The therapist guided cognitive reframing to promote autonomy and emotional empowerment.', 50, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a process group on the connection between identity and confidence. Clients explored how aligning behaviors with personal values fosters authenticity and stability. The therapist highlighted congruence as a predictor of long-term confidence.', 51, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a mindfulness-centered session promoting self-confidence through self-compassion. Clients practiced redirecting judgmental thoughts with curiosity and kindness. The therapist guided breathing and reflection exercises to anchor acceptance.', 52, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a reflective group examining how achievement pressure undermines self-confidence. Clients discussed experiences of tying worth to productivity. The therapist encouraged redefining success to include effort, growth, and emotional balance.', 53, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a cognitive-behavioral session focused on internal locus of control. Clients explored how attributing success and failure to personal agency fosters confidence. The therapist reinforced self-accountability without self-blame.', 54, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a psychoeducational group exploring the neuroscience of confidence, explaining how repeated mastery experiences strengthen neural pathways associated with motivation. Clients discussed ways to reinforce positive habits through consistency.', 55, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a process-oriented group on self-acceptance after rejection. Clients identified emotional triggers and negative assumptions formed from social setbacks. The therapist encouraged reframing rejection as a reflection of circumstance rather than personal deficiency.', 56, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a discussion on assertive decision-making as a form of confidence expression. Clients practiced evaluating choices based on self-respect rather than fear of disapproval. The therapist modeled calm, rational communication strategies.', 57, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist led a strengths-based group emphasizing gratitude as a pathway to sustainable confidence. Clients listed attributes or experiences that highlight competence and growth. The therapist reinforced gratitude as a cognitive anchor during periods of doubt.', 58, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist facilitated a session on developing confidence through self-consistency. Clients explored the psychological benefits of following through on commitments, even small ones. The therapist emphasized integrity between intention and action as the root of confidence.', 59, TRUE),
        (v_activity_id, v_building_confidence_id, 'IOP Therapist conducted a closing group integrating lessons from previous sessions. Clients reflected on progress in replacing self-doubt with empowered thinking. The therapist reinforced continued use of mindfulness, cognitive reframing, and self-affirmation to maintain confidence in daily life.', 60, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Building Self-Confidence"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 4: PRACTICE SELF-CARE (50 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_practice_selfcare_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'practice self-care'
    LIMIT 1;

    IF v_practice_selfcare_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Practice Self-Care', 'Self-care practices for self-esteem', TRUE)
        RETURNING subactivity_id INTO v_practice_selfcare_id;
        RAISE NOTICE '✅ Subactividad "Practice Self-Care" creada';
    END IF;

    -- Insertar los 50 párrafos de Practice Self-Care
    -- Por tamaño, insertaré todos los párrafos proporcionados por el usuario
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a psychoeducational group emphasizing the relationship between self-care and self-worth. Clients explored how neglecting physical or emotional needs reinforces low self-esteem. The therapist guided the group in developing individualized self-care plans to promote balance and self-respect.', 1, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a reflective session helping clients identify barriers that prevent consistent self-care. Participants discussed guilt, fatigue, and time management difficulties. The therapist encouraged reframing self-care as a necessity rather than a luxury.', 2, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a mindfulness-based group focusing on the importance of present-moment awareness in self-care. Clients practiced guided breathing and grounding techniques to enhance emotional regulation. The therapist reinforced that mindful attention strengthens self-trust and inner calm.', 3, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a discussion on how early family dynamics shape current self-care habits. Clients identified learned behaviors around rest, nutrition, and boundaries. The therapist guided insight-oriented reflection to promote healthier daily routines.', 4, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a cognitive-behavioral session on challenging the belief that prioritizing oneself is selfish. Clients explored how such cognitive distortions hinder emotional recovery. The therapist modeled assertive language for communicating personal needs.', 5, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a strengths-based group helping clients recognize self-care as an act of empowerment. Participants identified personal coping tools—such as journaling, exercise, or creative outlets—that enhance emotional stability. The therapist emphasized intentional practice as reinforcement for self-esteem.', 6, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a reflective session on the link between burnout and diminished self-esteem. Clients described signs of emotional exhaustion and its impact on daily functioning. The therapist provided education on preventive care and sustainable energy management.', 7, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a process-oriented discussion exploring emotional neglect and its long-term effect on self-care. Clients reflected on difficulty acknowledging their needs. The therapist introduced compassionate self-dialogue to normalize nurturing oneself.', 8, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a psychoeducational group addressing the role of boundaries in maintaining self-care. Clients practiced identifying personal limits and recognizing when overextension leads to resentment or fatigue. The therapist emphasized assertive communication as essential to emotional preservation.', 9, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a mindfulness-integrated session on body awareness as part of self-care. Clients practiced observing sensations of tension or relaxation to identify unmet physical needs. The therapist encouraged body scanning as a daily grounding tool.', 10, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a session helping clients distinguish between escapism and genuine self-care. Clients discussed how avoidance behaviors, such as overuse of technology or isolation, mimic rest but undermine emotional well-being. The therapist reinforced intentional, restorative practices.', 11, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a problem-solving group assisting clients in creating structured self-care schedules. Participants outlined specific daily habits to support physical and emotional health. The therapist emphasized accountability and consistency to enhance self-efficacy.', 12, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a group discussion about how emotional regulation improves with consistent self-care. Clients shared experiences where healthy routines reduced irritability and anxiety. The therapist reinforced behavioral tracking as a method of sustaining progress.', 13, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a psychoeducational session on recognizing self-neglect as a symptom of low self-esteem. Clients reflected on patterns of overworking or self-sacrifice. The therapist guided reframing of rest and nourishment as essential aspects of self-respect.', 14, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a reflective group examining how self-care contributes to resilience during stress. Clients explored which practices help them recover after emotional exhaustion. The therapist emphasized the connection between self-regulation and internal strength.', 15, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a cognitive-behavioral group helping clients link emotional triggers to lapses in self-care. Participants analyzed how stress leads to inconsistent routines. The therapist provided grounding and planning tools to promote balance.', 16, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a mindfulness-based session promoting emotional healing through relaxation and compassion. Clients practiced guided visualization focused on self-acceptance. The therapist reinforced that calmness nurtures confidence and clarity.', 17, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a discussion about redefining productivity to include rest and restoration. Clients examined the pressure to constantly perform and how it leads to depletion. The therapist encouraged valuing downtime as a form of psychological renewal.', 18, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a group centered on the emotional dimension of self-care. Clients discussed how emotional expression, journaling, and seeking support help them process internal experiences. The therapist modeled validation as an essential self-care skill.', 19, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a closing session integrating all aspects of self-care explored in prior meetings. Clients identified specific physical, emotional, and social strategies they plan to maintain. The therapist reinforced the concept of ongoing self-care as the foundation for long-term self-esteem stability.', 20, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a group session highlighting the link between consistent self-care and emotional regulation. Clients explored how neglecting rest or nutrition contributes to irritability and fatigue. The therapist emphasized that balanced routines promote self-respect and improve overall functioning.', 21, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a reflective group helping clients identify self-care activities that foster self-esteem. Participants shared coping methods such as journaling, mindfulness, or physical exercise. The therapist encouraged integrating at least one restorative practice into daily routines.', 22, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a cognitive-behavioral discussion exploring distorted beliefs that frame self-care as undeserved. Clients examined guilt and negative self-talk when prioritizing personal needs. The therapist modeled compassionate self-affirmations to counter self-neglect.', 23, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a mindfulness-based group focusing on using relaxation as a therapeutic form of self-care. Clients practiced guided breathing and grounding exercises. The therapist reinforced the value of slowing down to strengthen emotional stability and self-trust.', 24, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a psychoeducational session addressing how chronic stress erodes self-care behaviors. Clients identified early signs of burnout and learned preventive coping techniques. The therapist encouraged consistent boundary-setting to preserve mental and physical energy.', 25, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a process-oriented discussion exploring emotional barriers to self-care. Clients reflected on how shame, trauma, or low motivation interfere with personal well-being. The therapist validated these challenges and introduced small, achievable behavioral changes.', 26, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a reflective group encouraging clients to redefine self-care beyond pampering. Participants discussed emotional hygiene, healthy boundaries, and balanced routines. The therapist reinforced viewing self-care as a daily act of self-preservation.', 27, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a session emphasizing how consistent self-care improves self-esteem and interpersonal relationships. Clients explored how meeting personal needs enhances empathy and patience with others. The therapist promoted self-nourishment as essential to relational health.', 28, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a cognitive restructuring group identifying thought patterns that rationalize self-neglect. Clients challenged beliefs such as "I don''t have time for myself." The therapist guided reframing exercises that linked rest to increased effectiveness and self-worth.', 29, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a mindfulness exercise centered on sensory awareness as a grounding form of self-care. Clients engaged in breathing and visualization to connect with body and mind. The therapist highlighted how intentional presence cultivates inner peace and confidence.', 30, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a group addressing the connection between healthy sleep patterns and emotional resilience. Clients shared how sleep deprivation influences mood and concentration. The therapist encouraged establishing nighttime routines to support psychological balance.', 31, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a psychoeducational group teaching self-care through nutrition and movement. Clients explored how balanced meals and light exercise enhance self-image. The therapist provided examples of realistic lifestyle adjustments to support mental well-being.', 32, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a process group examining how overcommitment and people-pleasing undermine self-care. Clients reflected on the difficulty of saying no. The therapist modeled assertive communication to reinforce personal boundaries and emotional safety.', 33, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a reflective session exploring how emotional awareness guides self-care decisions. Clients learned to identify physical sensations as indicators of stress or imbalance. The therapist emphasized that tuning into the body supports self-regulation.', 34, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a cognitive-behavioral group addressing avoidance behaviors that replace authentic self-care. Clients identified distractions like overworking or social withdrawal. The therapist guided participants to replace avoidance with intentional, restorative activities.', 35, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a session helping clients differentiate between self-soothing and self-care. Clients discussed how temporary distractions fail to meet deeper emotional needs. The therapist encouraged integrating sustainable, value-based self-care practices.', 36, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a group focusing on emotional self-care through self-compassion and validation. Clients practiced gentle internal dialogue during moments of distress. The therapist reinforced that kindness toward oneself fosters long-term emotional security.', 37, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a session on time management as an essential component of self-care. Clients created structured schedules balancing productivity and rest. The therapist emphasized that prioritizing self-maintenance prevents emotional depletion.', 38, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a mindfulness and journaling group promoting reflection on personal growth. Clients wrote about recent efforts toward self-care and their emotional impact. The therapist validated progress and encouraged continued practice as reinforcement of self-esteem.', 39, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a closing group integrating emotional, physical, and spiritual aspects of self-care. Clients shared strategies for maintaining well-being beyond the program. The therapist highlighted that consistent self-nurturing behaviors strengthen confidence and inner stability.', 40, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a reflective group emphasizing the concept of self-care as preventive mental health. Clients discussed how neglecting personal needs often precedes emotional instability. The therapist guided participants in identifying early signs of imbalance and implementing restorative activities.', 41, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a psychoeducational group on the relationship between self-care and emotional regulation. Clients learned how consistent routines support resilience during stress. The therapist reinforced viewing self-care as an act of emotional accountability.', 42, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a mindfulness-based session encouraging clients to reconnect with their physical and emotional states. Clients practiced grounding through breath awareness. The therapist highlighted how tuning into bodily cues fosters self-awareness and compassionate self-maintenance.', 43, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a cognitive-behavioral discussion challenging perfectionistic attitudes that hinder self-care. Clients explored how overcommitment and guilt interfere with rest. The therapist modeled cognitive reframing to replace self-criticism with balanced self-permission.', 44, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a process group addressing emotional exhaustion as a consequence of poor self-care. Clients recognized behaviors such as overworking or people-pleasing. The therapist encouraged the use of structured breaks and mindful reflection to prevent burnout.', 45, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a reflective group helping clients redefine self-care beyond physical acts. Participants explored emotional and social dimensions, such as meaningful connection and self-validation. The therapist emphasized that holistic care strengthens identity and self-esteem.', 46, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a psychoeducational session teaching clients to identify cognitive distortions that justify self-neglect. Clients challenged beliefs like "I don''t deserve rest." The therapist reinforced that prioritizing wellness enhances long-term productivity and psychological health.', 47, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist conducted a mindfulness and relaxation group promoting presence during routine tasks. Clients learned to infuse daily moments—like eating or walking—with intention. The therapist reinforced that mindful engagement transforms simple actions into restorative self-care practices.', 48, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist led a session on the role of boundaries as a form of advanced self-care. Clients discussed situations where saying "yes" led to resentment or fatigue. The therapist encouraged assertive boundary maintenance as a demonstration of self-respect.', 49, TRUE),
        (v_activity_id, v_practice_selfcare_id, 'IOP Therapist facilitated a group focused on self-care for emotional regulation. Clients identified activities that reduce anxiety, such as nature walks or deep breathing. The therapist guided the creation of individualized "emotional reset" plans to manage stress effectively.', 50, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Practice Self-Care"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 5: DAILY ACCOMPLISHMENTS (40 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_daily_accomplishments_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'daily accomplishments'
    LIMIT 1;

    IF v_daily_accomplishments_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Daily Accomplishments', 'Recognizing daily accomplishments', TRUE)
        RETURNING subactivity_id INTO v_daily_accomplishments_id;
        RAISE NOTICE '✅ Subactividad "Daily Accomplishments" creada';
    END IF;

    -- Insertar los 40 párrafos de Daily Accomplishments
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a reflective group session focused on identifying daily accomplishments as a means to strengthen self-esteem. Clients discussed how recognizing small successes fosters a sense of competence and self-efficacy. The therapist encouraged consistent self-acknowledgment to counter negative self-appraisal patterns.', 1, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a psychoeducational session emphasizing the relationship between achievement recognition and self-worth. Clients explored how focusing on progress rather than perfection promotes intrinsic motivation. The therapist guided journaling exercises to record daily positive actions.', 2, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a group discussion highlighting how awareness of daily accomplishments reinforces adaptive self-perception. Clients reflected on overlooked personal achievements, such as maintaining routines or setting boundaries. The therapist emphasized cognitive reframing to shift attention toward growth.', 3, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a cognitive-behavioral group exploring how chronic self-criticism minimizes awareness of accomplishments. Clients identified internalized negative beliefs and replaced them with affirming thoughts. The therapist modeled realistic self-praise as a tool for emotional regulation.', 4, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a session encouraging clients to track personal milestones that support emotional stability. Participants shared examples of progress in communication, self-care, and problem-solving. The therapist reinforced positive reinforcement as a foundation for sustained motivation.', 5, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a group reflection on the psychological benefits of celebrating minor victories. Clients examined how daily recognition improves mood and enhances self-efficacy. The therapist encouraged the use of gratitude journaling as a mindfulness practice.', 6, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a process group where clients discussed resistance to acknowledging personal successes. Clients explored the role of low self-esteem and learned helplessness in minimizing progress. The therapist provided feedback on developing balanced self-perception.', 7, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a reflective exercise guiding clients to identify three meaningful actions completed during the week. Clients shared insights about self-efficacy and persistence. The therapist reinforced the link between task completion and identity reconstruction in recovery.', 8, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a psychoeducational discussion on the cognitive impact of acknowledging small daily goals. Clients explored how recognition activates reward pathways in the brain, promoting motivation and resilience. The therapist encouraged regular self-evaluation and affirmation.', 9, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a group exploring the relationship between self-esteem and behavioral consistency. Clients discussed how following through with small commitments increases confidence. The therapist guided participants in setting realistic daily intentions.', 10, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a strengths-based session where clients identified daily actions that reflected perseverance. Clients practiced reframing perceived failures into learning experiences. The therapist highlighted the importance of self-validation in maintaining long-term stability.', 11, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a reflective group on how external validation can overshadow internal recognition. Clients explored shifting from seeking approval to valuing self-recognition. The therapist guided participants toward autonomy in evaluating progress.', 12, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a psychoeducational group focusing on the emotional reinforcement gained from daily accomplishments. Clients discussed how this practice strengthens neural pathways associated with positive affect. The therapist introduced visualization exercises to internalize success.', 13, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a process group on developing self-esteem through behavioral activation. Clients reflected on how even small productive actions, such as organization or social interaction, increase self-worth. The therapist reinforced that self-esteem grows through consistent practice.', 14, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a discussion encouraging clients to compare their current level of functioning with past stages of distress. Clients noted how gradual improvement reflects resilience. The therapist validated progress and encouraged continued reflection on achievements.', 15, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a session focused on distinguishing genuine accomplishment from perfectionistic expectations. Clients examined the cognitive distortions that invalidate personal growth. The therapist introduced self-compassion practices to replace rigid self-standards.', 16, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a mindfulness-based group where clients practiced being present with feelings of accomplishment. Participants described sensations of pride, relief, and gratitude. The therapist guided clients to anchor those feelings as positive internal resources.', 17, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a reflective discussion on how tracking achievements improves accountability and self-discipline. Clients shared strategies for maintaining awareness of daily progress. The therapist emphasized the integration of this habit into recovery maintenance plans.', 18, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a cognitive restructuring exercise aimed at identifying automatic negative thoughts that overshadow progress. Clients practiced countering self-deprecating beliefs with factual evidence of accomplishment. The therapist reinforced objective self-assessment as a therapeutic tool.', 19, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a closing group session reviewing the role of daily accomplishments in reinforcing self-esteem. Clients summarized their week''s successes and reflected on emotional shifts experienced through self-recognition. The therapist encouraged ongoing documentation of achievements to sustain confidence and motivation.', 20, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a reflective group emphasizing how acknowledging daily accomplishments reinforces a positive self-narrative. Clients identified recent personal successes, no matter how small, and discussed how these experiences counteract feelings of inadequacy. The therapist encouraged verbal affirmation as a practice to solidify self-worth.', 21, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a psychoeducational session exploring how self-esteem develops through consistent recognition of effort. Clients learned that valuing incremental progress promotes self-trust. The therapist guided them in creating a personal list of daily achievements to increase awareness of competence.', 22, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a process group where clients reflected on how ignoring accomplishments perpetuates low self-esteem. Participants examined cognitive biases that dismiss success. The therapist provided tools for identifying and challenging these distortions.', 23, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a group discussion about how daily structure contributes to feelings of accomplishment. Clients explored how maintaining schedules and routines builds predictability and self-control. The therapist reinforced that consistent behavior fosters internal stability.', 24, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a strengths-based session highlighting the psychological benefits of celebrating small milestones. Clients discussed how validation of progress improves mood and reduces hopelessness. The therapist introduced positive reinforcement as a daily self-care tool.', 25, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a reflective group examining the emotional impact of acknowledging self-improvement in recovery. Clients shared examples of growth such as setting boundaries or managing urges. The therapist emphasized self-recognition as crucial for sustaining motivation.', 26, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a session focused on transforming daily accomplishments into evidence of resilience. Clients identified how completing tasks under stress demonstrates adaptability. The therapist guided them to internalize success as part of identity reconstruction.', 27, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a group exploring how comparison to others undermines appreciation of personal achievements. Clients discussed replacing external validation with internal pride. The therapist reinforced autonomy and intrinsic motivation as key to self-esteem development.', 28, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a psychoeducational discussion on how self-awareness of progress promotes cognitive restructuring. Clients reflected on replacing thoughts of "not enough" with "I am progressing." The therapist guided affirmations to integrate realistic self-appraisal.', 29, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a reflective group emphasizing emotional connection to daily accomplishments. Clients discussed how pride and gratitude can coexist with imperfection. The therapist encouraged mindfulness to enhance appreciation of small wins.', 30, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a group exploring barriers to recognizing achievements, such as shame, guilt, or perfectionism. Clients processed the origins of self-criticism. The therapist provided cognitive reframing techniques to challenge internalized negative beliefs.', 31, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a strengths-based session encouraging clients to reframe daily tasks—like cooking, attending therapy, or exercising—as legitimate accomplishments. The therapist highlighted how redefining success supports self-efficacy and reinforces healthy routines.', 32, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a group where clients identified patterns of dismissing achievements as "insignificant." They discussed how this habit perpetuates low self-esteem. The therapist modeled compassionate acknowledgment as a corrective experience.', 33, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a psychoeducational group explaining how consistent recognition of effort enhances motivation and accountability. Clients created personal checklists to monitor progress. The therapist emphasized celebrating effort, not only outcomes.', 34, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a reflective group on how accomplishments serve as evidence of change during recovery. Clients shared behavioral shifts like improved communication or self-regulation. The therapist validated progress and reinforced the connection between action and identity growth.', 35, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a mindfulness-based session where clients practiced reflecting on moments of success without judgment. They focused on the sensations associated with pride and satisfaction. The therapist encouraged daily repetition to strengthen emotional awareness.', 36, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a session addressing self-sabotage and the tendency to minimize success. Clients discussed fear of failure and discomfort with praise. The therapist introduced journaling prompts to explore and replace these maladaptive thought patterns.', 37, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist led a group emphasizing gratitude as a complementary practice to self-recognition. Clients listed things they were proud of accomplishing and shared how this shifted their perspective. The therapist explained how gratitude reinforces self-compassion and optimism.', 38, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist facilitated a session on identifying emotional growth as an accomplishment, not just tangible outcomes. Clients reflected on progress in self-control, patience, and empathy. The therapist highlighted these as indicators of internal transformation.', 39, TRUE),
        (v_activity_id, v_daily_accomplishments_id, 'IOP Therapist conducted a closing group reviewing the week''s achievements and emotional responses to success. Clients recognized how even minimal progress contributes to recovery. The therapist encouraged them to integrate daily acknowledgment into their self-care routines to maintain confidence and motivation.', 40, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Daily Accomplishments"', v_paragraph_count;

    RAISE NOTICE '✅✅✅ COMPLETADO: Self-Esteem con todas sus subactividades y párrafos insertados ✅✅✅';

END $$;

-- Verificar inserción parcial
SELECT 
    a.activity_name,
    s.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs
FROM activities a
LEFT JOIN subactivities s ON s.activity_id = a.activity_id
LEFT JOIN activity_paragraphs ap ON ap.subactivity_id = s.subactivity_id
WHERE LOWER(a.activity_name) = 'self-esteem'
GROUP BY a.activity_name, s.subactivity_name
ORDER BY a.activity_name, s.subactivity_name;
