-- =============================================
-- IOP: Coping Skills - MARTES - Cognitive Mechanisms
-- =============================================
-- Este script inserta los 52 párrafos para "Cognitive Mechanisms"
-- de la actividad "Coping Skills" para IOP del día MARTES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Coping Skills"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'coping skills'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Coping Skills" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Coping Skills" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Cognitive Mechanisms"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'cognitive mechanisms'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Cognitive Mechanisms', 'Exploring cognitive coping strategies and thought patterns', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Cognitive Mechanisms" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Cognitive Mechanisms" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 52 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on aim inhibition as a cognitive mechanism used to manage frustration and fear of failure. The therapist explained how individuals may unconsciously lower their goals to preserve self-esteem and reduce anxiety. Clients reflected on instances where they set modest objectives to avoid disappointment, and the session emphasized graded goal-setting as a healthier approach.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on altruism as a cognitive defense that transforms internal conflict into prosocial behavior. The therapist highlighted how helping others can serve both as a means of self-regulation and as a strategy for reducing personal distress. Clients shared examples of deriving meaning and relief through altruistic acts, reinforcing the adaptive value of this mechanism.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of compartmentalization as a strategy to manage internal contradictions. The therapist described how separating conflicting thoughts or emotions into distinct domains may help maintain temporary equilibrium, but also prevents full integration of the self. Clients examined personal examples, and the therapist encouraged recognition of compartmentalization patterns that interfere with authenticity.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on conversion as a cognitive mechanism in which psychological conflict is transformed into somatic symptoms. The therapist explained how stress may manifest through headaches, gastrointestinal distress, or other physical complaints. Clients reflected on mind–body connections in their own experiences, and the group emphasized the importance of addressing psychological roots rather than focusing solely on physical manifestations.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention on dissociation as a coping strategy. The therapist explained how detaching from reality or separating from parts of lived experience may protect against acute distress but risks impairing continuity of identity. Participants processed experiences of "disconnecting" under stress, and grounding techniques were introduced to enhance self-awareness and presence.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational discussion on introjection as a defense mechanism. The therapist clarified how individuals internalize attitudes, beliefs, or attributes of others, often unconsciously, as a way of coping with conflict or insecurity. Clients identified positive and negative instances of introjection in their lives, and the session emphasized the importance of developing autonomous self-definition.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on rationalization as a cognitive defense that provides plausible justifications for maladaptive behavior. The therapist highlighted how rationalization shields the Ego from guilt while maintaining distorted self-perceptions. Clients reflected on common rationalizations they use, and the therapist guided them toward cultivating accountability and more realistic self-appraisal.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group discussion on somatization as a mechanism in which psychological distress converts into bodily symptoms. The therapist explained how unresolved affect may manifest as fatigue, chronic pain, or other physical complaints. Clients processed their own experiences with psychosomatic symptoms, and the therapist emphasized the importance of integrating emotional awareness into health management.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group intervention on suppression as a conscious cognitive strategy. The therapist described how intentionally holding back unwanted thoughts or urges may help individuals function temporarily, but risks creating long-term tension. Clients explored times when suppression was useful, and the session focused on balancing restraint with constructive emotional expression.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on aim inhibition as a mechanism through which individuals lower their aspirations to minimize the risk of failure. The therapist explained how this process can reduce anxiety temporarily but also limit growth and achievement. Clients discussed personal experiences of setting "safer" goals, and the therapist emphasized graded exposure to challenges as a path toward resilience.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention on altruism as a cognitive mechanism that transforms personal distress into prosocial action. The therapist highlighted how helping others often functions as a way to regulate one''s own anxiety and foster a sense of meaning. Clients reflected on times they experienced relief through altruistic behaviors, reinforcing altruism as both adaptive and socially beneficial.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of compartmentalization as a defense that separates conflicting emotions into distinct mental domains. The therapist explained how this strategy reduces inner conflict in the short term but interferes with authenticity and integration of the self. Clients identified moments when compartmentalization created distance from their feelings, and the session emphasized healthier integrative practices.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on conversion as a mechanism where unresolved psychological tension manifests in physical symptoms. The therapist described the link between stress and somatic complaints, underscoring the importance of addressing psychological roots rather than focusing solely on physical manifestations. Clients shared examples of somatic distress linked to stress, and the therapist guided them in exploring psychosomatic connections.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group process on dissociation as a cognitive defense that separates the self from distressing aspects of reality. The therapist explained how dissociation can serve as a protective strategy during overwhelming stress but risks fragmenting continuity of identity. Clients reflected on experiences of feeling "detached" or "numb," and grounding techniques were introduced to restore presence and cohesion.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational discussion on idealization as a defense mechanism that emphasizes only positive attributes while neglecting limitations. The therapist explained how this can create unrealistic expectations in relationships and hinder genuine connection. Clients explored personal examples of idealization and were guided toward balanced appraisal as a step toward healthier relational dynamics.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group intervention on intellectualization as a strategy of overreliance on rational thought to avoid emotional discomfort. The therapist explained how intellectualization may offer temporary stability but blocks affective expression and authentic processing. Clients practiced incorporating both cognitive and emotional perspectives into their narratives, strengthening emotional literacy and self-awareness.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group session on suppression as a conscious mechanism of deliberately postponing unwanted thoughts. The therapist differentiated suppression from repression, emphasizing its intentional nature. Clients reflected on times they intentionally held back distressing thoughts to function effectively, and the therapist framed suppression as potentially adaptive when paired with planned emotional processing.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on symbolization as a defense where unacceptable impulses are expressed indirectly through metaphor, imagery, or symbolic acts. The therapist highlighted its presence in dreams, creative expression, and repetitive behaviors. Clients processed personal experiences where symbolic representation masked deeper conflicts, and the session underscored the importance of interpretation and insight to move toward resolution.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on aim inhibition as a cognitive strategy used to lower personal aspirations in order to reduce the fear of failure. The therapist explained how this mechanism can temporarily safeguard self-esteem, yet may also limit growth and motivation. Clients reflected on personal examples of setting overly modest goals, and the therapist encouraged them to explore gradual exposure to more challenging objectives.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational discussion on altruism as a mechanism that transforms intrapsychic conflict into prosocial behavior. The therapist emphasized how engaging in acts of service often regulates personal anxiety and strengthens meaning-making. Group members shared examples of how helping others provided them with relief, reinforcing altruism as a constructive coping strategy.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group intervention on conversion as a cognitive mechanism that channels unresolved stress into physical manifestations. The therapist highlighted the psychodynamic link between unconscious conflict and psychosomatic symptoms such as headaches, fatigue, or gastrointestinal discomfort. Clients processed their own experiences of stress-related somatic complaints, and the therapist emphasized the value of integrated mind–body awareness.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of dissociation as a defense mechanism. The therapist explained how separating from aspects of lived experience can offer temporary protection against overwhelming affect but risks impairing cohesion of identity. Clients reflected on times when dissociation left them feeling detached or fragmented, and grounding strategies were introduced to promote present-moment awareness.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on identification as a cognitive defense in which individuals internalize the attributes or behaviors of others. The therapist described how this process can foster belonging and ego strengthening, while also highlighting risks of dependency and loss of authenticity. Participants discussed examples of adopting traits from mentors or peers, and the therapist encouraged selective internalization of adaptive characteristics.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on intellectualization as a mechanism of detachment from emotional intensity. The therapist explained how focusing solely on rational analysis provides temporary control but restricts emotional processing. Clients practiced combining factual reasoning with affective expression to promote psychological integration and enhance interpersonal authenticity.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group session on projection as an unconscious cognitive mechanism in which unwanted impulses are attributed to others. The therapist emphasized how projection temporarily reduces intrapsychic conflict but distorts relationships and reality testing. Clients shared moments where projection escalated interpersonal conflict, and reflective practices were introduced to increase accountability and insight.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of somatization as a manifestation of psychological distress in physical symptoms. The therapist explained how unresolved conflicts may surface as chronic pain, fatigue, or other bodily complaints. Clients reflected on their own somatic experiences, and the group was encouraged to integrate emotional awareness into their health management practices.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational intervention on suppression as a conscious mechanism that intentionally postpones distressing thoughts. The therapist clarified its difference from repression, underscoring that suppression involves deliberate control rather than unconscious exclusion. Clients processed situations where suppression was adaptive in the short term, and the session emphasized the importance of scheduling time for emotional processing.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group focused on mental defense mechanisms as unconscious strategies individuals use to manage anxiety and internal conflict. The therapist explained how these processes—such as denial, repression, and rationalization—distort reality to reduce emotional distress. Clients explored personal examples of these defenses in action and discussed how increasing self-awareness can lead to healthier emotional regulation.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on aim inhibition as a cognitive mechanism that lowers one''s goals to prevent the experience of failure. The therapist explained how this defense can protect self-esteem in the short term but may limit personal growth. Clients reflected on instances where they set overly modest goals and discussed how incremental exposure to challenge can enhance confidence and resilience.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of altruism as a constructive defense mechanism that channels personal tension into helping others. The therapist highlighted how prosocial acts can regulate distress and foster a sense of meaning. Clients shared examples of using altruism to manage their emotions and identified the difference between genuine empathy and avoidance-based caretaking.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on avoidance as a coping mechanism that temporarily shields individuals from distress. The therapist emphasized how avoidance may prevent immediate discomfort but reinforces long-term anxiety and emotional stagnation. Clients identified patterns of avoidance in their daily lives and practiced planning gradual exposure to increase emotional tolerance.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational group on compartmentalization as a defense that separates conflicting emotions into distinct psychological spaces. The therapist explained how this defense preserves short-term stability but can interfere with emotional integration. Clients examined how dividing aspects of their identity or experience has impacted authenticity and discussed ways to achieve greater internal coherence.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on conversion as a mechanism in which psychological stress manifests through physical symptoms. The therapist explained that somatic expressions of anxiety often emerge when emotions remain unprocessed. Clients reflected on personal experiences of tension or fatigue linked to stress and discussed techniques for increasing emotional expression to prevent psychosomatic distress.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on denial as a primitive defense mechanism that rejects distressing realities. The therapist described how denial shields individuals from emotional overwhelm but disrupts awareness and insight. Clients shared experiences of self-denial and explored strategies for developing acceptance and cognitive flexibility.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on displacement as a mechanism that redirects emotions from a threatening target to a safer one. The therapist highlighted how displaced anger or frustration often harms relationships. Clients identified situations where they misdirected emotion and practiced using self-awareness to address the root cause directly.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group exploration of dissociation as a psychological strategy for detaching from overwhelming experiences. The therapist explained how dissociation serves as a protective mechanism during trauma but may impair continuity of self if used chronically. Clients reflected on episodes of emotional numbness or detachment and practiced grounding techniques to restore presence and connection.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on fantasy as a defense mechanism that provides escape from stressful or unsatisfying reality. The therapist discussed how imagination can serve as both a creative outlet and a barrier to engagement with real-life problems. Clients identified instances of escapism and developed mindfulness-based tools to remain present while preserving creativity.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on idealization as a cognitive distortion that amplifies positive qualities while ignoring flaws. The therapist explained how idealization creates unrealistic expectations and emotional dependency. Clients explored how this defense has shaped their relationships and practiced balanced perception as a tool for emotional maturity.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on identification as a defense mechanism involving the unconscious adoption of traits from others. The therapist emphasized how identification can strengthen self-esteem but may blur individuality. Clients reflected on influential figures they have modeled and discussed ways to internalize adaptive traits while maintaining authenticity.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group session on intellectualization as an avoidance strategy that overemphasizes logic to suppress emotion. The therapist illustrated how excessive rationalizing distances individuals from genuine emotional experience. Clients practiced combining factual analysis with emotional acknowledgment to foster integrated self-awareness.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on introjection as a defense involving the internalization of external attitudes or values. The therapist explained how introjection can enhance belonging but also create internal conflict when absorbed values contradict personal beliefs. Clients identified beliefs inherited from family or peers and discussed methods for defining their authentic identity.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on passive aggression as a form of covert hostility expressed through indirect actions. The therapist explained how this defense allows the release of anger while avoiding confrontation. Clients explored how passive resistance has impacted their communication and practiced assertive strategies to express emotions openly.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of projection as an unconscious defense that attributes one''s own negative emotions to others. The therapist emphasized how projection distorts interpersonal perception and hinders accountability. Clients reflected on times they externalized internal conflict and discussed the benefits of introspection and emotional ownership.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on rationalization as a cognitive defense that creates logical justifications for maladaptive behavior. The therapist explained how rationalization protects the ego from guilt but maintains avoidance of responsibility. Clients identified rationalizations in their own narratives and developed self-reflective skills to promote authenticity and accountability.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group on reaction formation as a mechanism that replaces unacceptable impulses with exaggerated opposite behaviors. The therapist explained how this incongruence often leads to internal tension and confusion. Clients discussed examples of overcompensating behaviors and learned to tolerate ambivalence as part of emotional growth.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on regression as a defense that reverts to earlier developmental behaviors during stress. The therapist discussed how regressive tendencies can provide comfort but interfere with adult coping and independence. Clients identified situations where they sought safety through dependency and practiced self-soothing and problem-solving techniques.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a psychoeducational session on repression as an unconscious exclusion of distressing thoughts or emotions. The therapist highlighted how repressed material can reemerge through anxiety or intrusive thoughts. Clients discussed the therapeutic value of safe exploration and practiced mindfulness-based strategies for emotional release.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on somatization as the process of translating psychological conflict into physical symptoms. The therapist explained that somatization reflects emotional suppression and body–mind disconnection. Clients explored psychosomatic experiences and learned relaxation and expression techniques to promote mind–body integration.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on suppression as a conscious attempt to postpone unwanted thoughts. The therapist distinguished suppression from repression, emphasizing its intentional and adaptive potential when managed effectively. Clients discussed situations where delaying emotional expression was helpful and created plans for revisiting unresolved feelings safely.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group discussion on symbolization as a defense mechanism that expresses unconscious conflict through metaphor, art, or symbolic behavior. The therapist encouraged clients to explore the emotional meaning behind their creative expressions or recurring imagery. The group practiced interpreting symbols as pathways to greater self-understanding.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on trivializing as a cognitive defense that minimizes emotional pain. The therapist explained how this mechanism reduces perceived threat but invalidates one''s own experiences. Clients identified times they downplayed distress and practiced emotional validation to foster resilience and authenticity.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a closing group integrating mental defense mechanisms within a framework of self-awareness and growth. The therapist emphasized that recognizing these patterns is the first step toward transforming them into adaptive coping strategies. Clients reflected on personal insights and committed to applying mindfulness, accountability, and emotional honesty in daily life.', 52);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Cognitive Mechanisms" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'coping skills'
AND LOWER(sa.subactivity_name) = 'cognitive mechanisms'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

