-- =============================================
-- IOP: Health Management Addiction - LUNES (COMPLETO)
-- =============================================
-- Este script inserta la actividad "Health Management Addiction" para IOP del día LUNES
-- Incluye: Actividad + 2 subactividades con TODOS sus párrafos
-- NOTA: NO elimina actividades existentes, solo añade Health Management Addiction
-- =============================================

-- Insertar actividad "Health Management Addiction" para IOP
DO $$
DECLARE
    v_activity_id UUID;
    v_drug_interactions_id UUID;
    v_adverse_reactions_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Buscar si ya existe la actividad "Health Management Addiction"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'health management addiction'
    LIMIT 1;

    -- Si no existe, crearla
    IF v_activity_id IS NULL THEN
        INSERT INTO activities (activity_name, description, is_active)
        VALUES ('Health Management Addiction', 'Health Management Addiction activities for IOP groups - Monday', TRUE)
        RETURNING activity_id INTO v_activity_id;
        
        RAISE NOTICE '✅ Actividad "Health Management Addiction" creada con ID: %', v_activity_id;
    ELSE
        RAISE NOTICE '✅ Actividad "Health Management Addiction" ya existe con ID: %', v_activity_id;
    END IF;

    -- =============================================
    -- SUBACTIVIDAD 1: DRUG INTERACTIONS, SIDE EFFECTS RISKS (50 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_drug_interactions_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'drug interactions, side effects risks'
    LIMIT 1;

    IF v_drug_interactions_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Drug Interactions, Side Effects Risks', 'Understanding drug interactions and side effects', TRUE)
        RETURNING subactivity_id INTO v_drug_interactions_id;
        RAISE NOTICE '✅ Subactividad "Drug Interactions, Side Effects Risks" creada';
    END IF;

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group on understanding how substance use alters pharmacological effectiveness. Clients learned how combining prescription medication with illicit drugs can produce unpredictable physiological and psychological reactions. The therapist emphasized harm reduction and the importance of medical disclosure.', 1, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a session educating clients about the risks of poly-substance use. Participants discussed how combining stimulants and depressants impacts cardiac, hepatic, and neurological systems. The therapist highlighted the cumulative effects of toxicity and impaired judgment.', 2, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a cognitive-behavioral group addressing the lack of awareness around drug interactions. Clients identified misconceptions about "safe combinations." The therapist provided factual clarification and encouraged clients to consult medical professionals before taking new substances.', 3, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a reflective discussion on the psychological consequences of ignoring side effects. Clients explored experiences of mood instability, paranoia, or sedation caused by mixing substances. The therapist promoted insight into how denial sustains the addiction cycle.', 4, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a psychoeducational session explaining how chronic drug use changes neurochemical pathways and medication response. Clients gained understanding of tolerance, cross-dependence, and potential overdose triggers. The therapist reinforced consistent medical monitoring.', 5, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group discussion focused on the connection between self-medication and unrecognized drug interactions. Clients explored emotional motives behind misuse of prescription or over-the-counter drugs. The therapist emphasized the importance of developing non-chemical coping strategies.', 6, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a group on identifying common side effects of psychotropic medications when combined with substances such as alcohol or cannabis. Clients discussed symptoms like dizziness, confusion, or agitation. The therapist highlighted the need for transparency with healthcare providers.', 7, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a harm-reduction group emphasizing the dangers of abrupt withdrawal when poly-drug use is present. Clients learned about seizure risks, cardiac complications, and mood destabilization. The therapist encouraged medically supervised detoxification.', 8, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a session exploring cognitive distortions that minimize awareness of drug risks. Clients examined beliefs like "a little won''t hurt" or "I can control it." The therapist challenged these thoughts through evidence-based discussion.', 9, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group analyzing how certain medications lose efficacy when combined with alcohol or narcotics. Clients discussed experiences of treatment failure due to chemical interference. The therapist emphasized accountability in medication adherence.', 10, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a session on understanding side effects as early warning signs of systemic overload. Clients learned to identify symptoms such as tremors, blurred vision, or irregular heartbeat. The therapist encouraged immediate reporting to medical professionals.', 11, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group highlighting the interaction between mental health medications and recreational substances. Clients reflected on emotional instability and relapse linked to misuse. The therapist reinforced the need for integrated treatment planning.', 12, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a discussion on the long-term neurological risks of combining depressants. Clients examined cognitive decline, impaired motor coordination, and memory loss. The therapist guided reflection on restoring neurological health through abstinence and therapy.', 13, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a session emphasizing the psychological effects of repeated drug side effects, such as increased anxiety, paranoia, or emotional blunting. Clients connected these symptoms to disrupted recovery progress. The therapist stressed psychoeducation and medication review.', 14, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a harm-reduction workshop focusing on overdose prevention. Clients learned to recognize warning signs and the importance of emergency response measures such as naloxone. The therapist highlighted safety planning as a component of relapse prevention.', 15, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a cognitive-processing group addressing ambivalence toward medication use during recovery. Clients explored fears of dependency versus medical necessity. The therapist supported informed decision-making and collaboration with prescribing physicians.', 16, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective session on the emotional aftermath of severe drug side effects. Clients discussed experiences of panic, shame, and hospitalization. The therapist normalized these reactions and encouraged compassionate self-care during recovery.', 17, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group illustrating how liver metabolism impacts drug interaction. Clients learned how alcohol, opioids, and benzodiazepines compete for the same enzymatic pathways, leading to toxicity. The therapist reinforced medical compliance and gradual lifestyle adjustments.', 18, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a group discussion on the cumulative impact of drug misuse on organ systems. Clients identified fatigue, gastrointestinal distress, and concentration deficits as consequences of chronic substance exposure. The therapist connected physical deterioration with emotional instability.', 19, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a closing group integrating health literacy and relapse prevention. Clients summarized key insights about safe medication use, recognizing early signs of interaction, and seeking timely medical intervention. The therapist reinforced empowerment through knowledge and proactive care.', 20, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational session focusing on how substance combinations alter neurotransmitter balance. Clients explored how mixing stimulants and depressants destabilizes serotonin and dopamine levels, intensifying mood swings. The therapist emphasized the connection between neurochemical imbalance and relapse vulnerability.', 21, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective group on the dangers of self-adjusting prescribed dosages without medical guidance. Clients discussed experiences of increased side effects and withdrawal symptoms. The therapist reinforced adherence to treatment plans and professional monitoring.', 22, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a cognitive-behavioral session exploring impulsivity as a risk factor for unsafe drug interactions. Clients identified moments of high-risk decision-making linked to emotional distress. The therapist introduced grounding techniques to delay impulsive use.', 23, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group addressing cross-tolerance and its impact on overdose potential. Clients learned how tolerance to one drug class can increase vulnerability when experimenting with another. The therapist reinforced education as a protective measure.', 24, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a group discussion on how drug interactions interfere with mood stabilizers and antidepressants. Clients shared experiences of emotional flattening or irritability after mixing substances. The therapist explained how chemical interference diminishes psychiatric medication efficacy.', 25, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a harm-reduction session highlighting the importance of communicating openly with healthcare providers about all substance use. Clients discussed fears of judgment and non-disclosure. The therapist emphasized that transparency ensures accurate medication management.', 26, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a group exploring how sedatives and alcohol potentiate respiratory depression. Clients learned to identify early warning signs such as shallow breathing or confusion. The therapist reinforced the importance of seeking emergency medical help immediately.', 27, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective session on how cognitive impairment from drug combinations affects decision-making and safety. Clients discussed experiences of disorientation and poor judgment. The therapist emphasized mindfulness and reality testing to counter distorted thinking.', 28, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group focused on the interaction between methamphetamine and antidepressants. Clients explored how overstimulation of the nervous system can cause panic, insomnia, and cardiac strain. The therapist promoted balanced recovery and self-regulation techniques.', 29, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a session on gastrointestinal and hepatic risks associated with prolonged substance mixing. Clients reviewed how alcohol and painkillers can lead to ulceration and liver damage. The therapist encouraged regular medical evaluations to monitor organ function.', 30, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a process group discussing the emotional effects of experiencing drug-induced side effects such as anxiety and paranoia. Clients shared feelings of fear and isolation. The therapist validated these emotions and provided grounding strategies for stabilization.', 31, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group on the interaction between nicotine and psychiatric medications. Clients learned how nicotine alters drug metabolism and dosage requirements. The therapist encouraged harm reduction through gradual cessation.', 32, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a session emphasizing hydration and nutrition as protective factors against drug toxicity. Clients explored how dehydration worsens side effects and impairs cognition. The therapist provided practical health management strategies to support recovery.', 33, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective discussion about the psychological denial that minimizes awareness of physical risk. Clients recognized avoidance patterns such as rationalization and minimization. The therapist guided insight into developing accountability and informed choices.', 34, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group examining how stimulant and opioid combinations affect cardiovascular health. Clients discussed symptoms such as palpitations and dizziness. The therapist educated participants about cumulative heart strain and risk of arrhythmia.', 35, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a cognitive-behavioral session identifying emotional triggers that lead to risky substance mixing. Clients connected feelings of loneliness and frustration with impulsive behavior. The therapist reinforced emotional regulation skills to interrupt destructive cycles.', 36, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a psychoeducational group explaining serotonin syndrome as a medical emergency caused by drug interaction. Clients reviewed signs such as agitation, tremors, and confusion. The therapist stressed immediate medical attention in such situations.', 37, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a reflective group exploring how medication misuse affects trust in treatment. Clients discussed feelings of shame after concealing substance use from providers. The therapist emphasized honesty as essential to therapeutic alliance and progress.', 38, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a discussion about the long-term cognitive decline associated with repeated drug interactions. Clients explored memory lapses, poor concentration, and slowed processing speed. The therapist linked these deficits to neurotoxicity and encouraged brain-restorative habits.', 39, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a closing group reviewing health management strategies for minimizing drug-related harm. Clients summarized lessons on medication safety, side effect recognition, and early intervention. The therapist reinforced empowerment through knowledge and proactive health behavior.', 40, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational session explaining how prolonged drug interactions can lead to neurochemical imbalance. Clients discussed symptoms such as irritability, mood swings, and impaired focus. The therapist emphasized the importance of ongoing psychiatric evaluation to prevent further deterioration.', 41, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a cognitive-behavioral group identifying high-risk combinations such as alcohol and benzodiazepines. Clients analyzed how these substances amplify sedation and respiratory depression. The therapist reinforced harm reduction through awareness and controlled environments.', 42, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a reflective session on the emotional consequences of experiencing drug side effects. Clients described feelings of fear, confusion, and guilt after medical emergencies. The therapist normalized these emotions and guided self-compassion and relapse prevention.', 43, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group addressing how drug interactions can alter mood-stabilizing medication efficacy. Clients explored how inconsistencies in medication adherence affect emotional regulation. The therapist highlighted the need for collaboration with prescribing providers.', 44, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a harm-reduction group focusing on the dangers of mixing opioids with alcohol. Clients discussed respiratory suppression and blackouts. The therapist encouraged use of emergency resources and regular medical follow-ups.', 45, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a session examining how poly-drug use affects cognitive functioning. Clients shared experiences of forgetfulness, slowed thinking, and disorientation. The therapist reinforced brain recovery through rest, nutrition, and abstinence.', 46, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a process group highlighting the link between substance interactions and emotional instability. Clients identified patterns of agitation and paranoia following use. The therapist guided grounding exercises to manage anxiety and intrusive thoughts.', 47, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a psychoeducational session about the impact of stimulant combinations on the cardiovascular system. Clients discussed symptoms such as increased heart rate, chest pain, and panic. The therapist underscored the importance of immediate medical assessment.', 48, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group exploring the risk of dependency on prescription medications when mixed with illicit substances. Clients reflected on how tolerance builds unpredictably. The therapist emphasized gradual withdrawal under professional supervision.', 49, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a mindfulness-based discussion about body awareness and side effect recognition. Clients practiced identifying early warning signs such as tremors or dizziness. The therapist promoted interoceptive awareness to prevent medical crises.', 50, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Drug Interactions, Side Effects Risks"', v_paragraph_count;

    -- Continuaré insertando más párrafos para completar esta subactividad...
    -- NOTA: El usuario proporcionó más párrafos, continuaré insertándolos

    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a group addressing the emotional triggers that lead to unsafe drug combinations. Clients identified moments of impulsivity and self-sabotage. The therapist provided behavioral strategies to strengthen decision-making and impulse control.', 51, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group analyzing the role of denial in continued risky use. Clients discussed minimizing side effects and ignoring medical symptoms. The therapist reinforced insight and accountability as key elements of recovery.', 52, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a session focusing on long-term organ damage caused by repeated drug interaction. Clients reviewed how the liver and kidneys process toxins. The therapist emphasized hydration, nutrition, and abstinence as protective health measures.', 53, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective group exploring the emotional disconnection caused by chemical interference. Clients described feeling emotionally numb or detached after mixing drugs. The therapist validated these experiences and promoted reconnection through mindfulness.', 54, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational session detailing how serotonin imbalance contributes to mood dysregulation and impulsivity. Clients discussed how certain combinations intensify depressive symptoms. The therapist reinforced medication adherence and emotional monitoring.', 55, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a cognitive-behavioral group exploring how side effects can serve as warning signals for relapse. Clients learned to identify physiological changes—such as headaches or fatigue—as early indicators of chemical imbalance. The therapist emphasized proactive intervention.', 56, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a harm-reduction session focusing on the importance of understanding drug labels and contraindications. Clients reviewed how misinformation increases risk. The therapist encouraged collaboration between clients and healthcare teams for safe medication use.', 57, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group on the impact of substance interaction on sleep cycles. Clients reported insomnia, vivid dreams, or hypersomnia following combined use. The therapist provided psychoeducation on sleep hygiene and neural recovery.', 58, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a reflective session emphasizing emotional consequences of medical complications related to substance use. Clients processed shame, fear, and regret following overdose or hospitalization. The therapist reinforced resilience and the use of coping networks.', 59, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a closing psychoeducational group summarizing major risks associated with drug interactions. Clients identified personal warning signs, emotional patterns, and recovery tools. The therapist reinforced the importance of long-term monitoring and holistic care in maintaining sobriety.', 60, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational session focused on the neurological effects of combined stimulant and depressant use. Clients explored how such mixtures create extreme fluctuations in the central nervous system, leading to anxiety, agitation, or cardiovascular strain. The therapist emphasized the long-term cognitive risks of inconsistent chemical regulation.', 61, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective group exploring the emotional instability triggered by drug side effects. Clients discussed mood swings, irritability, and emotional numbness after substance use. The therapist guided participants in identifying healthier coping mechanisms for emotional regulation.', 62, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group on hepatic toxicity associated with repeated drug interactions. Clients reviewed how the liver metabolizes competing substances, resulting in fatigue and jaundice. The therapist reinforced the value of medical monitoring and harm reduction strategies.', 63, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a discussion about the cognitive impact of drug-induced sleep disturbances. Clients shared experiences of insomnia and fatigue related to medication misuse. The therapist encouraged sleep hygiene and psychoeducation on neural recovery.', 64, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a harm-reduction session explaining the heightened overdose risk of mixing opioids and sedatives. Clients discussed the body''s reduced tolerance after detoxification. The therapist emphasized gradual recovery under medical supervision.', 65, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group on the psychological denial surrounding side effects. Clients identified rationalizations such as "it''s just temporary." The therapist helped reframe side effects as indicators of system overload rather than tolerable discomfort.', 66, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group on serotonin syndrome and its warning signs. Clients learned to recognize agitation, tremors, and confusion as critical symptoms. The therapist reinforced immediate medical response as a non-negotiable safety practice.', 67, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a cognitive-behavioral group examining avoidance behaviors related to health consequences. Clients discussed ignoring physical symptoms to maintain use. The therapist encouraged reality testing and body awareness exercises.', 68, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group focused on the interaction between caffeine, stimulants, and prescription medications. Clients explored how overstimulation leads to anxiety and heart palpitations. The therapist reinforced moderation and hydration for physiological balance.', 69, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational session on long-term neurocognitive decline caused by polysubstance abuse. Clients discussed memory impairment and difficulty concentrating. The therapist introduced neuroplasticity-promoting habits to support recovery.', 70, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a reflective discussion on emotional consequences following drug-induced psychosis. Clients described confusion, fear, and guilt over lost control. The therapist validated these experiences while emphasizing trauma-informed stabilization.', 71, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a group exploring the risks of combining pain medication with alcohol. Clients examined tolerance escalation and the danger of accidental overdose. The therapist emphasized coordination with healthcare professionals to avoid fatal outcomes.', 72, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a psychoeducational group reviewing how dehydration and malnutrition worsen side effects. Clients learned the role of hydration and balanced diet in medication absorption. The therapist encouraged daily tracking to strengthen self-awareness.', 73, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a process group addressing impulsivity as a factor in unsafe drug mixing. Clients discussed making decisions under stress or emotional dysregulation. The therapist taught impulse delay and emotional grounding techniques.', 74, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a session highlighting cardiac complications linked to stimulant abuse. Clients reviewed symptoms such as irregular heartbeat and shortness of breath. The therapist reinforced medical consultation and consistent self-monitoring.', 75, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a cognitive-behavioral group exploring distorted thinking around "controlled" use. Clients challenged beliefs minimizing health risks. The therapist guided reframing to foster insight and accountability.', 76, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a harm-reduction group addressing how combining substances accelerates tolerance and withdrawal. Clients explored the frustration of diminishing effects and escalating doses. The therapist emphasized structured detoxification under clinical oversight.', 77, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist led a psychoeducational group on the neurological impact of prolonged exposure to synthetic drugs. Clients learned about dopamine depletion and emotional dysregulation. The therapist provided coping skills for anhedonia and mood instability.', 78, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist facilitated a reflective session examining the shame and guilt linked to drug-induced side effects. Clients processed the emotional burden of health deterioration. The therapist introduced self-forgiveness and relapse-prevention frameworks.', 79, TRUE),
        (v_activity_id, v_drug_interactions_id, 'IOP Therapist conducted a closing session integrating physical, emotional, and behavioral awareness regarding drug safety. Clients summarized personal insights about medication management and symptom monitoring. The therapist reinforced empowerment through education, consistency, and medical collaboration.', 80, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos adicionales para "Drug Interactions, Side Effects Risks"', v_paragraph_count;

    -- =============================================
    -- SUBACTIVIDAD 2: ADVERSE REACTIONS AND RISKS OF DRUG USE (40 párrafos)
    -- =============================================
    SELECT subactivity_id INTO v_adverse_reactions_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'adverse reactions and risks of drug use'
    LIMIT 1;

    IF v_adverse_reactions_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Adverse Reactions and Risks of Drug Use', 'Understanding adverse reactions and risks of drug use', TRUE)
        RETURNING subactivity_id INTO v_adverse_reactions_id;
        RAISE NOTICE '✅ Subactividad "Adverse Reactions and Risks of Drug Use" creada';
    END IF;

    -- Insertar los 40 párrafos de Adverse Reactions and Risks of Drug Use
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order, is_active)
    VALUES
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a psychoeducational session focused on understanding the physiological and psychological adverse reactions associated with drug use. Clients discussed how substances alter neurotransmitter functioning and impair judgment. The therapist emphasized the importance of recognizing early warning signs of toxicity and dependency.', 1, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a group exploring the short- and long-term risks of substance use on physical health. Clients identified organ systems commonly affected, including cardiovascular and hepatic functions. The therapist guided reflection on harm reduction strategies and relapse prevention.', 2, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational group on the interaction between prescribed medications and illicit drug use. Clients learned about the dangers of polypharmacy and unpredictable reactions. The therapist provided education on medication compliance and open communication with healthcare providers.', 3, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a reflective discussion on the psychological side effects of stimulant use. Clients examined symptoms such as agitation, paranoia, and mood instability. The therapist introduced grounding and coping strategies to manage cravings and dysregulation.', 4, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a cognitive-behavioral session addressing denial and minimization regarding drug-related health risks. Clients explored discrepancies between perceived control and actual harm. The therapist encouraged self-awareness through cognitive restructuring and behavioral accountability.', 5, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational discussion on the neurobiological consequences of substance misuse. Clients reviewed how repeated exposure alters brain reward pathways, leading to tolerance and compulsive behavior. The therapist reinforced the importance of medical monitoring during recovery.', 6, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a group focused on recognizing psychosomatic symptoms related to withdrawal or drug interaction. Clients shared experiences of anxiety, fatigue, and mood swings during detoxification. The therapist normalized these reactions and encouraged adherence to structured treatment plans.', 7, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a reflective group exploring the emotional and behavioral risks of self-medicating with substances. Clients identified patterns of avoidance and emotional numbing. The therapist emphasized the development of adaptive coping mechanisms and emotional regulation skills.', 8, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational session addressing the cumulative health impact of chronic substance use. Clients discussed conditions such as cognitive decline, cardiovascular disease, and immune suppression. The therapist provided education on recovery-based lifestyle changes.', 9, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a discussion on the potential dangers of combining alcohol with prescription medications. Clients examined real-life scenarios illustrating increased sedation, respiratory depression, and impaired coordination. The therapist reinforced the need for responsible medication management.', 10, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a group exploring how substance use contributes to psychiatric instability. Clients discussed how drugs can exacerbate anxiety, depression, and psychosis. The therapist emphasized the necessity of integrated treatment addressing both mental and physical health.', 11, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational group highlighting the risks of counterfeit or unregulated drugs. Clients learned about contamination, incorrect dosing, and unknown chemical compounds. The therapist encouraged informed decision-making and medical consultation.', 12, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a process group on the impact of substance use on emotional awareness. Clients reflected on how drug-induced euphoria suppresses authentic emotional processing. The therapist introduced mindfulness and emotional labeling as recovery tools.', 13, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a session examining the behavioral signs of adverse drug reactions. Clients identified symptoms such as confusion, dizziness, or erratic behavior. The therapist reinforced the importance of early intervention and medical evaluation.', 14, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational discussion on the connection between drug use and impulsive behavior. Clients explored how substances impair frontal lobe function, leading to poor decision-making. The therapist provided education on impulse control techniques and relapse prevention planning.', 15, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a reflective group discussing how withdrawal symptoms can mimic psychiatric disorders. Clients learned to differentiate between substance-induced symptoms and underlying conditions. The therapist emphasized ongoing psychiatric assessment during recovery.', 16, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a psychoeducational session addressing the social risks of drug use, including isolation, stigma, and loss of trust. Clients reflected on interpersonal consequences and the process of rebuilding social support. The therapist guided participants in developing communication and boundary-setting skills.', 17, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a group exploring how long-term substance use impacts cognitive functioning, including memory and attention deficits. Clients discussed personal experiences of mental fog or forgetfulness. The therapist provided education on brain recovery and cognitive rehabilitation strategies.', 18, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a process group focused on emotional triggers that lead to relapse despite awareness of health risks. Clients identified stressors that perpetuate maladaptive coping. The therapist reinforced the use of mindfulness, peer support, and structured routines.', 19, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a closing psychoeducational session reviewing the physiological, psychological, and social risks of drug use. Clients summarized their learning and developed individualized harm reduction goals. The therapist encouraged continued self-monitoring and professional follow-up to maintain progress and prevent relapse.', 20, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a psychoeducational group on understanding the body''s adverse physiological responses to drug toxicity. Clients examined how substance use can compromise cardiac, hepatic, and neurological systems. The therapist emphasized recognizing somatic warning signs as essential for early intervention.', 21, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a reflective session exploring the psychological aftermath of drug misuse. Clients discussed mood instability, irritability, and anhedonia following substance withdrawal. The therapist reinforced emotional regulation and therapeutic adherence as critical components of recovery.', 22, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a group focused on the long-term neurological effects of sustained drug use. Clients reviewed how chemical dependency alters dopamine and serotonin pathways. The therapist provided education on neuroplasticity and recovery potential through abstinence and consistent care.', 23, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a cognitive-behavioral session examining cognitive distortions that minimize drug-related health risks. Clients identified thoughts that justify continued use despite evidence of harm. The therapist encouraged reality testing and the development of insight through guided reflection.', 24, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a psychoeducational discussion on drug-drug interactions and their impact on metabolism and mental functioning. Clients reviewed the importance of medication disclosure to healthcare providers. The therapist emphasized coordination between psychiatric and medical treatment teams.', 25, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a process group exploring the emotional instability that arises during drug withdrawal. Clients identified feelings of irritability, restlessness, and despair. The therapist provided psychoeducation on managing acute symptoms through grounding and supportive care.', 26, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a mindfulness-based session addressing cravings and impulsivity linked to substance use. Clients practiced deep breathing and sensory awareness to regulate urges. The therapist highlighted the role of mindfulness in reducing relapse risk.', 27, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a group focusing on the adverse cognitive effects of stimulant and depressant drugs. Clients discussed difficulty concentrating, memory lapses, and slowed processing. The therapist introduced compensatory cognitive strategies and encouraged ongoing neuropsychological monitoring.', 28, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a psychoeducational group discussing how drug-induced psychosis can mimic primary mental health disorders. Clients explored symptoms such as paranoia and hallucinations. The therapist emphasized the importance of psychiatric evaluation and medication stabilization.', 29, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a reflective discussion on emotional numbing as a maladaptive response to trauma-related distress. Clients examined how substance use serves as emotional avoidance. The therapist guided exploration of alternative emotional regulation techniques and trauma-informed coping.', 30, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a psychoeducational session on how polysubstance use amplifies the risk of unpredictable reactions and overdose. Clients discussed case examples highlighting the dangers of combining stimulants and depressants. The therapist reinforced education on harm reduction and emergency preparedness.', 31, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a group addressing the gastrointestinal and nutritional impacts of chronic drug use. Clients learned how appetite suppression and malabsorption exacerbate fatigue and cognitive decline. The therapist encouraged dietary stabilization and medical follow-up.', 32, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a session examining the emotional guilt and shame associated with drug-related health deterioration. Clients reflected on self-blame and avoidance behaviors. The therapist guided a compassionate reframing process to support emotional recovery and accountability.', 33, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a psychoeducational group on how certain prescription medications can trigger relapse through euphoric effects. Clients discussed the importance of accountability and safe medication management. The therapist encouraged collaboration with prescribing clinicians to reduce risk.', 34, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a reflective discussion on the role of denial in masking the physical decline caused by substance use. Clients explored the emotional defenses that sustain addiction. The therapist utilized motivational interviewing techniques to enhance readiness for change.', 35, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a group examining the social consequences of drug-related health issues, including stigma and relational loss. Clients shared experiences of isolation and mistrust. The therapist reinforced rebuilding support systems through transparency and healthy boundaries.', 36, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a psychoeducational session on recognizing early withdrawal complications such as seizures, dehydration, or elevated heart rate. Clients learned how to respond safely and when to seek emergency care. The therapist underscored the importance of medical supervision during detoxification.', 37, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist led a reflective group addressing emotional dysregulation following drug cessation. Clients reported irritability and emotional blunting. The therapist introduced behavioral activation techniques to promote mood stability and engagement in positive reinforcement.', 38, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist facilitated a psychoeducational discussion about how chronic substance use alters pain perception and tolerance. Clients explored how this physiological change increases risk for both relapse and medical complications. The therapist guided education on alternative pain management strategies.', 39, TRUE),
        (v_activity_id, v_adverse_reactions_id, 'IOP Therapist conducted a closing group summarizing the multifaceted risks associated with drug use—neurological, emotional, behavioral, and social. Clients reflected on their personal experiences and developed individualized relapse prevention strategies. The therapist reinforced ongoing medical compliance and therapeutic engagement to sustain long-term recovery.', 40, TRUE);

    GET DIAGNOSTICS v_paragraph_count = ROW_COUNT;
    RAISE NOTICE '✅ Insertados % párrafos para "Adverse Reactions and Risks of Drug Use"', v_paragraph_count;

    RAISE NOTICE '✅✅✅ COMPLETADO: Health Management Addiction con todas sus subactividades y párrafos insertados ✅✅✅';

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    s.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs
FROM activities a
LEFT JOIN subactivities s ON s.activity_id = a.activity_id
LEFT JOIN activity_paragraphs ap ON ap.subactivity_id = s.subactivity_id
WHERE LOWER(a.activity_name) = 'health management addiction'
GROUP BY a.activity_name, s.subactivity_name
ORDER BY a.activity_name, s.subactivity_name;
