-- =============================================
-- IOP: Coping Skills - MARTES - Adaptive Mechanisms
-- =============================================
-- Este script inserta los 57 párrafos para "Adaptive Mechanisms"
-- de la actividad "Coping Skills" para IOP del día MARTES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Coping Skills"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'coping skills'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Coping Skills" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Coping Skills" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Adaptive Mechanisms"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'adaptive mechanisms'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Adaptive Mechanisms', 'Learning adaptive coping mechanisms for healthy functioning', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Adaptive Mechanisms" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Adaptive Mechanisms" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 57 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on adaptation as an essential human capacity for maintaining psychological equilibrium. The therapist emphasized how individuals recalibrate internal responses to align with external demands, thereby reducing distress and enhancing resilience. Clients were invited to identify situations in which adaptive flexibility promoted stability during periods of change, highlighting adaptation as a foundation for healthy coping.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of compartmentalization as an adaptive mechanism that allows the Ego to separate conflicting cognitions or emotions into distinct domains. The therapist discussed how this strategy can protect individuals from being overwhelmed by dissonant thoughts, while also warning against rigid fragmentation that may inhibit integration. Clients reflected on experiences where compartmentalization created short-term relief but required eventual reconciliation for sustained well-being.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on compensation as a constructive coping mechanism. The group examined how individuals may overinvest in one area of functioning to balance perceived deficits in another. The therapist highlighted how compensation, when consciously directed, can enhance self-esteem and mastery rather than masking vulnerabilities. Participants were encouraged to reframe compensatory behaviors as opportunities for growth rather than avoidance.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on crying as a natural release mechanism associated with emotional catharsis. Clients explored how tears not only serve as a biological discharge of tension but also signal vulnerability and elicit social support. The therapist normalized crying as a restorative process, emphasizing its role in affect regulation and relational bonding. Group members reflected on cultural and personal barriers that limit acceptance of this adaptive behavior.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion on idealization as an adaptive mechanism that can promote hope and motivation when directed appropriately. The therapist highlighted how focusing on the positive qualities of people or circumstances may help individuals navigate stress, while also cautioning against over-idealization that distorts reality. Clients processed examples where selective attention to strengths fostered resilience and facilitated perseverance during adversity.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on post-traumatic growth, underscoring how trauma, while distressing, can catalyze profound personal development. The therapist introduced narratives of individuals who transformed suffering into opportunities for meaning-making, spiritual expansion, and redefined values. Clients were invited to consider ways in which their own adversity had generated inner strength, reinforcing post-traumatic growth as an advanced adaptive process.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group activity on sublimation as one of the most mature adaptive mechanisms. Clients explored how channeling instinctual energy into socially constructive pursuits enhances ego functioning and provides a safe outlet for tension. The therapist encouraged participants to identify personal practices, such as art, exercise, or community service, where sublimation operates naturally. The session emphasized sublimation''s role in transforming inner conflict into productive action.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session exploring compartmentalization as a strategy for managing internal conflict. The therapist explained how individuals separate contradictory thoughts or emotions into distinct mental categories, thus reducing cognitive dissonance and preserving ego stability. The group discussed both the short-term relief this provides and the long-term need for integration to avoid fragmentation.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention on compensation as a mechanism for balancing perceived inadequacies. Clients reflected on how overinvesting in certain abilities or roles can bolster self-esteem when other areas feel deficient. The therapist emphasized the adaptive potential of compensation when used consciously, while noting that excessive reliance may mask deeper vulnerabilities that require acknowledgment.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational discussion on crying as a natural form of emotional release. The group examined how tears not only facilitate physiological regulation but also invite social support and comfort. The therapist normalized crying as an adaptive outlet for distress, counteracting cultural stigmas that often frame it as weakness. Participants identified moments when allowing themselves to cry fostered clarity and relief.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an exploration of identification as an adaptive coping strategy. The therapist highlighted how modeling oneself after valued figures can support ego development, foster social belonging, and strengthen resilience. Clients considered examples of internalizing positive traits from mentors, peers, or cultural figures. The session reinforced the importance of discerning which characteristics enhance self-concept versus those that perpetuate dependency.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group process on intellectualization as a way of maintaining equilibrium by prioritizing logic over affect. The therapist guided clients to recognize how focusing on rational explanations can provide a buffer against overwhelming emotions but may also hinder authentic processing. Group members practiced integrating factual reasoning with emotional awareness, cultivating a more balanced coping approach.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on performing rituals as an adaptive mechanism that provides structure and cognitive space. Clients reflected on how routines and repetitive actions can reduce anxiety by offering predictability during times of uncertainty. The therapist reframed ritualistic behaviors as opportunities for grounding and reflection, while distinguishing between adaptive ritualization and compulsive patterns.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on post-traumatic growth, highlighting how adversity can catalyze transformative change. The therapist underscored how trauma, while painful, can foster resilience, redefined priorities, and deeper meaning-making. Clients shared examples of personal strengths that emerged from hardship, reframing suffering as a potential source of psychological expansion rather than limitation.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided the group in exploring undoing as a coping strategy aimed at symbolically reversing perceived wrongdoings. The therapist explained how corrective actions may reduce guilt and restore a sense of equilibrium for the Ego. Clients reflected on situations where reparative gestures alleviated inner conflict. The session emphasized the distinction between symbolic undoing and genuine accountability in interpersonal repair.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on adaptation as a fundamental mechanism of coping. The therapist highlighted how the capacity to adjust to new circumstances allows individuals to restore equilibrium in the face of stressors. Clients reflected on recent life changes where flexibility promoted stability, and the discussion underscored adaptation as a marker of psychological resilience.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on displacement as an adaptive mechanism for managing affect. The group explored how shifting emotional energy toward safer targets can prevent direct confrontation with threatening stimuli. While recognizing its protective function, the therapist emphasized the need to channel displacement into constructive outlets to avoid relational strain.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a discussion on idealization as a coping strategy that can reinforce hope and motivation during adversity. Clients examined how emphasizing the strengths of a person or circumstance can buffer against despair, while also acknowledging the risks of neglecting limitations. The therapist guided participants toward using idealization consciously, as a temporary support rather than a distortion of reality.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of identification as an ego-strengthening process. The therapist explained how modeling oneself after admired figures may foster belonging and internalize adaptive traits. Clients shared examples of adopting positive characteristics from mentors or peers, reinforcing identification as a mechanism that supports development and social integration.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a session on substitution as an adaptive approach to redirect harmful patterns. The group examined how replacing maladaptive behaviors with healthier alternatives facilitates both self-regulation and growth. The therapist highlighted substitution as a practical strategy for habit change, encouraging clients to view it as a stepping stone toward deeper therapeutic work.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on undoing as a mechanism that symbolically repairs guilt-inducing behaviors. The therapist explained how corrective gestures can reduce inner conflict and restore self-coherence. Clients processed examples of attempts to "make things right" after interpersonal tension, distinguishing between symbolic undoing and authentic accountability.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on post-traumatic growth as an advanced form of coping. The therapist introduced the concept of transforming traumatic experiences into opportunities for meaning-making, resilience, and personal redefinition. Clients reflected on strengths gained from adversity, with the session emphasizing growth as an integrative outcome of adaptive processing.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on adaptive mechanisms as constructive coping strategies that promote psychological balance and resilience. The therapist explained how these mechanisms, such as adaptation, sublimation, and compensation, allow individuals to transform internal conflict into growth-oriented behavior. Clients reflected on times they used adaptive strategies effectively and discussed ways to strengthen these responses during stress.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion on adaptation as a fundamental human capacity to adjust to changing circumstances while maintaining internal stability. The therapist emphasized how flexibility and cognitive reframing reduce distress during transitions. Clients identified specific life changes they had adapted to and practiced developing coping plans that enhance emotional resilience.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on compartmentalization as an adaptive mechanism that allows individuals to manage conflicting emotions or roles without becoming overwhelmed. The therapist discussed how this strategy, when used consciously, promotes focus and stability. Clients explored scenarios where mental separation helped them function effectively and reflected on the importance of later integration for overall well-being.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a psychoeducational activity on compensation as a method of balancing perceived weaknesses by excelling in other areas. The therapist illustrated how this defense, when intentional, builds self-efficacy and personal mastery rather than masking inadequacy. Clients identified personal examples of healthy compensation and discussed how to transform overcompensation into balanced achievement.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of crying as an adaptive emotional release that fosters relief and connection. The therapist normalized crying as a physiological and psychological mechanism for self-soothing and tension reduction. Clients shared experiences where allowing emotional expression promoted clarity and recovery from stress.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a discussion on displacement as a mechanism of redirecting emotional energy toward safer targets in a socially acceptable manner. The therapist emphasized the importance of recognizing when displaced frustration can be transformed into productive activities. Clients reflected on recent experiences of emotional redirection and practiced identifying appropriate outlets for anger or anxiety.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group on idealization as a temporary adaptive process that sustains motivation and hope during adversity. The therapist discussed how focusing on positive aspects of a goal or person can promote perseverance but cautioned against excessive distortion of reality. Clients examined personal examples of idealization and learned to balance optimism with realistic expectations.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on identification as a mechanism that fosters learning and ego development through modeling. The therapist explained how internalizing adaptive traits from mentors or peers can strengthen resilience and social functioning. Clients discussed figures they admire and explored ways to integrate those qualities authentically into their own behavior.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on intellectualization as an adaptive form of emotional regulation that allows individuals to process distress cognitively before confronting affect. The therapist clarified how balancing logic with emotional awareness enhances decision-making and coping efficiency. Clients practiced integrating thought and feeling to approach challenges with both clarity and compassion.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of performing rituals as a healthy behavioral framework for creating stability and reflection. The therapist highlighted how structured routines offer predictability and grounding during periods of uncertainty. Clients developed personal rituals that foster mindfulness, organization, and emotional safety.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational discussion on post-traumatic growth as an advanced adaptive mechanism that transforms suffering into self-development. The therapist described how trauma can catalyze meaning-making, spiritual growth, and renewed appreciation for life. Clients reflected on strengths gained through hardship and articulated ways to sustain resilience in future challenges.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on sublimation as one of the most mature adaptive mechanisms, redirecting instinctual impulses into socially constructive actions. The therapist illustrated how creativity, altruism, and goal-directed work serve as outlets for repressed tension. Clients identified areas where sublimation already operates in their lives and developed strategies to enhance this adaptive channel.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion on substitution as a coping mechanism that replaces harmful or unattainable goals with healthier alternatives. The therapist emphasized how substitution facilitates behavioral change and emotional stability. Clients shared personal experiences of substituting maladaptive habits for productive activities and developed individualized replacement plans.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on undoing as a reparative mechanism that symbolically corrects perceived wrongdoings. The therapist discussed how conscious acknowledgment and corrective action can restore psychological equilibrium. Clients reflected on moments where restitution or apology helped reduce guilt and promoted reconciliation in relationships.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a closing discussion integrating all adaptive mechanisms as tools for balanced coping and emotional intelligence. The therapist encouraged clients to replace avoidance and defensiveness with conscious, constructive strategies that promote growth. Participants identified one adaptive mechanism to apply in real life, reinforcing accountability and personal empowerment.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on adaptive mechanisms as positive coping strategies that promote resilience and psychological balance. The therapist explained how mechanisms such as adaptation, sublimation, and compensation help individuals transform distress into constructive action. Clients explored examples from their daily lives where adaptive responses enhanced problem-solving and emotional regulation.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session focused on adaptation as an essential human ability to adjust to change while maintaining internal stability. The therapist emphasized flexibility, acceptance, and problem-solving as markers of adaptive functioning. Clients reflected on moments of transition and identified personal strengths that supported effective adjustment to life stressors.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group discussion on compartmentalization as an adaptive method for managing conflicting emotions or responsibilities. The therapist explained how temporary separation of thoughts can maintain functionality under pressure. Clients shared experiences where compartmentalization allowed them to focus, while also discussing the importance of emotional integration once stability is regained.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational exploration of compensation as a strategy for balancing perceived weaknesses through the enhancement of other skills. The therapist discussed how conscious compensation fosters self-esteem and motivation rather than masking insecurity. Clients reflected on situations where they transformed inadequacy into mastery, reinforcing self-efficacy as a growth tool.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on crying as an adaptive emotional release. The therapist normalized tears as a healthy physiological and psychological mechanism for reducing internal tension and seeking comfort. Clients explored cultural and personal barriers to expressing sadness and discussed how vulnerability supports emotional healing.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational discussion on displacement as a mechanism for channeling emotional energy into safer or more productive outlets. The therapist highlighted the difference between harmful redirection and adaptive rechanneling through exercise, creativity, or journaling. Clients identified personal experiences of redirecting frustration and developed awareness of healthier alternatives.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of idealization as an adaptive strategy for maintaining optimism and motivation during stress. The therapist discussed how focusing on positive traits of people or goals can foster hope but warned against unrealistic expectations. Clients practiced identifying realistic strengths in themselves and others to sustain balanced motivation.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on identification as a mechanism through which individuals model behavior after admired figures. The therapist explained how adopting positive traits from role models supports ego development and social learning. Clients shared examples of individuals who inspired them and reflected on how identification fosters self-improvement.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention on intellectualization as a temporary adaptive response for managing overwhelming emotions. The therapist explained how focusing on logic provides distance and control during distress, but emotional processing must follow for full resolution. Clients practiced combining cognitive understanding with emotional expression to achieve balance.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on performing rituals as a stabilizing coping mechanism. The therapist illustrated how structure and repetition provide psychological containment, allowing space for reflection and emotional regulation. Clients developed personalized rituals, such as journaling or meditation, to manage anxiety and promote grounding.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group on post-traumatic growth as a transformative response to adversity. The therapist described how trauma can foster self-discovery, strengthened relationships, and new life perspectives. Clients reflected on difficult experiences that led to unexpected personal growth, reinforcing resilience and empowerment.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on sublimation as one of the most mature adaptive mechanisms. The therapist explained how channeling instinctual drives into socially constructive activities—such as art, writing, or volunteerism—reduces distress and builds self-worth. Clients identified current outlets that support sublimation and explored new creative practices.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on substitution as a mechanism for replacing harmful behaviors or unattainable goals with healthier alternatives. The therapist emphasized how substitution supports behavioral modification and emotional stability. Clients shared personal experiences of replacing maladaptive habits with positive routines and developed future coping plans.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on undoing as a reparative mechanism that symbolically corrects perceived mistakes. The therapist discussed how taking corrective actions helps to alleviate guilt and restore internal balance. Clients reflected on moments where restitution or apology strengthened self-esteem and relational trust.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a reflective group integrating the use of adaptive mechanisms to replace destructive patterns. The therapist encouraged clients to recognize the link between awareness and emotional regulation. Participants developed personalized strategies for applying adaptive coping methods, reinforcing accountability and sustained psychological growth.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session highlighting the value of adaptive mechanisms in recovery. The therapist explained that positive coping responses improve stress tolerance, emotional regulation, and interpersonal effectiveness. Clients reflected on their progress in replacing avoidance or denial with adaptive behaviors that enhance overall functioning.', 53),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational activity examining the role of flexibility in adaptation. The therapist emphasized that emotional agility and open-mindedness allow for better adjustment to uncertainty. Clients practiced reframing stressors as opportunities for learning, promoting resilience and problem-solving.', 54),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on the balance between intellect and emotion in adaptive coping. The therapist explained that healthy regulation requires both logical reasoning and emotional awareness. Clients engaged in exercises to identify situations where integration of these elements led to better outcomes.', 55),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration on self-awareness and choice in adaptive functioning. The therapist emphasized that adaptive mechanisms operate most effectively when used consciously rather than reflexively. Clients practiced identifying their automatic responses to stress and developed strategies to replace maladaptive patterns with deliberate coping.', 56),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a closing session synthesizing adaptive mechanisms as markers of psychological maturity. The therapist reinforced that growth involves transforming tension into constructive energy rather than suppression or avoidance. Clients committed to applying adaptive responses in their daily lives, enhancing self-regulation and emotional insight.', 57);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Adaptive Mechanisms" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'coping skills'
AND LOWER(sa.subactivity_name) = 'adaptive mechanisms'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

