-- =============================================
-- IOP: Coping Skills - MARTES - Defense Mechanisms
-- =============================================
-- Este script inserta los 53 párrafos para "Defense Mechanisms"
-- de la actividad "Coping Skills" para IOP del día MARTES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Coping Skills"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'coping skills'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Coping Skills" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Coping Skills" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Defense Mechanisms"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'defense mechanisms'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Defense Mechanisms', 'Exploring defense mechanisms and their adaptive and maladaptive uses', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Defense Mechanisms" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Defense Mechanisms" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 53 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session exploring the role of denial as a defense mechanism commonly activated under conditions of reality anxiety. The therapist highlighted how denial temporarily reduces distress by rejecting threatening stimuli, yet perpetuates maladaptive avoidance. Clients were encouraged to reflect on situations in which they minimized risks or dismissed consequences to alleviate fear. Through guided processing, the therapist emphasized the importance of reality testing and cognitive restructuring as more adaptive alternatives.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on projection as a defense mechanism related to neurotic anxiety. Clients explored how unconscious fears of losing control over instinctual impulses often manifest as attributing undesirable feelings to others. The therapist facilitated group exercises where participants identified instances of externalizing internal conflicts, drawing attention to the relational strain this produces. Psychoanalytic interpretation was introduced to increase insight into unconscious dynamics and foster accountability.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a discussion on moral anxiety and its link to defense mechanisms such as reaction formation. The therapist explained how guilt or shame may be unconsciously transformed into exaggerated opposite behaviors, masking the underlying impulse. Clients analyzed real-life examples where overcompensation was used to preserve self-image while intensifying internal conflict. The therapist guided participants in recognizing the cost of this defense and introduced mindfulness practices to tolerate dissonance without resorting to rigid behavioral extremes.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session examining the defensive operation of intellectualization as a response to overwhelming affect. Clients were invited to recognize how reliance on abstract reasoning serves to distance the self from distress, particularly when facing interpersonal challenges. The therapist modeled language that integrates cognitive and emotional domains, underscoring the therapeutic goal of enhancing affect regulation. Group members practiced reframing personal narratives with balanced attention to both thought content and emotional resonance.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided clients through an exploration of sublimation as an adaptive defense mechanism contrasted with maladaptive strategies such as repression. The discussion focused on how channeling unacceptable drives into socially constructive outlets promotes psychological resilience while preserving internal equilibrium. Clients were encouraged to identify personal activities where sublimation has been spontaneously employed and to consider how this mechanism can be intentionally strengthened. The therapist emphasized sublimation''s role in long-term ego development and conflict resolution.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session addressing reality anxiety and its connection to the defensive operation of avoidance. The discussion emphasized how fear of tangible threats often activates denial or withdrawal as immediate strategies of tension reduction. Clients were guided to explore recent instances in which they minimized or fled from external stressors. The therapist reframed avoidance as an unconscious attempt at ego protection while introducing grounding techniques to strengthen reality testing and adaptive coping.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group process exploring neurotic anxiety as it arises from unconscious conflicts between the Id and the Ego. The therapist highlighted how mechanisms such as repression and displacement emerge when instinctual drives provoke internal alarm. Participants reflected on moments when they redirected affect toward safer substitutes rather than confronting the original source. The intervention underscored the role of insight and affect regulation in dismantling entrenched avoidance patterns.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session examining moral anxiety as the product of the Superego''s internalized prohibitions. The group analyzed how guilt and shame frequently trigger reaction formation, wherein unacceptable impulses are masked by exaggerated virtue. The therapist encouraged clients to identify areas in which rigid overcompensation limited authenticity and emotional flexibility. Strategies for balanced self-evaluation were discussed to foster healthier integration of moral standards.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a discussion on intellectualization as a defense mechanism often employed when emotional intensity feels overwhelming. Clients were invited to explore how distancing through abstract reasoning can provide temporary relief while also impeding authentic affective processing. The therapist modeled language that blended cognitive interpretation with emotional acknowledgment, reinforcing the therapeutic aim of integrating thought and feeling for more adaptive functioning.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided the group through an exploration of projection and its impact on interpersonal relationships. The session emphasized how attributing unwanted internal states to others allows for a temporary reduction of tension but perpetuates conflict and mistrust. Through role-play, clients practiced differentiating between subjective perception and external reality. The therapist introduced reflective questioning techniques to counteract distortion and promote self-awareness in relational dynamics.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an intervention centered on sublimation as an adaptive defense mechanism contrasted with maladaptive strategies like regression. The discussion highlighted how channeling instinctual drives into creative or prosocial outlets contributes to ego strength and resilience. Clients shared examples of transforming frustration into constructive action, reinforcing sublimation as a mature coping resource. The therapist underscored its role in long-term psychological growth and integration of unconscious material.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session exploring the unconscious use of denial as a primary defense mechanism in the context of reality anxiety. The group examined how individuals often minimize or negate threatening circumstances to avoid psychological discomfort. The therapist emphasized the function of denial as a temporary shield for the Ego, while highlighting its long-term limitations in adaptive coping. Psychoeducation was provided on the importance of gradually confronting avoided realities to promote resilience.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention focused on neurotic anxiety and the emergence of repression as a defense strategy. Clients reflected on how unconscious drives may be forcefully excluded from awareness, leading to heightened internal conflict and somatic tension. The therapist encouraged exploration of how unresolved impulses often resurface in disguised forms. Insight-oriented questions were introduced to foster awareness of repressed material and its role in perpetuating anxiety.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group discussion on moral anxiety and the Ego''s reliance on reaction formation to manage feelings of guilt or shame. Participants analyzed how exaggerated adherence to moral codes can conceal unconscious desires deemed unacceptable by the Superego. The therapist explained the defensive nature of overcompensation, underscoring the importance of authenticity and balanced self-concept. Clients were supported in identifying healthier ways of reconciling personal values with inner conflicts.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an intervention centered on intellectualization as a means of detaching from distressing affect. The group examined how an overreliance on abstract reasoning can distort emotional processing, leaving individuals disconnected from authentic experience. The therapist provided corrective feedback, modeling integrative responses that combined cognitive analysis with emotional acknowledgment. Clients practiced reframing personal narratives to incorporate both rational thought and affective awareness.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on the defensive operation of projection, particularly its impact on interpersonal functioning. Clients explored how attributing unwanted impulses or emotions to others provides temporary relief but fosters relational conflict and miscommunication. The therapist facilitated role-play exercises that illuminated discrepancies between internal affect and external attribution. Reflective practices were introduced to strengthen ego awareness and reduce reliance on projection in daily interactions.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of sublimation as a mature and adaptive defense mechanism. The therapist emphasized how instinctual impulses, when redirected into creative or socially valued pursuits, can strengthen ego functioning and diminish intrapsychic tension. Participants were encouraged to identify instances in which sublimation had facilitated constructive outcomes in their lives. The session highlighted sublimation as an essential pathway for psychological growth and integration of unconscious material.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on the role of denial as a primitive defense mechanism often activated under reality anxiety. The discussion explored how individuals unconsciously distort threatening external stimuli by refusing to acknowledge their existence. The therapist emphasized that although denial provides temporary relief, it impedes adaptive coping and reality testing. Clients were guided to identify patterns of avoidance and consider more constructive strategies to face distressing circumstances.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention examining neurotic anxiety and its link to unconscious drives of the Id. The therapist introduced the concept of displacement as a defense mechanism, highlighting how intense affect is redirected toward safer targets. Group members reflected on situations in which anger or fear was projected onto substitute objects or relationships. The therapist framed displacement as a protective but ultimately maladaptive strategy that maintains internal conflict.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a clinical discussion on moral anxiety and its manifestation in feelings of guilt and shame imposed by the Superego. The focus was on reaction formation as a defensive process, whereby unacceptable impulses are masked by exaggerated opposing behaviors. Clients processed examples of over compensatory actions that concealed deeper ambivalence. The therapist underscored the importance of self-reflection and balance in navigating superego demands without rigid overcorrection.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated an exploration of intellectualization as a common strategy to minimize anxiety through excessive reliance on logic. Clients analyzed how emotional detachment allows for temporary stabilization of the Ego but simultaneously obstructs authentic emotional processing. The therapist modeled integrative dialogue combining rational evaluation with affective expression, encouraging participants to practice reframing narratives in ways that included both cognitive and emotional perspectives.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a session on projection as a defense mechanism that externalizes unwanted impulses by attributing them to others. The discussion illuminated how this distortion of reality reduces intrapsychic tension but creates interpersonal conflict and mistrust. Clients engaged in exercises aimed at differentiating between internal affect and external perception. The therapist introduced reflective questioning techniques to increase ego awareness and diminish reliance on projection as a habitual defense.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group process highlighting sublimation as a mature defense mechanism that channels instinctual energy into socially acceptable outlets. The therapist contrasted sublimation with maladaptive strategies such as regression and repression, emphasizing its adaptive role in ego strengthening. Clients shared personal examples of transforming impulses into creative or prosocial pursuits. The session reinforced sublimation as a pathway to psychological growth, adaptive functioning, and tension reduction.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on defense mechanisms as unconscious strategies employed by the Ego to mediate internal conflict between instinctual drives and moral standards. Clients learned to identify how denial, projection, and repression distort reality to minimize anxiety. The therapist guided participants in recognizing personal patterns of defense and explored more adaptive coping alternatives to foster emotional regulation.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion examining the role of reality, neurotic, and moral anxiety in triggering defense mechanisms. The therapist highlighted how unconscious distortions emerge when rational problem-solving fails, and emphasized the value of insight-oriented reflection. Clients processed examples of guilt, avoidance, and fear, linking them to underlying defense responses and exploring healthier emotional processing.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention focused on repression and displacement as mechanisms that unconsciously redirect or suppress unwanted impulses. The therapist explained how unresolved internal conflict manifests through displaced anger or forgotten memories. Clients discussed personal experiences of emotional redirection and practiced grounding techniques to enhance conscious awareness.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a session on intellectualization and rationalization as cognitive defenses used to detach from affective discomfort. Through guided dialogue, clients explored how over-reliance on logic or justification minimizes vulnerability but limits authentic emotional engagement. The therapist encouraged mindful emotional awareness as a corrective practice.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of projection as a defense mechanism that attributes disowned feelings to others. The therapist emphasized how projection reduces guilt but distorts interpersonal perception. Clients identified relational conflicts exacerbated by projection and were introduced to reflective journaling as a means to strengthen self-awareness and accountability.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational group on reaction formation and sublimation as contrasting mechanisms of defense. The therapist explained how exaggerated virtue may conceal unacceptable impulses, whereas sublimation channels them into socially constructive outlets. Clients processed personal examples and discussed the benefits of transforming inner tension into creative or prosocial behavior.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on regression as a behavioral retreat to earlier developmental functioning when faced with stress. The therapist illustrated how reverting to dependency or helplessness temporarily reduces anxiety but undermines adaptive coping. Clients explored age-regressive behaviors and developed strategies to strengthen adult problem-solving capacities.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group activity on denial as an unconscious refusal to acknowledge painful realities. The therapist explained how denial protects against immediate distress but sustains long-term dysfunction. Clients reflected on situations where denial delayed healing and practiced verbal acknowledgment of discomfort as the first step toward change.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a psychoeducational discussion on sublimation as one of the most adaptive defenses of the Ego. The therapist explained how redirecting instinctual impulses into creative or socially acceptable actions promotes growth and mastery. Clients shared personal examples of transforming frustration or anger into productive energy, reinforcing sublimation as a sign of ego maturity.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session exploring Freud and Anna Freud''s contributions to understanding defense mechanisms. The therapist outlined how these processes operate unconsciously to protect the Ego from anxiety arising from internal or external conflict. Clients connected psychoanalytic theory to everyday behavior, identifying how insight can foster greater emotional integration and psychological flexibility.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group reflection on the purpose of psychoanalysis in bringing unconscious defenses into awareness. The therapist discussed techniques such as free association and dream analysis as methods to uncover repressed material. Clients engaged in experiential exercises to increase insight into their defensive patterns and to reframe avoidance into conscious self-exploration.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on moral anxiety as guilt-driven tension rooted in the Superego''s moral standards. The therapist emphasized how perfectionism and excessive self-criticism often emerge from this conflict. Clients practiced self-compassion and cognitive reframing to reduce internalized shame and enhance self-acceptance.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group focused on neurotic anxiety as the internal fear of losing control over instinctual drives. The therapist illustrated how this anxiety activates mechanisms like repression and reaction formation. Clients analyzed how fear of judgment or punishment shaped their defenses and explored grounding exercises to strengthen ego control.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group examining how defense mechanisms distort perception to reduce tension. The therapist explained the paradox of temporary relief versus long-term dysfunction that occurs when reality is denied or altered. Clients discussed the importance of mindful confrontation of fear to achieve emotional authenticity and cognitive clarity.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a closing group focused on integrating awareness of defense mechanisms into daily functioning. The therapist emphasized that recognizing patterns such as avoidance, projection, or rationalization fosters emotional intelligence and relational health. Clients developed individualized plans to replace unconscious defenses with conscious, adaptive coping responses.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational group focused on defense mechanisms as unconscious processes used by the Ego to manage internal conflict and reduce anxiety. The therapist discussed Freud''s structural model of personality, emphasizing how the Id, Ego, and Superego interact in creating psychological tension. Clients learned to identify personal defenses such as denial, repression, and rationalization, and explored how bringing these patterns into awareness can promote adaptive emotional regulation.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on reality, neurotic, and moral anxiety as the three primary forms of tension described by Freud. The group explored how fear of external danger, internal impulses, or moral transgression activates defense mechanisms that distort perception to reduce distress. Clients reflected on their own sources of anxiety and practiced mindfulness-based awareness to replace avoidance with conscious coping.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational discussion on denial and rationalization as common defenses that protect the Ego from overwhelming affect. The therapist explained how denial suppresses recognition of painful truths, while rationalization provides false logic to justify behavior. Through guided self-reflection, clients identified instances where these defenses interfered with growth and explored acceptance-based strategies to foster authenticity.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of projection and displacement as mechanisms that redirect uncomfortable emotions toward others or substitute targets. The therapist explained how these processes reduce internal tension but often create interpersonal conflict. Clients discussed real-life examples of misplaced anger or blame and practiced emotional ownership as a path toward healthier communication.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a session on repression and regression as unconscious retreats from distressing material. The therapist illustrated how repression pushes painful memories out of awareness, while regression involves reverting to earlier developmental behaviors for safety. Clients processed how these mechanisms maintain avoidance and developed insight into using mature defenses for emotional resilience.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on sublimation as one of the most adaptive defense mechanisms. The therapist explained how unacceptable impulses can be transformed into socially beneficial outlets such as art, exercise, or creative expression. Clients explored personal examples where channeling negative emotions into productivity supported self-growth and emotional balance.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group discussion on intellectualization as a cognitive defense that prioritizes logic over emotion. The therapist described how this detachment serves to regulate anxiety but often prevents authentic emotional processing. Clients practiced integrating affective language into narratives, reinforcing the importance of emotional congruence and psychological flexibility.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational group on reaction formation as a defense in which individuals overcompensate by acting in the opposite way of their true feelings. The therapist demonstrated how exaggerated behaviors or beliefs can mask underlying fear or guilt. Clients reflected on moments of incongruent behavior and discussed self-acceptance as a foundation for emotional honesty.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on moral anxiety and the role of the Superego in shaping guilt and shame. The therapist highlighted how strict internalized standards can produce chronic self-criticism and reinforce defensive behavior. Clients examined their internal dialogue and practiced self-compassion to balance moral integrity with psychological well-being.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on the function of the Ego in moderating impulses and moral restrictions through defense mechanisms. The therapist explained how the Ego strives to maintain equilibrium by distorting or transforming reality to manage anxiety. Clients engaged in self-assessment exercises to identify personal defense patterns and discussed methods for increasing self-awareness and ego strength.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session exploring Freud and Anna Freud''s theoretical contributions to understanding unconscious defenses. The therapist described how awareness of these mechanisms supports psychoanalytic insight and emotional integration. Clients connected the concepts to their own lived experiences, identifying how awareness of defense patterns can reduce avoidance and improve emotional processing.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group on the adaptive and maladaptive functions of defense mechanisms. The therapist clarified that while defenses serve to protect the psyche from anxiety, excessive reliance on them can lead to distortion of reality and relational difficulties. Clients differentiated between temporary protective responses and long-term maladaptive avoidance, committing to practice self-observation as a tool for growth.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session examining Freud''s view of anxiety as a motivational force for change. The therapist highlighted how tension between the Id, Ego, and Superego triggers defense activation, prompting behavioral and emotional regulation. Clients explored their own experiences of internal conflict and learned grounding techniques to tolerate anxiety without resorting to denial or projection.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational discussion on dream analysis and free association as tools to uncover repressed material within psychoanalytic therapy. The therapist emphasized how repressed fears and unresolved conflicts manifest symbolically in dreams and behaviors. Clients practiced reflective dialogue to identify unconscious themes contributing to current emotional distress.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a reflective group on self-observation of defense patterns in daily life. The therapist encouraged clients to view defensive behaviors not as failures but as signals of underlying unmet needs or fears. The group processed how developing insight into their defenses fosters greater self-regulation, accountability, and emotional maturity.', 53);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Defense Mechanisms" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'coping skills'
AND LOWER(sa.subactivity_name) = 'defense mechanisms'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

