-- =============================================
-- IOP: Coping Skills - MARTES - Attack Mechanisms
-- =============================================
-- Este script inserta los 58 párrafos para "Attack Mechanisms"
-- de la actividad "Coping Skills" para IOP del día MARTES
-- =============================================

DO $$
DECLARE
    v_activity_id UUID;
    v_subactivity_id UUID;
    v_paragraph_count INTEGER;
BEGIN
    -- Obtener la actividad "Coping Skills"
    SELECT activity_id INTO v_activity_id
    FROM activities
    WHERE LOWER(activity_name) = 'coping skills'
    LIMIT 1;

    IF v_activity_id IS NULL THEN
        RAISE EXCEPTION 'Actividad "Coping Skills" no encontrada. Ejecuta primero el script de creación de la actividad.';
    END IF;

    RAISE NOTICE '✅ Actividad "Coping Skills" encontrada con ID: %', v_activity_id;

    -- Obtener o crear la subactividad "Attack Mechanisms"
    SELECT subactivity_id INTO v_subactivity_id
    FROM subactivities
    WHERE activity_id = v_activity_id
    AND LOWER(subactivity_name) = 'attack mechanisms'
    LIMIT 1;

    IF v_subactivity_id IS NULL THEN
        INSERT INTO subactivities (activity_id, subactivity_name, description, is_active)
        VALUES (v_activity_id, 'Attack Mechanisms', 'Understanding and managing aggressive coping responses', TRUE)
        RETURNING subactivity_id INTO v_subactivity_id;
        RAISE NOTICE '✅ Subactividad "Attack Mechanisms" creada con ID: %', v_subactivity_id;
    ELSE
        RAISE NOTICE '✅ Subactividad "Attack Mechanisms" ya existe con ID: %', v_subactivity_id;
    END IF;

    -- Eliminar párrafos existentes para esta subactividad (para evitar duplicados)
    DELETE FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '🗑️  Párrafos existentes eliminados para evitar duplicados';

    -- Insertar los 58 párrafos
    INSERT INTO activity_paragraphs (activity_id, subactivity_id, paragraph_text, paragraph_order)
    VALUES
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on acting out as a maladaptive coping response. The therapist explained how individuals may externalize internal distress through impulsive or disruptive behavior rather than engaging in reflective processing. The group analyzed how acting out provides immediate release but ultimately undermines self-regulation. Clients were encouraged to explore alternative methods of tension management that reinforce ego strength.', 1),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of displacement within the spectrum of attack mechanisms. The discussion highlighted how frustration or hostility often becomes redirected toward less threatening targets, creating relational strain. The therapist emphasized that although displacement temporarily relieves internal pressure, it perpetuates conflict when not recognized. Clients reflected on instances where redirected aggression masked the true source of distress.', 2),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational session on the fight-or-flight reaction, emphasizing its evolutionary roots in survival but also its maladaptive manifestation in interpersonal contexts. The therapist explained how aggression may emerge as a defensive response to perceived threat, even in non-threatening environments. Group members examined personal triggers that activate physiological arousal, and grounding strategies were introduced to interrupt automatic attack responses.', 3),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on passive aggression as a covert form of hostility. Clients processed how indirect behaviors, such as procrastination, sarcasm, or intentional inefficiency, can serve as disguised attacks against others. The therapist underscored the unconscious dynamics of resentment and avoidance underlying passive aggression, encouraging the development of direct communication as a healthier alternative.', 4),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on projection as an attack mechanism. The group examined how attributing one''s own unacceptable feelings to others provides temporary relief from guilt but erodes trust and interpersonal functioning. The therapist highlighted the importance of self-reflection in differentiating between internal affect and external reality, reinforcing projection as a defense that distorts relationships.', 5),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention on reaction formation within the context of aggressive defenses. The therapist explained how individuals unconsciously mask unacceptable impulses by adopting the opposite stance, often in exaggerated form. Clients discussed how rigid adherence to opposite behaviors can conceal unresolved hostility and reinforce internal conflict. The session emphasized the therapeutic value of confronting ambivalence directly.', 6),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on trivializing as a defensive attack mechanism. The therapist explained how minimizing the significance of threatening issues may function as a subtle invalidation of others'' experiences, thereby maintaining emotional distance. Clients reflected on times when they downplayed serious matters to avoid confrontation. The therapist reframed trivializing as a defense that can harm trust and encouraged acknowledgment of issues in their true proportion.', 7),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on acting out as a maladaptive strategy for handling inner conflict. The therapist explained how impulsive or disruptive behaviors serve as external discharges of internal pressure, bypassing reflective processing. Clients identified situations where they gave in to frustration rather than addressing the underlying affect. The intervention emphasized the need for impulse regulation and constructive expression of emotions.', 8),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on displacement within the framework of attack mechanisms. The therapist highlighted how anger or hostility often becomes redirected toward safer, less threatening targets. Group members explored the unconscious relief this provides and the collateral damage it causes to relationships. Clients were encouraged to recognize displacement in real time and redirect energy into adaptive outlets.', 9),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a discussion on the fight-or-flight reaction as a primitive response to perceived threat. The group examined how physiological arousal may predispose individuals to aggressive responses even in non-threatening interpersonal contexts. The therapist explained the neurobiological basis of hyperarousal and guided clients in practicing grounding skills to interrupt automatic aggressive patterns.', 10),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group process on passive aggression as a covert form of attack. Clients analyzed how indirect resistance, such as procrastination, sarcasm, or intentional inefficiency, allows resentment to be expressed without open confrontation. The therapist emphasized how passive aggression erodes trust and perpetuates interpersonal conflict. Participants were introduced to assertive communication as an alternative strategy.', 11),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided an exploration of projection as an attack mechanism that distorts interpersonal perception. The therapist explained how attributing one''s own unacceptable impulses to others reduces internal guilt but fosters relational hostility. Clients reflected on times when projection created unnecessary conflict and distorted reality testing. The intervention reinforced the importance of self-reflection and accountability to diminish reliance on projection.', 12),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on reaction formation within the spectrum of aggressive defenses. The therapist explained how adopting a polar-opposite stance conceals underlying hostility, often manifesting in exaggerated displays of virtue or compliance. Clients discussed how this defense complicates authentic communication and perpetuates ambivalence. The group was encouraged to recognize incongruence between inner affect and outward behavior.', 13),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on trivializing as a mechanism that minimizes significant issues to avoid discomfort. The therapist explained how diminishing the weight of a problem can act as a subtle attack on the experiences of others by invalidating their perspective. Clients explored instances where trivialization escalated interpersonal conflict. The therapist highlighted the importance of acknowledging problems proportionately as a pathway toward resolution.', 14),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of acting out as an externalized response to unresolved intrapsychic conflict. The therapist explained how impulsive behaviors represent a bypass of reflective capacity, leading to short-term relief but long-term maladjustment. Clients reflected on situations where frustration translated directly into misbehavior, and the session emphasized impulse regulation strategies as healthier alternatives.', 15),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on displacement as an aggressive defense mechanism. The therapist highlighted how hostility toward an unsafe or inaccessible target is unconsciously redirected to a safer substitute. Clients shared examples where anger was projected onto unrelated relationships, and the therapist emphasized the relational damage caused when underlying conflicts remain unaddressed.', 16),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group discussion on the fight-or-flight reaction as an automatic physiological response to perceived threat. The therapist explained how hyperarousal can manifest in disproportionate aggression, particularly in interpersonal contexts that do not warrant such intensity. Clients examined their own triggers and practiced grounding techniques to reduce reactivity and promote self-control.', 17),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a process group on passive aggression as an indirect manifestation of hostility. The therapist explained how covert resistance, through sarcasm, withdrawal, or intentional inefficiency, serves to undermine relational dynamics. Clients analyzed patterns of masked resentment and were encouraged to practice assertive communication to decrease reliance on passive-aggressive behaviors.', 18),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session examining projection as an attack mechanism that externalizes unwanted impulses. The therapist clarified how attributing unacceptable affect to others may temporarily relieve guilt but distorts interpersonal perception. Group members reflected on past conflicts intensified by projection, and the therapist introduced self-monitoring tools to promote accountability and reduce distortion.', 19),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on trivializing as a subtle yet harmful attack mechanism. The therapist highlighted how minimizing the significance of important issues invalidates others'' experiences and serves as a covert expression of hostility. Clients processed moments when trivialization escalated relational conflict, and the therapist encouraged proportional acknowledgment of problems as a foundation for conflict resolution.', 20),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on acting out as a defense mechanism characterized by impulsive or disruptive behavior in place of emotional reflection. The therapist explained how acting out offers temporary tension release but reinforces maladaptive cycles of avoidance. Clients discussed moments where frustration translated into impulsive actions and were encouraged to practice emotional regulation and self-monitoring as alternatives.', 21),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of displacement as a mechanism where anger or hostility toward an inaccessible target is redirected to a safer substitute. The therapist described how displacement provides momentary relief yet damages relationships and perpetuates avoidance. Clients reflected on recent situations where misdirected emotion caused conflict and discussed strategies for expressing anger assertively and safely.', 22),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a psychoeducational discussion on the fight-or-flight reaction as a physiological and psychological response to perceived threat. The therapist explained how this automatic mechanism, while adaptive in survival contexts, becomes maladaptive when overactivated in interpersonal situations. Clients identified personal triggers for aggressive or defensive reactions and practiced grounding techniques to interrupt impulsive responses.', 23),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on passive aggression as an indirect manifestation of hostility and resistance. The therapist explained how behaviors such as procrastination, sarcasm, or withdrawal mask unresolved anger and erode trust. Clients analyzed patterns of passive defiance in their relationships and were guided toward assertive communication as a healthier form of emotional expression.', 24),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group on projection as a mechanism that attributes one''s own unwanted feelings or impulses to others. The therapist illustrated how this distortion reduces internal guilt but creates interpersonal tension and miscommunication. Clients practiced reflective awareness to differentiate between internal affect and external perception, fostering accountability and emotional insight.', 25),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a discussion on reaction formation as a mechanism that conceals unacceptable impulses by adopting an exaggerated opposite stance. The therapist explained how this creates psychological incongruence and emotional strain. Clients reflected on times they overcompensated through moral rigidity or false positivity and explored ways to align authentic feelings with behavior.', 26),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on trivializing as a subtle attack mechanism used to minimize the significance of distressing experiences. The therapist discussed how making light of serious matters serves as a defense against vulnerability but invalidates others'' emotions. Clients shared experiences of minimizing problems and practiced acknowledgment and empathy to strengthen interpersonal understanding.', 27),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group exploration of acting out as a maladaptive form of emotional discharge. The therapist highlighted how impulsive behaviors often bypass cognitive processing and perpetuate shame and conflict. Clients were guided through self-awareness exercises to recognize precursors to acting out and develop alternative coping strategies such as mindfulness or verbal expression.', 28),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational discussion on displacement and projection as interrelated forms of externalized defense. The therapist emphasized how redirecting or misattributing emotions displaces responsibility and disrupts relationships. Clients examined how these defenses have manifested in their lives and practiced identifying emotional ownership to enhance self-regulation.', 29),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group on the psychological roots of aggression as expressions of internal anxiety and fear. The therapist explained how unacknowledged vulnerability often manifests as attack behaviors to regain a sense of control. Clients reflected on the emotional origins of their anger and learned strategies to express assertiveness without hostility.', 30),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session examining fight-or-flight activation in response to interpersonal stress. The therapist discussed how physiological arousal—such as rapid heartbeat or tension—can escalate into aggression if not regulated. Clients practiced grounding and breathing techniques to calm the nervous system and promote emotional containment.', 31),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational group on passive aggression and its impact on relational dynamics. The therapist emphasized how avoidance-based hostility can undermine trust and communication. Clients explored the emotional function behind passive defiance and role-played scenarios using assertive communication as a corrective behavioral skill.', 32),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session on projection as an interpersonal distortion. The therapist explained that attributing one''s inner conflicts to others leads to chronic misunderstanding and resentment. Clients engaged in reflective dialogue to increase awareness of their own projections and strengthen emotional boundaries.', 33),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a group exploration of reaction formation and its relationship to guilt and repression. The therapist described how moral overcompensation masks internal ambivalence and hinders authentic expression. Clients examined examples of rigid behavior patterns and developed insight into integrating opposing emotions.', 34),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational intervention on trivializing as a subtle but damaging defense. The therapist explained how minimizing important issues serves as an emotional avoidance tactic that invalidates oneself and others. Clients discussed personal examples and practiced using validation statements to replace minimizing behaviors.', 35),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a reflective discussion on aggression as a disguised coping mechanism. The therapist explained that aggressive defenses often originate from perceived helplessness or fear of vulnerability. Clients identified emotional triggers underlying aggressive reactions and practiced reframing them as opportunities for emotional growth.', 36),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group on the transformation of attack mechanisms into adaptive responses. The therapist emphasized how awareness of reactive patterns allows for the redirection of anger into assertiveness, creativity, or problem-solving. Clients developed individualized strategies for converting hostility into constructive communication.', 37),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session integrating insight into unconscious drives that contribute to aggressive defenses. The therapist highlighted how unprocessed frustration from the Id may seek release through attack mechanisms. Clients explored links between suppressed emotions and reactive behavior, fostering insight for healthier impulse management.', 38),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a closing session synthesizing attack mechanisms within the framework of ego defense. The therapist reinforced that while these mechanisms offer short-term relief, they compromise relational harmony and emotional stability. Clients committed to applying adaptive coping skills to replace aggression with self-regulation, empathy, and reflective awareness.', 39),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group discussion on acting out as a defense mechanism rooted in impulsivity and emotional dysregulation. The therapist described how individuals externalize inner conflict through behavior rather than reflection, seeking immediate relief from tension. Clients processed examples of impulsive reactions and discussed the benefits of mindfulness and emotional containment as healthier alternatives.', 40),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on displacement as a mechanism where anger or frustration is redirected toward less threatening targets. The therapist explained how this defense temporarily alleviates anxiety but damages relationships and perpetuates avoidance. Clients reflected on situations where they misdirected emotion and practiced using assertive communication to address the real source of conflict.', 41),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a psychoeducational exploration of the fight-or-flight response and its connection to aggression. The therapist emphasized that this physiological survival mechanism can manifest as hostility when activated unnecessarily. Clients examined personal triggers that elicit defensive aggression and practiced grounding exercises to reduce hyperarousal and improve self-control.', 42),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group session on passive aggression as an indirect form of hostility expressed through avoidance or noncompliance. The therapist explained how covert behaviors such as procrastination or sarcasm serve to mask resentment. Clients identified passive-aggressive patterns in their interactions and were guided to replace them with assertive and transparent communication.', 43),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session on projection as an externalizing defense where one attributes unacceptable emotions to others. The therapist highlighted how projection distorts reality and damages trust. Clients discussed experiences of misperceiving others based on their own insecurities and developed insight into recognizing projection as a cue for self-reflection.', 44),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of reaction formation as a mechanism where individuals overcompensate by exhibiting behaviors opposite to their true emotions. The therapist described how this defense creates emotional incongruence and psychological strain. Clients reflected on instances of exaggerated virtue or politeness masking deeper frustration, learning to embrace authenticity as a step toward integration.', 45),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a session on trivializing as a subtle form of avoidance and emotional invalidation. The therapist explained how minimizing important issues can function as an attack by dismissing others'' emotions or one''s own pain. Clients examined moments when they downplayed problems and practiced validating emotions as a means to improve relational empathy and awareness.', 46),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a group intervention addressing aggressive coping patterns as maladaptive defenses. The therapist emphasized how outward hostility often conceals vulnerability and fear of rejection. Clients explored how unexpressed anxiety manifests as irritability or control and developed adaptive strategies such as assertive dialogue and stress management.', 47),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational discussion on the transformation of attack mechanisms into adaptive behaviors. The therapist illustrated how awareness of reactive defenses allows individuals to redirect anger into productive expression. Clients developed action plans for using self-awareness and empathy to prevent interpersonal harm.', 48),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a reflective group on acting out and emotional avoidance. The therapist explained that impulsive outbursts often serve as a distraction from underlying sadness or guilt. Clients processed recent incidents where reactivity replaced introspection and practiced techniques for emotional labeling and delayed response.', 49),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a session on displacement and relational conflict. The therapist described how frustration with authority or stressors is often unconsciously transferred to safer relationships. Clients examined the emotional consequences of misdirected aggression and practiced identifying the original source of anger to improve accountability.', 50),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a psychoeducational session on projection as a relational distortion. The therapist emphasized that attributing unwanted qualities to others allows temporary relief but perpetuates misunderstanding. Clients engaged in self-reflective exercises to recognize projection and strengthen emotional ownership.', 51),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group discussion on passive aggression as a communication barrier that damages trust. The therapist illustrated how unspoken hostility fosters confusion and resentment. Clients practiced converting covert resistance into assertive statements to promote transparency and psychological safety.', 52),
    (v_activity_id, v_subactivity_id, 'IOP Therapist guided a discussion on reaction formation as an unconscious strategy for avoiding unacceptable impulses. The therapist described how exaggerated kindness or compliance may conceal frustration or envy. Clients shared examples of internal conflict hidden beneath overcontrolled behavior and explored methods for balanced emotional expression.', 53),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a group exploration of trivializing as a defensive attempt to downplay anxiety-provoking experiences. The therapist explained that minimizing distress creates emotional disconnection and invalidation. Clients reflected on moments when humor or detachment masked discomfort and practiced acknowledgment as a step toward authentic coping.', 54),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a psychoeducational session integrating all attack mechanisms as forms of displaced emotional tension. The therapist emphasized how aggressive defenses serve to protect the ego from perceived weakness. Clients analyzed recurring behavioral themes and developed personalized strategies for converting aggression into constructive communication.', 55),
    (v_activity_id, v_subactivity_id, 'IOP Therapist led a group on the emotional roots of hostility. The therapist discussed how unprocessed grief, shame, or insecurity often manifests as verbal or behavioral aggression. Clients identified underlying emotions associated with anger and practiced using emotional literacy to de-escalate interpersonal conflict.', 56),
    (v_activity_id, v_subactivity_id, 'IOP Therapist facilitated a session focused on converting aggression into assertiveness. The therapist explained how controlled emotional expression and clear boundaries enhance psychological health. Clients role-played scenarios to practice assertive communication and reinforce empathy during high-stress interactions.', 57),
    (v_activity_id, v_subactivity_id, 'IOP Therapist conducted a closing group summarizing attack mechanisms as maladaptive coping responses. The therapist highlighted the importance of recognizing aggression as a signal of internal imbalance rather than external threat. Clients committed to monitoring emotional triggers and applying adaptive strategies that promote reflection, self-regulation, and respectful dialogue.', 58);

    -- Verificar inserción
    SELECT COUNT(*) INTO v_paragraph_count
    FROM activity_paragraphs
    WHERE activity_id = v_activity_id
    AND subactivity_id = v_subactivity_id;

    RAISE NOTICE '✅✅✅ COMPLETADO: % párrafos insertados para "Attack Mechanisms" ✅✅✅', v_paragraph_count;

END $$;

-- Verificar inserción
SELECT 
    a.activity_name,
    sa.subactivity_name,
    COUNT(ap.paragraph_id) as total_paragraphs,
    MIN(ap.paragraph_order) as min_order,
    MAX(ap.paragraph_order) as max_order
FROM activities a
JOIN subactivities sa ON sa.activity_id = a.activity_id
JOIN activity_paragraphs ap ON ap.subactivity_id = sa.subactivity_id
WHERE LOWER(a.activity_name) = 'coping skills'
AND LOWER(sa.subactivity_name) = 'attack mechanisms'
GROUP BY a.activity_name, sa.subactivity_name
ORDER BY a.activity_name, sa.subactivity_name;

